### ISSUE TITLE
Search parameter code sample includes a `cropLength=0`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1010]
After consulting with @curquiza, setting `cropLength` to 0 is an edge case with no obvious application, but we use it as an example in `reference/features/search_parameters`.

I believe it's a good idea to change this example to something that more closely mirrors what a user is likely to do.

**Comment by vaish567** [comment]
Hello @guimachiavelli I would like to work on this issue :)

**Comment by guimachiavelli** [comment]
Hello @vaish567 

I'm terribly sorry about the delay in getting back to you. We have a major version of the docs in the works and that dominated my attention and time these past few weeks.

The section containing this example has been reworked on #924 and will be fixed when we merge that into `master`, something that should happen next week.

Thank you so much for the willingness to give us a helping hand and my apologies once again.

**Comment by guimachiavelli** [comment]
Closed by #924
