### ISSUE TITLE
Standardize formatting of links to the API reference

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1015]
We haven't quite decided on a format yet, but when we have we would like to standardize the formatting of links to the API references from outside that section, and possibly the way we write about API endpoints in general.

See [this conversation](https://github.com/meilisearch/documentation/pull/989#pullrequestreview-686256154) about pros and cons of different styles.

**Comment by maryamsulemani97** [comment]
Closing as we currently use the "get document endpoint" format everywhere except when we’re talking specifically about the GET or POST search endpoints or in the telemetry table
