### ISSUE TITLE
golang is missing in the reference doc

### ISSUE THREAD

**Issue by johnhaha** [meilisearch/documentation#1022]
I found that golang is missing in the reference doc code example, wish this could be fixed soon.

**Comment by dichotommy** [comment]
@johnhaha Hi John, thanks for creating an Issue about this! We are actively working to resolve this problem and are certain it will be fixed soon. Will keep you posted 😎

**Comment by johnhaha** [comment]
That will be great, you guys are awesome🔥👍

**Comment by dichotommy** [comment]
@johnhaha We figured it out! The culprit was a sneaky `tab` character that found its way into our YAML. This should now be entirely fixed, so I'm closing the issue. Please let us know if you have any other feedback, and have a great day! 😄
