### ISSUE TITLE
Correct PHP synonyms code sample

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#1028]
According to [this issue discussion](https://github.com/meilisearch/MeiliSearch/discussions/1482#discussioncomment-974678) the update synonyms PHP code samples are not correct

**Comment by CaroFG** [comment]
@alallema already did a [PR](https://github.com/meilisearch/meilisearch-php/pull/161) on the PHP repo, I assume code samples are synced with the docs?

**Comment by dichotommy** [comment]
> I assume code samples are synced with the docs

The contents of the `.code-samples.meilisearch.yaml` are used to generate the code tabs on site build. We just triggered a re-build so this issue should be solved 🙌🏻 

Thank you @CaroFG and @alallema 🙏🏻 🔥 🚀 🍪
