### ISSUE TITLE
Netlify deploys sometimes use `readme.md` as the docs home

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1030]
This has happened twice so far:

1. when manually merging #983 (2021-06-15);
2. when using Bors to merge #998 (2021-07-08);
3. in a preview of PR #1027 (2021-07-12).

In all cases, triggering a re-build (manually via Netlify's web interface or automatically via e.g. a new commit in a PR)  fixed the issue.

The first instance of the issue was recorded shortly after we started using Bors in this repo. We are not sure whether this is just a coincidence or if the issue is actually connected to Bors.

Comparing Netlify logs between correct and incorrect deploys doesn't seem to reveal any relevant information: there is a slight variation in the number of generated files, but as far as we can see this type of variation is normal and does not influence the deploy in any way.

**Comment by guimachiavelli** [comment]
[According to an old Vuepress issue](https://github.com/vuejs/vuepress/pull/23#issuecomment-584553906), there are cases when a site uses `index.md` when built in development and `readme.md` when built in production mode. (thanks, @dichotommy ❤️)

This does sound like what's happening to us. The suggested fix in the thread is to rename `readme.md` to `readme.markdown`.

**Comment by guimachiavelli** [comment]
@bidoubiwa suggested this bug might be related to PR #965; more specifically, on line 54 of `create/how_to/digitalocean_droplet.md` we enclose a couple of words between single quotes. @bidoubiwa's theory is that this might be throwing off vuepress.

That seems like a fairly basic error that vuepress should have accounted for, but it's worth looking into if the above suggested quickfix doesn't solve the issue.

**Comment by bidoubiwa** [comment]
There is a solution that might prevent us for ever serving a build that uses `readme.md` as the landing.
Cypress, a front end testing framework, tests how UI appears on a browser (using browsers executable).

Using the [cypress netlify plugin](https://www.cypress.io/blog/2020/03/30/run-cypress-tests-on-netlify-using-a-single-line/) we can cancel the publish when elements of the landing are not appearing on the final build. 

```js
it('Contains Welcome message', () => {
  cy.contains(
    "Welcome to the MeiliSearch documentation. Here you'll find everything you need to learn and create with our lightning fast search engine."
  )
})
```
