### ISSUE TITLE
GET search query parameters types are not specified

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#1033]
Contrary to `POST /search` which has all its query parameter type well documented, the `GET /search routes` has only a description and the default value: 

See [POST](https://docs.meilisearch.com/reference/api/search.html#search-in-an-index-with-post-route) route and [GET](https://docs.meilisearch.com/reference/api/search.html#search-in-an-index-with-get-route) route

**Comment by guimachiavelli** [comment]
Unless I misunderstood, @dichotommy's plan was to replace all GET documentation with a note stating that the route exists, listing some of its uses and strongly advising people to use POST whenever possible.

Are there any differences between the routes in terms of parameters they accept?

**Comment by dichotommy** [comment]
What @guimachiavelli said is correct, at some point we plan to remove the dedicated GET section and focus on maintaining documentation for the POST route. It's not related to v0.21, but I see no reason why this can't be bundled with the rest of the changes in the `prepare-docs-v0.21` branch. Adding it as a checklist item.

**Comment by bidoubiwa** [comment]
> Unless I misunderstood, @dichotommy's plan was to replace all GET documentation with a note stating that the route exists, listing some of its uses and strongly advising people to use POST whenever possible.

> Are there any differences between the routes in terms of parameters they accept?

This would mean that the documentation becomes incomplete. As the way you construct search parameters are different in both versions. 
If we keep both versions it is because their are use cases for both. I would advice on keeping the information but maybe store it in a more discreet place. 

Also, I would advice against changing the title of an issue haha I was so hard confused that I doubted myself in this title change.
If an issue ought to be made with this title, lets open a new one, close this one, and relate to this discussion to explain this or that choice. Here you are going against the issue's problematic 🥲

**Comment by guimachiavelli** [comment]
Thanks for that, @bidoubiwa.

Sorry if I'm being slow, but as far as I can see the two routes accept the same arguments and are in a certain sense identical, with the main difference being preflight checks (and possibly security?).

If that is the case, couldn't we just bundle them together and state POST is preferred for this and that reason?

As a visual aid: 

![Screen Shot 2021-07-13 at 13 26 16](https://user-images.githubusercontent.com/1923183/125444417-e18dede2-3fd9-4f5d-ada0-aeee4a64637a.jpg)

Or is this a stupid idea?

**Comment by bidoubiwa** [comment]
Hey @guimachiavelli unfortunately not. See https://github.com/meilisearch/MeiliSearch/issues/1489

**Comment by guimachiavelli** [comment]
@bidoubiwa says that `attributesToRetrieve: "title, description"` is a best practice when using the search `GET` route and that `attributesToRetrieve: ["title", "description"]` is not recommended.

Do I understand the linked issue correctly in that it's not that `attributesToRetrieve: ["title", "description"]` is not recommended, it flat out won't work in v0.21?

**Comment by bidoubiwa** [comment]
The behavior of the `GET /search` route in v0.21 is described here: https://github.com/meilisearch/specifications/pull/58

**Comment by guimachiavelli** [comment]
#1818 added types for `GET /search` parameters. Closing this issue.
