### ISSUE TITLE
Add FAQ answer about customization options

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1034]
Make the distinction between:

- Configuration: command-line options and flags. Added at launch, and instance must be relaunched in order to alter them. Tend to be more technical and focus on instance behavior (not search behavior).
- Settings: index-specific settings, including a number of special field types. Tend to focus on manipulating search results/relevancy. These changes are indexed, meaning that altering the settings object requires all objects to be re-indexed (this process happens automatically). It also allows for a speed increase over run-time customization, such as parameters.
- Parameters: ways of altering the behavior and response of search. Focuses on getting information about and manipulating search results. Very fast operations (most of the time) that are performed at run-time, so could theoretically slow search results. 

Instead of being an FAQ answer, this could also be an article-style guide introduction to the different ways of customizing your MeiliSearch experience (in `/learn/advanced_topics/` for example). Or even a blog post!

**Comment by maryamsulemani97** [comment]
I think this can be an FAQ with a brief description of each option and then link each to its dedicated guide

**Comment by guimachiavelli** [comment]
In my crusade against the FAQ, I prefer the idea of a short guide briefly explaining the differences and then linking to each guide. `learn/configuration/overview.md` or something like that would be a good location.
