### ISSUE TITLE
Add `expected value` fields to configuration options

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1039]
#976 adds an explicit `default value` field for each configuration option. This is helpful, but can still be improved by adding an `expected value` field stating what sort of value each option requires.

For example:

```
Log level

Environment variable: MEILI_LOG_LEVEL
CLI option: --log-level
Default value: 'INFO'
```

Could become 

```
Log level

Environment variable: MEILI_LOG_LEVEL
CLI option: --log-level
Default value: 'INFO'
Expected value: one of `ERROR`, `WARN`, `INFO`. or `DEBUG`
```

This must be done for all configuration options.

_Note: currently all options require a value, even those whose behaviour is closer to a flag than actual option (e.g.: `--no-analytics` must be accompanied by a value in order to be valid, but it doesn't matter what that value actually is: `--no-analytics=true` and `--no-analytics=false` have, confusingly, the same effect)._

**Comment by aniketh-varma** [comment]
Would like to take up this issue, if someone can guide me in doing the same :)

**Comment by guimachiavelli** [comment]
Hi @aniketh-varma — great that you're interested in giving us a hand!

Each configuration option requires an extra bit of text describing what is the expected value for that option. For example, `--max-index-size` expects an integer and `--master-key` expects an alphanumeric string.

In essence, `Expected value` should just be a very quick summary of information already available on the text describing the option.

Does that give you something to start with? Let me know! 😄

**Comment by aniketh-varma** [comment]
Yeah got it! Please assign me this issue, I will make the appropriate changes :D
