### ISSUE TITLE
Broken links on blog.meilisearch.com

### ISSUE THREAD

**Issue by sylque** [meilisearch/documentation#1040]
Sorry to post here, didn't find a better place.

Page https://blog.meilisearch.com/meili-fundraise/, the link "open roadmap on GitHub" is broken.

Page https://blog.meilisearch.com/meilisearch-open-business-plan-v0-1/, the link "Meet the team (WIP)" is somewhat broken: you end up with the error message _You do not have access to Meilisearch. Please contact an admin to add you as a member_.

**Comment by guimachiavelli** [comment]
Hello @sylque and thanks for taking the time to open this issue! 

We'll update the broken links in these posts shortly, but in the meanwhile you can check our roadmap here https://roadmap.meilisearch.com/ and read a bit on some of our team members here  https://meilisearch.notion.site/MeiliSearch-Team-b7f24733f4944fa9b09fd518d6fc3eff

**Comment by guimachiavelli** [comment]
Blog updated with fixes for reported broken links, so I'm closing this issue. Thanks again for notifying us!
