### ISSUE TITLE
Add better explaination of implicit index creation (lazy index) 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#1043]
In the [documents core concept](https://docs.meilisearch.com/learn/core_concepts/documents.html#structure) it would be interesting to explain that when you add documents in an index that does `not exist`, the index will be created automatically.

**Comment by bidoubiwa** [comment]
In [`indexes` core concept](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-creation) it could be an idea to talk about the implicit index creation. Apparently not only `POST /documents` creates the index in the background. 

In the [index creation](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-creation) part we can talk about it.

**Comment by guimachiavelli** [comment]
Closing this in favour of #873, since both argue for a better explanation of implicit index creation. 

Adding the suggestions here as a comment there.
