### ISSUE TITLE
Clean up code samples

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1062]
There are code samples in our `.code-samples.meilisearch.yaml` that are not used anymore and need to be removed. Most of the ones we are aware of are related to v0.21, but it is possible that there are others.

Thus, there are two main tasks here:

1. Check that all code sample flags (using `ack` or something of the sort) are used at least once throughout the docs;
2. Remove those that do not return any results

- [x] `search_parameter_guide_filter_2`
- [x] `search_guide_1`
- [x] `search_guide_2`
- [x] `faceted_search_walkthrough_facets_distribution_1` (thanks @curquiza!)
- [x] `search_parameter_guide_filter_1` (thanks @curquiza!)
- [x] `faceted_search_walkthrough_filterable_attributes_1`

Once all unused code samples have been removed from the docs, we must also:

- [x] Update the template file (`.vuepress/public/sample-template.yaml`) (thanks, @bidoubiwa!)
- [ ] Notify the integrations team of the final changes

**Comment by bidoubiwa** [comment]
Changes should be updated in the [template file as well](https://github.com/meilisearch/documentation/blob/master/.vuepress/public/sample-template.yaml)
