### ISSUE TITLE
Obsolete React guide

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#1068]
Some users encounter trouble when trying to integrate MeiliSearch with their react application, because they base their work on the [documentation guide](https://docs.meilisearch.com/create/how_to/meilisearch_react.html). See [this issue](https://github.com/meilisearch/meilisearch-js/issues/983).

Especially, the GitHub repository [used as an example](https://docs.meilisearch.com/create/how_to/meilisearch_react.html#prerequisites) for this guide uses an old version of MeiliSearch and meilisearch-js. It does not even use [`react-meilisearch`](https://github.com/meilisearch/meilisearch-react/).

I don't suggest any clear solution, just saying this is a guide we can consider to re-do by our self one day 🙂

**Comment by curquiza** [comment]
Hello @zehawki!

Thanks for your feedback, sorry for the inconvenience when using instant-meilisearch, I get note of it!

As a company, we need to provide more than a search engine, but also all the needed integrations so that every kind of developer can use MeiliSearch and integrate it into their project as easily as possble.
That's why your feedback on our integration is important, so that we can improve them! Thank you for this.

**Comment by guimachiavelli** [comment]
After some internal discussions, we have decided this guide will be part of an upcoming new resource outside of the @meilisearch/docs-team current purview.
