### ISSUE TITLE
Pre-prod documentation on Netlify does not display all the `cURL` code samples

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#1070]
This is a known problem: the pre-prod documentation does not display all the samples in the tabs. This is expected since our "code-samples fetcher" plugin only fetches the code-samples on `master` and our dev-branch is `prepare-vX.X.X` and not `master`. 

We could find a solution to make the code-samples fetcher for pre-prod and not only for prod so that our users can completely use it, for example by passing a branch name that would replace `master`

See the user confusion here: https://github.com/meilisearch/MeiliSearch/issues/1603#issuecomment-902921302

**Comment by guimachiavelli** [comment]
Not that we shouldn't try to address this sooner, but I believe this issue will be fixed when we migrate to docusaurus.

**Comment by dichotommy** [comment]
> I believe this issue will be fixed when we migrate to docusaurus.

We are no longer planning to migrate to Docusaurus. Instead, we have spoken about implementing a form of naive versioning for the v1 launch: tagging version release branches and deploying these branches as separate sites on Netlify. This issue would create problems for this approach—with the current code samples fetcher, all different versions of the docs would display the same code samples from master—so it may need to be fixed beforehand.

**Comment by maryamsulemani97** [comment]
closing as we use Vercel instead of Netlify on the new site.
