### ISSUE TITLE
Make it obvious that filterableAttributes do not work with nested arrays and objects

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#1126]
Recently, we've had several questions on slack community about whether or not one can filter on nested arrays / objects.
After discussing it with @gmourier, we've come to the conclusion that ATM it's too complicated to throw an error or a warning when a user adds that type of field values to the `filterableAttributes`, and we are under the impression that this information goes unnoticed in the documentation.

**Comment by CaroFG** [comment]
Plus, the documentation states that `Fields containing object values will throw an error.` which is false. No error is thrown, it is silently ignored.

**Comment by bidoubiwa** [comment]
Also related documentation: 
https://docs.meilisearch.com/reference/under_the_hood/datatypes.html#data-types

As stated to @maryamsulemani97 the example is very bad in `object` and should look like this: 

```json
{
  "id": 1,
  "whatever": {
     "movie_id": "asdasda",
      "title": "Kung Fu Panda" 
   }
}
```
