### ISSUE TITLE
Document how to configure meilisearch whe using systemctl

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#1143]
How do we change the payload size limit?  How do we add our options?

**Comment by curquiza** [comment]
I did not find it in the docs, sorry if it's already present :)

**Comment by curquiza** [comment]
@guimachiavelli isn't related to https://github.com/meilisearch/documentation/issues/1011

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
Closing in favor of #1011
