### ISSUE TITLE
Curl tab disapeared in the code samples

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#1152]
It starts with the javascript tab instead of curl tab

**Comment by guimachiavelli** [comment]
Can confirm this. Has anyone touched the documentation deploy process recently? I'm seeing this on Netlify's deploy logs:

```
11:11:37 AM:  CODE-SAMPLE-FETCHER  Warning: the sample file could not be fetched
11:11:37 AM:         SDK: cURL,
11:11:37 AM:         url: https://raw.githubusercontent.com/meilisearch/documentation/main/.code-samples.meilisearch.yaml
11:11:37 AM:         StatusError: Not Found
```

The problem is on line #3: netlify is looking for code samples on `main` instead of `master`.
