### ISSUE TITLE
The documentation is still talking about wordsPosition

### ISSUE THREAD

**Issue by thijndehaas** [meilisearch/documentation#1158]
My `getAllUpdateStatus` function gives the following error for the `updateRankingRules` function:
`Invalid criterion wordsPosition`

But it is stil documented here:
https://docs.meilisearch.com/create/how_to/meilisearch_react.html#search-ranking

When I search for it in github I find the following text:
```
"wordsPosition" => {
    warn!("The criteria `attribute` and `wordsPosition` have been merged \
        into a single criterion `attribute` so `wordsPositon` will be \
        ignored");
    None
}
```

**Comment by thijndehaas** [comment]
Update: when I remove the wordsPosition I receive the following error when searching:
`The sort ranking rule must be specified in the ranking rules settings to use the sort parameter at search time`

**Comment by CaroFG** [comment]
Hi @thijndehaas, the guide you've linked is obsolete. There is a warning just below the title

![Capture d’écran 2021-10-04 à 10 02 26](https://user-images.githubusercontent.com/48251481/135815189-99b7f048-78b4-4a08-9686-0d3aa67b79e7.png)

Sorry for the inconvenience 🙏 

MeiliSearch latest version (v0.22) contains six built-in ranking rules: words, typo, proximity, attribute, sort, and exactness, in that default order. You can learn more about them in [the dedicated section of the documentation](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#ranking-rules).

**Comment by guimachiavelli** [comment]
As @CaroFG, said, this article is woefully out-of-date and needs to be rewritten. Apologies for the confusion.
