### ISSUE TITLE
Some code samples are not used in the documentation

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#1160]
The following code samples are not used in the documentation but are present in the [code sample file](https://github.com/meilisearch/documentation/blob/master/.code-samples.meilisearch.yaml)

- `search_guide_1`
- `search_guide_2`
- `faceted_search_walkthrough_facets_distribution_1`
- `search_parameter_guide_filter_1`

⚠️ this is not an exhaustive list, I did not check every single example, you might want to check the whole list 🙂

**Comment by guimachiavelli** [comment]
Closing this in favour of #1062. 

I have merged the reported samples into the previous issue.

Thanks for reporting!

**Comment by curquiza** [comment]
Thank you gui, sorry not to have checked this issue before :)
