### ISSUE TITLE
Blogpost link under "Understanding LMDB" is broken.

### ISSUE THREAD

**Issue by NickCis** [meilisearch/documentation#1199]
The [Understanding LMDB](https://docs.meilisearch.com/reference/under_the_hood/storage.html#understanding-lmdb) section of the documentation has the following text:

> The choice of LMDB comes with certain pros and cons. In order to understand this choice, its upsides and downsides, we need to have an insight on how LMDB impact size and memory usage. This is well explained in a **blogpost of LMDB** and we are trying to summarize it here

The link under _"blogpost of LMDB"_ is currently broken, it links to: https://www.symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization which yields a 404. I couldn't find the blogpost on google, so I don't know if there is an updated link for the blogpost.

**Comment by guimachiavelli** [comment]
Hello @NickCis! Nice catch, thanks for letting us know =)

@curquiza, I'm not familiar with the actual contents of the now missing blogpost: do you think someone on core could points us towards a similar resource?

**Comment by guimachiavelli** [comment]
I think that in the short term we should link to the wayback machine (great idea, @dichotommy), but perhaps we could also ask the original author if they're ok with us republishing the article on our blog (obviously crediting them and etc)?

**Comment by Kerollmops** [comment]
Hey just wanted to inform you that [the blog post has been moved to this page](https://www.symas.com/post/understanding-lmdb-database-file-sizes-and-memory-utilization).
