### ISSUE TITLE
Add documents API code sample should demonstrate primaryKey

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1213]
The code samples for [add or replace documents](https://docs.meilisearch.com/reference/api/documents.html#add-or-replace-documents) (`"add_or_replace_documents_1"`) + [add or update documents](https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents) (`"add_or_update_documents_1"`) should probably demonstrate how to use the optional `primaryKey` parameter.

@meilisearch/integration-team , would this be doable for all integrations?

**Comment by curquiza** [comment]
I agree the primary key should not contain `id` :)

`reference_number` is a good idea, but I let the documentation team decide on the final code sample. The integration team will update their code samples accordingly :)

**Comment by maryamsulemani97** [comment]
closed in PR #1242
