### ISSUE TITLE
Organise GitHub labels

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1251]
We have reached the extremely counterproductive number of 39 labels in this repo. It is hard to navigate and choose them, let alone be completely sure we are applying the correct label to an issue or PR.

A tentative list of stuff I think we should keep:
- P0 to P4: these don't say much about an issue, but help us prioritise tasks;
- good first issue: these are great for external contributors;
- new release: useful for our own organisation when planning content for new releases;
- technical, style, rewording, code sample: these all seem good to describe what is the main area of concern of an issue;
- blog: while the blog does not belong to this repo, we do get the occasional request;

These make 12 in total. I think the fewer we have, the better and would like to try and stay under 15 total.

This number excludes seasonal labels like hacktoberfest, which we can create and delete as necessary.

Pinging the rest of the @meilisearch/docs-team so I'm not the lone Warden and Protector of Label Integrity.

**Comment by dichotommy** [comment]
All in favor of changing @guimachiavelli 's job title to "Warden and Protector of Label Integrity"?

**Comment by dichotommy** [comment]
We did this today!

We also kept: blocked, bug, dependency.
We created: new content.
We will remove shortly: hacktoberfest-accepted, discussion (will be transferred to GitHub Discussions)
