### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1270]
### Discussed in https://github.com/meilisearch/documentation/discussions/1263

<div type='discussions-op-text'>

<sup>Originally posted by **fharper** January  6, 2021</sup>
Let's be allies and make this change that means a lot.

Here is a [blog post](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main) that explain a little more why it's important, and how to easily do it. It will be a bit more complicated with automation, but we still should do it!</div>

**Comment by dichotommy** [comment]
Will not be done, replaced by migration to Docusaurus

**Comment by tpayet** [comment]
Just saw that this issue close and I believe it could be done very quickly.

Will you let me some time to check this out this afternoon?

**Comment by guimachiavelli** [comment]
I believe the reason we closed this is that the new docs website will be in a different repo, so it felt like a bit unnecessary to change it on this repo when the plan is to migrate soon anyway.

**Comment by tpayet** [comment]
Okay, thanks. 
To my understanding, there is no clear date as to when we can expect the new doc website when this change can be done quickly.
If one of you gives me their approval, I can do it in the coming days 😁

**Comment by dichotommy** [comment]
> The change that needs to be done is changing master to main on GitHub as the default branch + updating Netlify deployment to deploy main instead of master? Am I missing something?

- Update CI files to use main instead of master
- Update link to curl samples in `sdks.json`

That's what I can think of off the top of my head. Would it affect `bors` as well? 👁️

**Comment by tpayet** [comment]
So I started, here is the TODO:
- [ ] Update deployment branch name on Netlify from master to main
- [ ] Update default branch name on GitHub from master to main
- [ ] Update in everyone's local repository the default branch name from master to main (@maryamsulemani97, @guimachiavelli, @dichotommy )
- [ ] Merge #1979 to update branch name in GitHub repository for GitHub CIs, `sdks.json`
