### ISSUE TITLE
Create page for demos + sites using us in production

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1272]
It's helpful for new users to experience searching w/ MeiliSearch as quickly as possible; searching w/ it cannot be compared to watching a gif or being told that MeiliSearch is fast.

This page should be created in What is MeiliSearch section.

**Comment by guimachiavelli** [comment]
We're slowly adjusting the focus of the docs so our content is more strictly technical.

@meilisearch/devrel-team, can you confirm whether you're interested in taking this on? Totally alright to say no if that doesn't fit your current goals.

**Comment by ferdi05** [comment]
Sorry for not responding to this earlier @dichotommy @guimachiavelli 
It's actually something I asked @Strift to work on, but we haven't really found time to make much progress afaik.

This issue already exists [in our repo](https://github.com/meilisearch/devrel/issues/66), but we could refer to this one for extra context. up to you @Strift 
In any case, @guimachiavelli feel free to close it. Thanks!

**Comment by guimachiavelli** [comment]
Great, thanks for the update!

Closing as not planned.
