### ISSUE TITLE
Review asynchronous updates page

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1273]
This page has been the victim of a lot of content bloat over the last year and needs to be reviewed. Should be made more brief, focused, clear.

Note that this feature is changing in v0.25, so this may happen as part of that release.

**Comment by maryamsulemani97** [comment]
Rename [Asynchronous operations](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html) to include the word “tasks”, e.g. “Tasks and asynchronous processes”.

**Comment by maryamsulemani97** [comment]
We could move the “[Summarized task object](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html#summarized-task-objects)” table to the API reference overview page. Under the “[Response body](https://docs.meilisearch.com/reference/api/overview.html#response-body)” section
