### ISSUE TITLE
Add a configuration guide to the documentation

### ISSUE THREAD

**Issue by regzon** [meilisearch/documentation#1278]
**Description**
I've faced an issue of a lack of documentation of MeiliSearch [configuration](https://docs.meilisearch.com/reference/features/configuration.html) both in the [official guide](https://docs.meilisearch.com/create/how_to/aws.html) and in this repository's readme.

**Basic example**
I've needed to change the default payload size limit but found that there's no documentation that would help me. After some investigation I've found that there's an env file (`/var/opt/meilisearch/env`) that contains all environment variables which are loaded to the root's env by sourcing this file.

I think that such investigations could be avoided by having a dedicated section in the documentation.

Also, while trying to find configuration file, I've found paths for the DB and dumps - they could be documented too :)

**Comment by dichotommy** [comment]
Related to #1011 #1143 #995

**Comment by regzon** [comment]
Sorry, I should have searched issues in the documentation repo first :)

Is this issue still needed (as the #1011 exists)?

**Comment by dichotommy** [comment]
Nope, if you're okay with it @regzon I'll close it shortly :)

And no worries, always happy to get feedback directly from our users! 🤝 

Out of curiosity, do you think the three-step procedure described in #1011 would have solved your problem, or would you have needed more information than what's currently present on the issue?

**Comment by regzon** [comment]
> Out of curiosity, do you think the three-step procedure described in #1011 would have solved your problem, or would you have needed more information than what's currently present on the issue?

The initial problem could be solved with the method described in #1011, but I'd prefer to use the method I've described in this issue description - edit `env` file. It's just more convenient for me.

**Comment by dichotommy** [comment]
Thanks @regzon ! Closing this.
