### ISSUE TITLE
MeiliSearch 101

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1279]
We would like to offer new users a more streamlined introduction to all of MeiliSearch's features than that provided by our not-so-quick [Quick Start](https://docs.meilisearch.com/learn/getting_started/quick_start.html). 

Using [Vercel's Getting Started](https://vercel.com/docs/get-started) as a reference, we aim to create **a frictionless "welcome to MeiliSearch" tour in multiple chapters**.

It should include a truly quick Quick Start as chapter 0 (only installation/deployment and _possibly_ adding documents).

Its focus should be on introducing and demonstrating, not teaching or documenting. It should always prioritize breadth over depth.

**Comment by guimachiavelli** [comment]
I wonder if the concepts of "Getting started" and "Welcome to MeiliSearch tour" detract from each other. 

Trying to put myself in the position of the user, "Getting Started" makes me think of a quick guide covering installation, basic configuration and basic usage. As an experienced user, I wouldn't expect it to hold much value for me, except perhaps when I want to, idk, launch a local instance for a quick test. As a new user, "Getting Started" would probably be the first thing I click; after entering it, I would probably skim read it to see how quick this guide actually is.

A "Welcome to MeiliSearch tour" gives me different vibes. What is the goal of this tour? Or, to put it another way, what do we want a user to have at the end of this tour? Is it supposed to be more of a "look at everything MeiliSearch can do" thing or "this is how you can quickly start using MeiliSearch's features"? Perhaps my biggest question here is: who is this for?

(In case my tone comes of as aggressive or doubtful, it's totally not my angle, I just feel it's important to understand what this document is before giving more feedback.)

**Comment by maryamsulemani97** [comment]
I think what we currently have is a mix of both. It starts of with a "Getting Started" which is as you mentioned a quick guide covering installation, basic configuration and basic usage. It then turns into a "Welcome to MeiliSearch tour", giving the user a brief introduction/demonstration on the major features so they have an idea of what MeiliSearch has to offer.

For me, the purpose of this guide is to give an introduction to MeiliSearch, how to set it up, start searching, configure it, and then some of the major features. That would be helpful for new users who can follow along. I think it will also be useful for advanced users who skim through it for testing some features.

What do you guys think?

**Comment by dichotommy** [comment]
Thank you @guimachiavelli for bringing all of this up.

> "Getting Started" makes me think of a quick guide covering installation, basic configuration and basic usage.

Wouldn't this be more of a "quick start"? 🤔 Well, I guess there's a lot of overlap. I think what you described is accurate to how most software docs approach "getting started" ([including us](https://docs.meilisearch.com/learn/getting_started/quick_start.html)), but we are purposefully taking a different path for the new one.

Our new approach is inspired by [Vercel's Getting Started guide](https://vercel.com/docs/get-started), which sets aside many of the hallmarks of getting started guides and tutorials (learning through doing; covering only extreme basics; completing a step-by-step project) in favor of a rapid and relatively "shallow" introduction to a large number of topics. The prioritization of speed and breadth over depth is what lead me to describe this as a "welcome tour" approach.

> What is the goal of this tour? Or, to put it another way, what do we want a user to have at the end of this tour?

At the end of this tour, we want readers to:

- Possess a "mental map" of MeiliSearch, particularly relating to which parts of the search experience they can customize. They don't need to know the name of a given parameter or how to use it, as long as they know that it exists, what it can do or modify, and how to find it again.
  - Be aware of the three main "groups" of MeiliSearch customization—Settings object, Configuration, and Search parameters—and the fact that they possess different contexts
- Have a basic understanding of the steps required to create a search experience with MeiliSearch, particularly parts of the process that are poorly documented such as front-end integration.

> Perhaps my biggest question here is: who is this for?

This is for developers who are interested in MeiliSearch as a software and want to know more about what it can do. They may not have experience with similar software, and they may not be interested in immediately creating a project with it. They want to know what tools MeiliSearch gives them to shape the search experience, and get a sense of how difficult it would be to work with.

It's **not** for startup CEOs who want to know about MeiliSearch's features from a high-level perspective (landing page should cover them), or devs who have already used Algolia and want to immediately start working on a MeiliSearch project (quick start + API references should cover them).

> Is it supposed to be more of a "look at everything MeiliSearch can do" thing or "this is how you can quickly start using MeiliSearch's features"?

Much closer to the former. It's a "here are the tools MeiliSearch gives you".

The goal is not to impress or demonstrate the maximum potential of MeiliSearch—we'll leave this to marketing and demos—nor is it to get users immediately working with the product.

The goal is to show them the capabilities of MeiliSearch so they have a complete view of the product before diving into the mundanities of using it (e.g. setting the primary field, communicating with the instance, understanding async updates, troubleshooting errors, best practices, deployment).

**Comment by dichotommy** [comment]
In light of these goals, should the new getting started include a brief section on Security, or not?

Security doesn't have to do with shaping search; it generally falls into the category of "necessary to use MeiliSearch" rather than "reason to use MeiliSearch". However, an easy-to-use security system with permissions management, multi-tenancy etc. can in and of itself be a feature for some people.

It also relates to the third goal of the new getting started, "Have a basic understanding of the steps required to create a search experience with MeiliSearch, particularly parts of the process that are poorly documented".

**Comment by guimachiavelli** [comment]
Thanks for the comprehensive reply, @dichotommy.

I'm still digesting everything, but I realise I might have misunderstood something very important. I assumed a sequential getting started would completely replace our current quick start, but this indicates I was completely wrong:

> It's not for startup CEOs who want to know about MeiliSearch's features from a high-level perspective (landing page should cover them), or devs who have already used Algolia and want to immediately start working on a MeiliSearch project (quick start + API references should cover them).

If the idea is to have both the sequential getting started and the quick start, I think only one of these should use the word "start" so users only have on answer to the question "how do I start using this thing?"

**Comment by bidoubiwa** [comment]
I don't this security information is required in a getting started since it's about having as quickly as possible a running MeiliSearch with some basic information on how to play with it. It is also something hard to grasp and only useful when the user is way past the getting started state as they are looking into putting MeiliSearch in production.

I would add that part in a `production` guide.

**Comment by dichotommy** [comment]
> If the idea is to have both the sequential getting started and the quick start, I think only one of these should use the word "start" so users only have on answer to the question "how do I start using this thing?"

That's a very good point. It also relates to how we approach and think of this guide. I think a lot of the confusion around this guide has to do with this name, "getting started", and the associations it conjures. It seems to make most people think of "the bare minimum required to run MeiliSearch, add documents, and perform a basic search." This is exactly what I think a "quick start" should cover.

On the other hand, the guide we're working on now might be more accurately described as an "overview", although [Vercel's Getting Started](https://vercel.com/docs/get-started) is still the best reference for it (that's where the naming problem stems from). This overview should:

- Go past where most quick starts end, moving onto MS's features
- Provide a more abstract approach to the software: focusing on what you can do with MeiliSearch and worrying less about how—that's for specific topic guides
- Be read, not used as a template or followed like a tutorial
- Contain mostly "simplified" code samples (i.e. representing MS internal objects and variables as JSON, rather than displaying a `curl` or SDK command to modify them)

I hope this helps clarify the style and scope of this guide.

Would it help if we referred to it as the "overview" rather than the "getting started"? 🤔

**Comment by bidoubiwa** [comment]
If the title is overview it makes more sense! 

Would it be something like that? I'm creating fake title to understand how you imagine it in a `"UX"` perspective.

- Quick Start
  - Instal and run
  - Add documents
  - Search
  - Integrate
- Overview
   - Explore search features
   - Customise your index
   - Secure your MeiliSearch
   - Prepare for production


In which case I think it does not scare the user, at the contrary, they know where to go next if needed

**Comment by dichotommy** [comment]
@bidoubiwa Yes! Except, small difference, I had imagined making the quick start the "chapter 0" of the Overview, e.g.

- Overview
  - Chapter 0: Quick Start
    - Install or deploy
    - Add documents
    - Search
    - Web interface
  - Chapter 1: Customizing relevancy
    - Ranking rules
    - Searchable attributes
    - Displayed attributes
    - Stop words
    - Synonyms 
  - Chapter 2: Filtering and sorting
    - Filtering
    - Sorting
    - Geosearch
  - Chapter 3: Adding a visual UI
    - Instant MeiliSearch
    - Manipulating results (highlight, crop, limit)
    - Faceted search
  - Chapter 4: Configuration and security
    - Protecting MeiliSearch
    - Changing the database path
    - Brief summary of other configuration options (max db size options, payload size option, possibly snapshots and dumps)

What do you think? The idea is that at the end of the quick start, we would give links to API reference for those who want to get started creating something, and link to the next chapter for those who want to follow the overview.

**Comment by dichotommy** [comment]
@maryamsulemani97 [suggested](https://github.com/meilisearch/documentation/pull/1280#issuecomment-988847688) "MeiliSearch 101" as an alternative to "getting started" or "overview".

**Comment by guimachiavelli** [comment]
Ok, that makes more sense. 

Both "Overview" and "MeiliSearch 101" are much less ambiguous on what this section is actually about. "Overview" is a bit dry and does not exactly scream beginner-friendliness, so 101 might be better.

I also really like @bidoubiwa's suggestion of keeping the overview and the quick start separate. This allow us to keep things separate and, if necessary, tonally diverse, so the quick start can be a bit more to the point and the overview more on the friendly side.

**Comment by bidoubiwa** [comment]
@dichotommy the only thing that may be risky is that it becomes overwhelming that there are so many steps with very specific things that you should not care about at the start. 

For example: 

<img width="281" alt="Screenshot 2021-12-09 at 14 09 43" src="https://user-images.githubusercontent.com/33010418/145402542-d5d99c62-0c2b-4c7e-861e-87e2bc378bc5.png">

Where the tutorial part only cares about helping the user understand the most important features of gatsby. It is a sentiment of completion to do the whole "tutorial" part. In your case, it will be hard for the user to not stop before the end. 

If it is not the objective, having the `chapter` wording lose a bit of interest since you would have to come back later and find the `chapter` of your specific subject

**Comment by qdequele** [comment]
> * Chapter 1: Customizing relevancy

I think it might be best to see chapter 3 first and then 2 as 2 is completely optional no matter what your use-case is whereas 3 is really dependent on your use-case and if you do geo search you can't miss it.

**Comment by dichotommy** [comment]
> I think it might be best to see chapter 2 first and then chapter 1

I think I agree. It's good to start with a search-heavy chapter with a large audience first, then move to the fine-tuning for people who need more customization. Thanks for the feedback!

**Comment by dichotommy** [comment]
> the only thing that may be risky is that it becomes overwhelming that there are so many steps with very specific things that you should not care about at the start.

Yes, this is why I think we should put the topics with the broadest appeal first, as @qdequele suggested.

We should also be careful about how we name each article in the sidebar. I personally find Gatsby's Tutorial titles too dry and specific.

Dropping numbering from the series is an option. **Sidebar example**:

Getting Started
- Quick Start
- Filtering and Sorting
- Refining search results
- Adding a visual UI
- etc.
Core Concepts
- etc.

I think this is good. Are there any downsides? It's possible that the lack of numbering makes it harder to remember and return to a specific spot in the series, isn't it? And that's something I can see new users in particular doing, since they're less likely to know the exact term to search in the search bar.

It also makes the series seem less "unified", which is probably why I prefer numbering. But perhaps it's worth this to remove the sense of discouragement that comes from seeing a long numbered series.

**Comment by bidoubiwa** [comment]
What you are suggesting looks a lot to what [algolia's does](https://www.algolia.com/doc/) no particular opinion about it just mentioning it :) 

The part where we add the documents is in the quickstart ? In algolia's it is the second title

> It also makes the series seem less "unified", which is probably why I prefer numbering. But perhaps it's worth this to remove the sense of discouragement that comes from seeing a long numbered series.

This is subjective yes, personally I prefer without but its only my opinion!
