### ISSUE TITLE
v0.25: API keys: API reference

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1286]
With v0.25, the `/keys/` endpoint is being expanded to include a secondary `/keys/:key` route. 

The `/keys` endpoint can only be accessed when using the `main` key.

- [ ] Update `reference/api/keys`:
  - [ ] rewrite `GET /keys` route: lists all currently active API keys (`main` key is not included)
  - [ ] add `GET /keys/:key` route: get information on a specific API key
  - [ ] add `POST /keys` route: create a new API key
  - [ ] add `PATCH /keys/:key` route: update an API key (e.g. change its description or its expiry date)
  - [ ] add `DELETE /keys/:key` route: delete a key

**Updated 2021-11-26:** Previously this issue body stated that `POST /keys/:key` could be used to create a new key. The correct route is `POST /keys`. This has been corrected.

---

## Reference
- spec PR: https://github.com/meilisearch/specifications/pull/85

**Comment by dichotommy** [comment]
@gmourier Can I ask why `PATCH /keys/:key` is a PATCH and not a PUT? I believe this is our first PATCH method.

**Comment by gmourier** [comment]
> @gmourier Could I ask about the rationale for making `PATCH /keys/:key` a PATCH and not a PUT? I believe this is our first PATCH method so I'm sure there was some special reason.

Absolutely, @dichotommy. 

`PUT` is used to update a resource but the payload must represent the final state of the resource. This means that all fields must be filled in, even those that are not updated. `PATCH` allows updating a resource in a partial way, just by filling in the fields that need to be updated for a resource.

If we wanted to keep `PUT` and be consistent on the use of HTTP verbs, the user should always fill in the editable fields when updating an API Key, even if he just modifies a field.

I'd like to make a more complete pass to tidy up the way we use HTTP verbs on all historical API routes before version 1.0. So I took advantage of this new resource to make it more consistent with HTTP verbs and the convention of a Restful API.
