### ISSUE TITLE
Remove subsection readmes

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1293]
Despite the title, this is more of a proposal/discussion.

Every subsection of the docs website (e.g.: `/learn/core_concepts`, `/reference/features`) leads to a page that is basically just a collection of links preceded by a fairly unhelpful text. There are a few exceptions to this, namely `learn/what_is_meilisearch` and `learn/contributing`, but generally speaking these subsection roots don't add much.

@dichotommy, @maryamsulemani97: any opinions? What do you think about removing these pages so the title of a subsection leads to the first article in that folder?

**Comment by dichotommy** [comment]
Fully support this. Would add `/reference/api` as another exception—it contains some useful information, just poorly organized.

**Comment by guimachiavelli** [comment]
Ok, let's do it then. 

The next question is what to do with the "good" readmes. I suggest we:

- what_is_meilisearch/readme.md: move it to an intro article, first of its subsection
- contributing/readme.md: move it to the first (and only) article in that subsection
- reference/api: move it to an intro article

**Comment by maryamsulemani97** [comment]
Fixed in https://github.com/meilisearch/documentation/pull/1490 and https://github.com/meilisearch/documentation/pull/1499
