### ISSUE TITLE
Example request with matches on search page is wrong

### ISSUE THREAD

**Issue by kennetvu** [meilisearch/documentation#1295]
Correct me if I am wrong but, example request in https://docs.meilisearch.com/reference/features/search_parameters.html#matches is wrong. 

Correct query should be `shifu` and not `winter feast`. 

The fix should be in this file;
https://github.com/meilisearch/documentation/blob/master/.code-samples.meilisearch.yaml#L328

**Comment by kennetvu** [comment]
I will be happy to help.

**Comment by dichotommy** [comment]
Hey @kennetvu , thanks for bringing this to our attention.

In fact, it's the opposite: we updated the code sample to try to make the example more clear, but neglected to update the MarkDown document 🤦🏻‍♂️ 

The fix would be changing `shifu` to `winter feast` and updating the `_matchesInfo` object with the correct values, both in [this file](https://github.com/meilisearch/documentation/blob/master/reference/features/search_parameters.md?plain=1#L359).

Would you like to do the honors @kennetvu ?

**Comment by kennetvu** [comment]
Ah, makes sense. I updated the documentation and `_matchesInfo` object. 

PR: https://github.com/meilisearch/documentation/pull/1297
