### ISSUE TITLE
Node version must be <15

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1323]
Currently the documentation is stuck with Node versions <15 due to several unmaintained dependencies, most of which are related to VuePress.

This will be fixed by our next site move, which will most likely be to [VuePress v2](https://github.com/vuepress/vuepress-next).

**Comment by guimachiavelli** [comment]
Devil's advocate, as usual: do we have any guarantees that vuepress v2 is going to be better maintained than v1?

**Comment by dichotommy** [comment]
No guarantees in life, but it will certainly be better maintained than VuePress v1 which is [set to be deprecated in the coming months](https://github.com/vuejs/vuepress/issues/2744).

**Comment by bidoubiwa** [comment]
VUuepress had 20k stars and did a good maintaining job for all those years. They were quite honest last year when they announced the drop of support and we were aware of that as well. 

There seems to be a lot of activity going on on vuepress2, I would thrust them personally.

**Comment by guimachiavelli** [comment]
ok, that's good enough reassurance for me 👍

**Comment by ferdi05** [comment]
upvoting this because installing old versions of node on Apple M1 is super annoying
