### ISSUE TITLE
Move`reference/features/configuration` to `learn/advanced/instance-options`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1325]
This is part of our current site restructure; more specifically, our effort to remove the Feature reference and move all its pages/content to more adequate places across the docs site.

Configuration is a very generic word in the context of MeiliSearch: we can reasonably say a user is configuring an instance, an index, and even their search query. The fact we have a Configuration reference can be confusing to new users (or at least it was for me) when we do not specify what exactly they are configuring.

My suggestion is:
1. move `reference/features/configuration.md` to `learn/advanced/instance-options`
2. rename Configuration to Instance options
3. make small text edits to that page clarifying that we are talking about instance options. An example of what I mean can be seen on the first sentence of [the Configuration guide](https://docs.meilisearch.com/reference/features/configuration.html): `You can configure MeiliSearch with environment variables and command-line options.`

**Comment by dichotommy** [comment]
Hey, I'm not convinced by the word instance. It is the correct usage obvious and useful information, but is there any chance it sounds intimidating or will make people not want to click on it? This is an important page so I don't want to inadvertently bury it w/ our word choice

**Comment by dichotommy** [comment]
The other thing I'm not sure about is whether this belongs is `learn/advanced` or the API references.

On the one hand I think putting it at the top of `learn/advanced` would be a very visible place for most users.

On the other hand, we now know that there are some developers who get tunnel vision for the API references and forget about the rest of the site, and I wonder about those people not finding these important options, even though I know it has little or nothing to do with the API.

**Comment by maryamsulemani97** [comment]
Regarding placement: We could create a section called Configuration options under `reference` like [this](https://docs.zephyrproject.org/latest/reference/kconfig/index.html).

**Comment by guimachiavelli** [comment]
Hmmm…the people responsible for that site seem to be struggling with similar issues as us.

They have two links that seem they should to lead to the same page (Contents>API reference and Reference>API), but they actually lead to completely different pages.

It's also weird how the behaviour on each link under the Reference heading does something different:
1. API takes the user to a completely different URL that looks like their regular docs site but isn't it;
2. kconfig leads to a bunch of pages that are still under the regular docs site but have no direct navigation;
3. devicetree leads to a page nested within that separate api reference under Content.

**Comment by guimachiavelli** [comment]
So, to try and make a proposal out of your feedback.

1. move reference/features/configuration.md to learn/advanced
2. rename "Configuration" to one of the options listed below
3. make small text edits to that page clarifying that we are talking about instance options. An example of what I mean can be seen on the first sentence of the Configuration guide: You can configure MeiliSearch with environment variables and command-line options;
4. add links pointing to the instance configuration guide we just move around the API references. Settings, for sure, but probably a few more as well.

I propose we put the name of the section up for a vote. Use the adequate GH reaction to vote. I'll start with three options and will add any suggestions that come up in the comments:
1. Configuration 🚀 
2. Instance options 👍 
3. Server configuration 🎉
