### ISSUE TITLE
Review core concepts section

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1333]
# Review core concepts

## Abstract

Our [core concepts section](https://docs.meilisearch.com/learn/core_concepts/) is a beloved institution of the Meilisearch docs. To me, it represents Meilisearch's commitment to support beginner developers and provide multiple [types of documentation](https://diataxis.fr/) for multiple types of learner.

While these three pages may have admirable aspirations, they are in dire need of a refresh—particularly "Documents" and "Relevancy". If we do decide to prune these pages, I've laid out a few practical steps below.

However, pruning isn't the only possible solution. We may desire to re-examine core concepts as a section and determine whether it works well with our current site architecture, workflow, and goals.

## Problems

Some problems I've observed:

- We've gotten away from the idea of "concepts". These pages should not be home to reference-like content (e.g. [Dataset Format](https://docs.meilisearch.com/learn/core_concepts/documents.html#dataset-format))—at least, not without changing the name of the section. This means that currently, the goals of these pages and the type of information that would be found there are unclear.
- There is [some](https://docs.meilisearch.com/learn/core_concepts/documents.html#primary-field) [information](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#custom-rules) that is _only given on these pages_. I can't understate how troubling it is that key information (haha, primary key pun) appears only on a page marked "core concepts"; it means that what should be an optional page is mandatory and yet easily missable.

## Solutions

The obvious solution to this problem is to do an editing pass on these pages, and yet it won't help if the problem is core concepts itself. This may be a good moment to reconsider core concepts as a category, particularly in light of the new [Meilisearch 101](https://docs.meilisearch.com/learn/getting_started/filtering_and_sorting.html) guide.

Both Core Concepts and Meilisearch 101 aim to offer some kind of "high-level overview" for new users, but with some clear differences in subject + style + audience. Defining the differences between these two sections could be a worthwhile exercise.

### Proposed changes

I would propose the following changes at minimum:

**General:**
- [x] Create a separate guide for the primary key. Documents and indexes core concepts pages could still feature a short conceptual description, but technical information and code examples should be in the guide.
- [x] Reduce technical-leaning or API-specific bits such as [custom sort syntax](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#custom-rules) or [code samples changing the payload size limit](https://docs.meilisearch.com/learn/core_concepts/documents.html#upload). It is of course important for users to know they can do these things, but it should be explained verbally and with a link to the relevant explanation rather than breaking the flow of the guide. We want these to be easy to read and **conceptual!**
- [x] Reduce the number of one-sentence paragraphs describing an edge case or limitation (99% of these were not in the original guide and were added over time in response to contributor feedback, but for the most part we have better places to put them now). Add more links to [Known Limitations](https://docs.meilisearch.com/learn/advanced/known_limitations.html#maximum-number-of-query-words)—more users should know about the existence of this page!
- [ ] General cleanup: tidying, updated links to recently created pages, etc.

**Documents guide:**

- [x] Move `Dataset format` section out of `Structure` section and into `Upload`
- [x] Remove mention of "field properties": this terminology is no longer used. Could be replaced with "Displayed and searchable fields".
- [x] In `Fields` section, add mention of dot notation
- [x] Change link type from reference to inline

**Indexes guide:**

- [x] Increase emphasis on index settings (while still being conceptual). Settings are the main difference between one index and another (aside from contained documents, task stores, etc.).
  - [x] Explain w/ links to API ref and/or code samples that settings can be changed through general settings route _or_ specific settings routes.
- [x] Remove mention of "field properties": this terminology is no longer used. Could be replaced with "Displayed and searchable fields".

**Comment by dichotommy** [comment]
In documents guide: change link type from reference to inline.

**Comment by guimachiavelli** [comment]
> change link type from reference to inline.

I'm not entirely sure I understand what this means. Perhaps a good idea to give it some context?

**Comment by maryamsulemani97** [comment]
This is [an example] (http://example.com/) inline link.
This is [an example] [id] reference-style link.

For some reason the `learn/core_concepts/documents.md` file uses reference links

**Comment by maryamsulemani97** [comment]
The first iteration (#1629, #1630, #1631) makes some minor changes, moving content around, adding any missing details, and removing any "practical information" that belongs in the API reference.   

A few suggestions based on some research:

- Rename "Core concepts" to:
  - Meilisearch basics
    - Does this clash with Meilisearch 101?
  - Fundamentals (like [Twitter](https://developer.twitter.com/en/docs))
- Move Async operations guide here
  - We can move the "[Understanding tasks](/learn/advanced/asynchronous_operations.html#understanding-tasks)" content to the Task API page
- Move Primary key to "Advanced topics"?
  - Its format is very different from the other 3 guides
  - 🙅🏻‍♀️   It's the only place that explains the primary field which counts as a core concept. We could move this content back to `learn/core_concepts/documents.md` but then we'd have very little content left for a primary key "guide"
