### ISSUE TITLE
Remove `reference/features/stop_words.md`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1340]
As part of our effort to remove the `reference/features` section, I propose we delete `reference/features/stop_words.md`.

Though I think a short guide on stop words might be necessary (as well as a decision on how to write stop words: `stopwords`, `stop-words`, or `stop words`), what we currently have adds very little to what's already present in the API reference. It also lacks examples and a narrative presenting a use-case, so the first step at rewriting this guide would very likely be deleting the whole thing and starting fresh.

**Comment by dichotommy** [comment]
I agree, and a guide may not even be necessary (or at the very least is probably low priority). If there's any content on this page that isn't present in the [stop words API reference](https://docs.meilisearch.com/reference/api/stop_words.html), let's try to move and preserve it there.
