### ISSUE TITLE
Move `reference/features/web_interface` to `learn/what_is_meilisearch/`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1372]
As part of our ongoing site restructure, I propose we:

1. rename the Web interface guide to "Search preview", following #1342
2. move the guide to `learn/what_is_meilisearch/`

Pinging @meilisearch/docs-team for approval/discussion.

**Comment by dichotommy** [comment]
This is related to my comment on #1373 and to #1377 . With this and other articles such as language and telemetry that we intend to keep on the docs site, I would be more inclined to create a new section or rename an old one to make them fit rather than put/keep them in `learn/what_is_meilisearch` (which would be temporary at best).

Am I crazy, or could this page fit in `learn/getting_started`?

**Comment by maryamsulemani97** [comment]
Do we even need a separate page on this? Most of the content is covered in the new getting started. The part that isn’t is lines 5-9. We could add it to the new getting started

**Comment by guimachiavelli** [comment]
A bit like #1373, I think this article is equally out of place under "What is MeiliSearch" and "Getting started."

For me this page seems like it either belongs to a non-existent "Features" section presenting marketing-friendly features or is a itself a full-on marketing piece that took a wrong turn a while ago and ended up in the documentation. As @maryamsulemani97 said, it's very light on information that cannot be found elsewhere. I'd be ok with removing it.

**Comment by guimachiavelli** [comment]
Thinking a bit more on the subject, I think it is good to have a dedicated resource that acknowledges the existence of this little bit of functionality.

I will move it to "What is MeiliSearch". Once we have a resource center section on the new website, we should probably rewrite this so it's a bit meatier and friendlier, then move it there.

**Comment by dichotommy** [comment]
I think @maryamsulemani97 makes a good point. The article is a total stub--provides extremely minimal information besides what's already present in the quick start. Doesn't seem to justify its existence as a separate page, although you could make an argument that with documentation, it's better to be too exhaustive than too minimal.

I'm okay with moving this to What is MeiliSearch for now, but I think the next time we take a look at this page it should be to decide whether to keep it or delete it.

**Comment by dichotommy** [comment]
Sorry did not mean to close this 🙏🏻

**Comment by guimachiavelli** [comment]
As I mentioned earlier, I completely agree that the guide itself is very low on actual information, but don't you think it would be a bit weird if it's only present in the docs only as off-hand remarks in the middle of unrelated guides? 

Granted, there isn't much to say about the search preview besides "copy paste this URL in your browser and you can make simple searches on your db," but I'd argue that just by existing and being visible in the sidebar this guide could already be useful to a user who's like "ugh, I don't want to build a whole UI just to see if this search engine works with my dataset."

**Comment by guimachiavelli** [comment]
closed by #1382
