### ISSUE TITLE
Update Meilisearch spelling

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1387]
Due to new branding guidelines, `MeiliSearch` should now always be written `Meilisearch`.

There are countless instances of the old spelling across the docs, but I think we can easily and safely use a case-sensitive find-and-replace tool to update everything.

Thoughts, @meilisearch/docs-team?

**Comment by dichotommy** [comment]
Sounds good to me. @maryamsulemani97 Could you already prepare these changes in a PR, so that we can merge the moment the new website is live?
