### ISSUE TITLE
Remove hover highlight on sidebar elements that aren't links

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1431]
We often use sidebar elements without links as section dividers (see below screenshot).

![Screen Shot 2022-02-10 at 5 50 51 PM](https://user-images.githubusercontent.com/68053732/153456928-9aa005df-d4cd-4897-942e-4b4f35eb9b50.png)

When you hover over them, they highlight, which gives the impression that they are clickable (they are not).

![Screen Shot 2022-02-10 at 5 51 41 PM](https://user-images.githubusercontent.com/68053732/153456989-abef89c2-b63d-4174-97be-4bc9e92be283.png)

We likely need to override this w/ a more precise CSS selector.

**Comment by guimachiavelli** [comment]
I had a meeting with @bidoubiwa this morning and mentioned this. She's aware of it and her next PR adjusting the new brand colours will solve this issue.
