### ISSUE TITLE
Update licence date

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1438]
As notified by @curquiza, we need to bump the date on our licence file. A catch-all open date like `2019–` is not legally valid, so we do need to remember to this once a year 😅

**Comment by curquiza** [comment]
I did some research regarding the date in MIT license, looks like we will indeed to change the year every year: https://softwareengineering.stackexchange.com/questions/210472/is-renewal-of-mit-license-needed-on-github-at-the-beginning-of-each-year

> So, to summarize:

    if you made changes that year, do include the year in a comma-separated list in your copyright notice.

    if did not make copyrightable changes that year, do not include that year in your copyright notice.
