### ISSUE TITLE
Update top navbar

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1447]
Some updates to the top navbar of our site:

- [x] Rename top navbar link `Reference` -> `API Reference`
- [x] Add link to blog
- [ ] ~Add link to landing page?~

**Comment by Rutam21** [comment]
@dichotommy You can assign this to me. I will give it a try.

**Comment by dichotommy** [comment]
Hi @Rutam21 , we try not to assign issues to contributors because we don't want to block our own team from working on the problem if a contributor becomes unavailable or unresponsive.

However I can confirm that none of us are working on this currently and we would welcome a PR from you if you'd like to give it a try. The changes should be made in `.vuepress/config.js`. Just let us know if you need any additional guidance👌🏻

**Comment by Rutam21** [comment]
Hello @dichotommy , The `Meilisearch Documentation v0.25` itself links to the landing page. So let me know if a link to the landing page is still needed. I will open a PR now. Do check and suggest changes if required. Thanks.
