### ISSUE TITLE
Replace advanced topics in the sidebar

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1449]
~~Async operations, security & permissions, and updating Meilisearch are the most important "advanced topics" that users may not actively search for. The rest are search feature guides, and probably deserve their own subsection.~~

**Edited**: 2022-10-04

The "advanced topics" category in the "Learn" sidebar has become a bit of a content grab-bag, making it hard for users to find what they need by browsing. More generally, the large amount of content and multiple levels of nesting in the sidebar risk making the site feel overwhelming, which could have an adverse effect on our users.

It would be nice if guides such as "Filtering and faceted search", "Geosearch", and "Sorting" could be grouped together somehow, as all describe essential Meilisearch features—none of which are particularly advanced. It is also worth asking what is gained by making "Data backup" and "Inner workings" sub-sections of "Advanced topics" in the sidebar instead of letting them stand on their own. Odd ducks like Updating Meilisearch and Asynchronous Operations continue to be difficult to place, as they are essential to using Meilisearch long-term but could discourage completely new users.

Ultimately, we will need to think deeply about what kind of content organization makes the most sense for us. Would we prefer organization by topic (e.g. "Security and permissions", "Data backup", "Inner workings"), organization by experience level (e.g. "Getting started", "Core concepts", "Advanced topics"), or some other form of organization?

Doing some kind of direct observation/testing of first-time documentation users could  go a long way towards helping us understand the categories that users would find helpful + intuitive.

**Comment by maryamsulemani97** [comment]
Suggestion:
- Move all guides to a new section called “Guides”. All sorted in alphabetical order
- Keep Snapshots, Dumps, and Inner workings in "Advanced topics". We should rename it
- Create a new section called  “Update and migration” like [Strapi](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html) and move the update and migration guides there

![Screen Shot 2023-01-25 at 17 45 04](https://user-images.githubusercontent.com/90181761/214579406-a8fb975d-4f65-4a5e-999f-956eaf62cf4e.png)

I don't like the idea of organizing by topic as it may end up being similar to what we currently have under "Advanced topics". If we have more than one guide on one topic, as we do for "Security and permissions", we can create a separate section for it.

**Comment by maryamsulemani97** [comment]
closing for #2435
