### ISSUE TITLE
Post-restructure cleanup

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1452]
Now that we have [removed the feature references section](https://github.com/meilisearch/documentation/projects/3), there is a bit of cleanup remaining to be done. These are not urgent and can be done over the next weeks.

#1451 
#1447 
#1448 
#1449 
#1450 
#1293 : assigned to @dichotommy , implemented in #1400

**Comment by maryamsulemani97** [comment]
@dichotommy Does this need to be an issue on its own?

**Comment by dichotommy** [comment]
The post-restructure cleanup is completed, so I am closing this!
