### ISSUE TITLE
Warn users that docker on mac sucks

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/documentation#1471]
sup.

I've been using meilisearch on docker for a few days, and the recommended usage makes meilisearch suck on macOS (and probably windows too).

The issue is that all mounted volumes from osX to Linux need are on two different filesystems, so docker has to copy files back and forth, which is insanely slow.

I would be a good idea to recommend using the native application instead of people simply wanting to try meilisearch out.

**Comment by dichotommy** [comment]
Fixed by #1472 and #1476
