### ISSUE TITLE
The docker link on the quickstart documentation leads to a 404 page

### ISSUE THREAD

**Issue by en237** [meilisearch/documentation#1501]
https://docs.meilisearch.com/learn/getting_started/quick_start.html#local-installation

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/5197781/156893573-033d6643-4fe5-4b40-ac91-0e1f35119519.png">

**Comment by NaincyKumariKnoldus** [comment]
Hey @en237 Can I fix this please? Can you provide me the correct link.

**Comment by en237** [comment]
> Hey @en237 Can I fix this please? Can you provide me the correct link.

Sure, this is the right link (no upper case): https://hub.docker.com/r/getmeili/meilisearch/tags

**Comment by dichotommy** [comment]
Fixed by #1502
