### ISSUE TITLE
Settings API - Feedback

### ISSUE THREAD

**Issue by gmourier** [meilisearch/documentation#1520]
Hi @meilisearch/docs-team!

While writing the [catch-up specification for the Settings API](https://github.com/meilisearch/specifications/pull/123), I took the opportunity to write down some little details I noticed on the documentation that might interest you.

## Reindexing Documents On Settings Change

In the `filterableAttributes` API Reference, it is mentioned that updating the setting will re-index documents but this is not mentioned on other settings API Reference.

Changing any of the following index settings will cause documents to be re-indexed:

- `searchableAttributes`
- `filterableAttributes`
- `sortableAttributes`
- `distinctAttribute`
- `stopWords`

You may want to mention that for consistency.

## Missing Description

Location: https://docs.meilisearch.com/learn/configuration/settings.html#index-settings

![](https://i.imgur.com/Q7f0AHd.png)

`sortableAttributes` seems missing a proper description.

**Comment by dichotommy** [comment]
Thank you @gmourier , this is very useful feedback! 🙌🏻
