### ISSUE TITLE
Camel case in code-samples name

### ISSUE THREAD

**Issue by alallema** [meilisearch/documentation#1541]
The following code-sample names contain a mixture of Camel and Snake cases:
`getting_started_update_rankingRules_md: |-`
`getting_started_update_displayedAttributes_md: |-`
`getting_started_update_searchableAttributes_md: |-`
`getting_started_geoRadius_md: |-`
`getting_started_geoPoint_md: |-`

**Comment by dichotommy** [comment]
Hey @alallema ! Hmm, this is an interesting one 🧐 

We use `snake_case` for code sample names, but in these specific code samples we're referring to keys within the Settings object, which all use `camelCase` (e.g. `rankingRules`). I understand why we wrote it the way we did, but I also agree that it's inconsistent.

It would be better to use snake_case all the way, e.g.

`getting_started_update_ranking_rules_md: |-`
`getting_started_update_displayed_attributes_md: |-`
`getting_started_update_searchable_attributes_md: |-`
`getting_started_geo_radius_md: |-`
`getting_started_geo_point_md: |-`

To whoever works on this issue: make sure to also update the `sample-template.yaml` and tag the integrations team on your PR to avoid breaking these code samples for the SDKs.

**Comment by maryamsulemani97** [comment]
Whoever works on this, please remove
- `getting_started_add_meteors_md` from `sample-template.yaml` line 80
- `_md` from any remaining code samples
