### ISSUE TITLE
Remove table of contents from pages

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1557]
Instead of a table of contents, we can add the headings to the sidebar for the following pages:

- [Features](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html)
- [Comparison to alternatives](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html)

This will be consistent with the rest of the site

**Comment by maryamsulemani97** [comment]
@meilisearch/devrel-team, would this be okay for the [Comparison to alternatives](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html) page?

**Comment by ferdi05** [comment]
Sure, sounds good to me. thanks @maryamsulemani97
