### ISSUE TITLE
primary key can be changed if index is empty

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1574]
As discussed in this [slack message](https://meilisearch.slack.com/archives/C01K0CZKASZ/p1649061495862959) (private link) and this [PR comment](https://github.com/meilisearch/specifications/pull/132/files#r836682649), it is now possible to change the primary key of an empty index using the [update index endpoint](https://docs.meilisearch.com/reference/api/indexes.html#update-an-index).

Before, you could only do this if the index had never possessed a primary key.

I'm not sure which pages are affected by this change, but certainly the update index endpoint (linked above) could be clarified, and possibly also [the primary key guide](https://github.com/meilisearch/documentation/pull/1544).

**Comment by curquiza** [comment]
FYI there is the fresh new spec defining the behavior here: https://github.com/meilisearch/specifications/blob/develop/text/0132-indexes-api.md#324-put---indexesindex_uid

@gmourier FYI
