### ISSUE TITLE
Change `document id` to `document ID`

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1591]
`ID` might not be grammatically correct in this situation, but it is more readable and easier to transform into plural/title-case.

Note for later: `reference/api/documents.md` line 235 `id's` should be `IDs`

**Comment by maryamsulemani97** [comment]
We use `id` in the [primary key guide](https://www.meilisearch.com/docs/learn/core_concepts/primary_key#document-id).

**Comment by maryamsulemani97** [comment]
fixed in https://github.com/meilisearch/documentation/pull/2421
