### ISSUE TITLE
Adding launch options with docker

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1600]
We don't have any code sample showing how to add launch options when using docker. Haven't received any specific request for it, but could still be helpful to document

example:

```
docker run -it --rm \
    -p 7700:7700 \
    -v $(pwd)/data.ms:/data.ms \
    getmeili/meilisearch:latest
    meilisearch --master-key helloiamthemasterkey
```

**Comment by maryamsulemani97** [comment]
Explained in the [Docker guide](https://docs.meilisearch.com/learn/cookbooks/docker.html#passing-instance-options-with-environment-variables) added in #1816
