### ISSUE TITLE
Incorrect information regarding instant-meilisearch

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#1603]
In [Step 5 of the quick start guide](https://docs.meilisearch.com/learn/getting_started/quick_start.html#step-5-front-end-integration), instant-meilisearch is described as "a developer tool that generates all the components needed to start searching.". That's not true, it's [instantSearch](https://github.com/algolia/instantsearch.js) powered by Algolia that generates the tools, instant-meilisearch only connects those tools with Meilisearch (if I am not wrong)

**Comment by curquiza** [comment]
Validated by @curquiza and @bidoubiwa (she's next to me 😇 right now)

"Algolia that generates the tools" -> I would say that generates the components, to be more accurate.

Feel free to ask us for a review on the future PR if needed :)
