### ISSUE TITLE
Format for data types

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1613]
We currently use [`string`](https://docs.meilisearch.com/reference/api/search.html#response) and [string](https://docs.meilisearch.com/reference/api/settings.html#response-body).  We need to choose one and update accordingly

**Comment by vaish567** [comment]
Hello, @maryamsulemani97 would you please elaborate more what changes need to make?

**Comment by maryamsulemani97** [comment]
Hi @vaish567,

Use one format for writing data types. We currently write it with backticks (`string`) and without backticks (string)

**Comment by maryamsulemani97** [comment]
fixed in the API reference PRs
