### ISSUE TITLE
Documentation is not in line with 0.27+

### ISSUE THREAD

**Issue by juchom** [meilisearch/documentation#1639]
The default paths and mount point are for pre 0.27 version.

`data.ms` is now `meili_data`
`dumps` is now `meili_data/dumps`

The default command for docker is for pre 0.27 also

`./meilisearch` is now `/bin/meilisearch`

If I'll see more, I'll update this issue.

**Comment by maryamsulemani97** [comment]
Hi @juchom, 👋

Thank you for this issue. Could you please share more information, like what pages need to be updated, etc.? 

Thank you!

**Comment by juchom** [comment]
You should look at this pages (based on my docker usages)
https://docs.meilisearch.com/learn/configuration/instance_options.html#database-path (Mount point is now meili_data)

https://docs.meilisearch.com/learn/configuration/instance_options.html#dumps-destination (dumps dir is now meili_data/dumps)

https://docs.meilisearch.com/learn/configuration/instance_options.html#dumps-destination (still shows data.ms supposed to be meili_data ?)

https://docs.meilisearch.com/learn/configuration/instance_options.html#dumps-destination (there are some data.ms)

**Comment by juchom** [comment]
Also another error here not linked to 0.27

https://docs.meilisearch.com/learn/core_concepts/relevancy.html#ranking-rules

> For example, if someone were to search batman dark knight, then the words rule would rank documents containing all three terms first, documents containing only batman and dark second, and documents containing only batman third.

In the note `batman` appears twice one should be `knight`

**Comment by maryamsulemani97** [comment]
Thanks @juchom! We'll update the documentation asap!

**Comment by curquiza** [comment]
Hello @juchom thanks for your report.
I've commented on the PR that @maryamsulemani97 opened to close this issue -> https://github.com/meilisearch/documentation/pull/1652
I commented because I'm not sure the changes are accurate and should be done. If you have the time to take a look at my comments, it would be awesome 😄

**Comment by maryamsulemani97** [comment]
closing this for https://github.com/meilisearch/documentation/issues/1609
