### ISSUE TITLE
Make documentation compatible with node 18

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#1656]
Once this PR https://github.com/meilisearch/documentation/pull/1653 is merged the documentation will be compatible with node 16. 

Node 16 is the [active version of node.js](https://nodejs.org/en/about/releases/) in a few months (2022-10-25) node 18 will become the new current version and node 16 will enter maintenance mode.

One of the reason why we cannot guarantee the compatibility with node 18 lies in this dependency we are using: [@bidoubiwa/vuepress-plugin-element-tabs](@bidoubiwa/vuepress-plugin-element-tabs). Which is a fork of the previous [vuepress-plugin-element-tabs](https://www.npmjs.com/package/vuepress-plugin-element-tabs) that was not compatible with node 16.

There might be other reasons to this incompatibility though.

**Comment by maryamsulemani97** [comment]
closing for #1908
