### ISSUE TITLE
Make netlify use node 16

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#1657]
**Context**
Node 14 is now in maintenance. The two current active supported versions are node 16 and node 18.
See [issue here](https://github.com/meilisearch/integration-guides/issues/196) for more explanation.

** Issue **
The documentation is still built in node 14 and should be updated to node 16 for the following reasons: 
- For security reasons
- To stay up to date with your own local node environment (which should be updated to a higher version) 
- To be compatible with the dependencies that might update to versions using features that are not in node 14.

I assume because the CI builts the documentation in node 14 that netlify also builds it in node 14.

I would suggest that Netlify builds the documentation using `node 16` and not node 14 anymore.

**Comment by dichotommy** [comment]
@maryamsulemani97 Could you check whether there are any Netlify settings that determine which Node version is used to build the site? I think it probably just uses our `package.json`, but I would like to be sure.

**Comment by maryamsulemani97** [comment]
I didn't see anything there. Checked with @bidoubiwa and we just need to make the changes in `package.json` and the workflow files

**Comment by bidoubiwa** [comment]
Hey! There is one for netlify :) [Here is the way to update it](https://www.elian.codes/blog/21-12-03-set-your-node-version-in-netlify/)

**Comment by maryamsulemani97** [comment]
Should I make this change after merging #1907?

**Comment by bidoubiwa** [comment]
Before!

**Comment by maryamsulemani97** [comment]
Set `NODE_VERSION` to 16 on Netlify
