### ISSUE TITLE
PUT instead of POST for stop-words endpoint

### ISSUE THREAD

**Issue by phanirithvij** [meilisearch/documentation#1680]
https://docs.meilisearch.com/reference/api/stop_words.html#update-stop-words

I'm on the latest commit (main)
```
Database path:          "./data.ms"
Server listening on:    "http://127.0.0.1:7700"
Environment:            "development"
Commit SHA:             "b83455f345cc42d0fac579daebb25e4783945344"
Commit date:            "2022-06-02T15:01:43Z"
Package version:        "0.27.1"
```
Here POST is giving 405 Method Not Allowed
```
[2022-06-03T10:55:41Z INFO  actix_web::middleware::logger] 127.0.0.1 "POST /indexes/movies/settings/stop-words HTTP/1.1" 405 0 "-" "curl/7.79.1" 0.000076
```
but PUT succeeds, so I think the documentation needs to be updated?
```
[2022-06-03T10:56:56Z INFO  actix_web::middleware::logger] 127.0.0.1 "PUT /indexes/movies/settings/stop-words HTTP/1.1" 202 121 "-" "curl/7.79.1" 0.309257
```
```sh
curl \
  -X PUT 'http://localhost:7700/indexes/movies/settings/stop-words' \
  -H 'Content-Type: application/json' \
  --data-binary @en.stopwords.json
```

**Comment by curquiza** [comment]
Hello @phanirithvij 
Following this comment: https://github.com/meilisearch/meilisearch/issues/2458#issuecomment-1147112904

These changes are planned for v0.28.0 and the v0.28.0 has not been released yet. We do not recommend using Meilisearch on `main`. You can use
- the `stable` tag
- the specific version tag, ex: `v0.25.1`
- the release assets (binaries)
- the docker image.
More information [here](https://docs.meilisearch.com/learn/getting_started/quick_start.html#local-installation) in the `Source` tab.
