### ISSUE TITLE
v0.28: Smart cropping

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1687]
Currently, when using `attributesToCrop`, Meilisearch will start cropping at the first occurrence of any search term. If a user searches for `'white car'`, cropping of `'the woman in the white shirt drove a white car'` will be centred on the first `'white'`, even though the second occurrence includes both terms.

With v0.28, a new cropping algorithm will instead centre cropping so it includes the highest possible number of search terms. We are calling this "smart cropping."

## References
PR: https://github.com/meilisearch/milli/pull/483
Issue on core: https://github.com/meilisearch/meilisearch/issues/2299
SME: @ManyTheFish

**Comment by ManyTheFish** [comment]
Hey @guimachiavelli, about the "smart cropping" names, it's not an official name chosen by the product team.
You can freely change it for something else that would better fit the documentation.

**Comment by guimachiavelli** [comment]
Thanks for the clarification, @ManyTheFish ☺️

**Comment by guimachiavelli** [comment]
Brilliant, thanks!
