### ISSUE TITLE
v0.28: `X-Meilisearch-Client`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1691]
v0.28 adds a new HTTP header, `X-Meilisearch-Client`. Its main goal seems to be helping us properly collect user agent data identifying which SDK or official tool is accessing an instance.

At a first look, this does not seem to impact the docs. Whoever's assigned the issue should confirm this with the SME.

## References
Issue on core: https://github.com/meilisearch/meilisearch/issues/2367
Spec: https://github.com/meilisearch/specifications/pull/150/files
SME: @gmourier

**Comment by gmourier** [comment]
Hi @guimachiavelli! I can't edit the title, the right header is `X-Meilisearch-Client` 😇

**Comment by maryamsulemani97** [comment]
Confirmed with @gmourier, this doesn't impact the docs
