### ISSUE TITLE
v0.28: API key updates

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1699]
v0.28 introduces many changes to the generation and management of API keys.

## New field: `name`
`name` is a field accepting a short description of a key for easy reference. This is in addition to the `description` field, which should be used for longer and more detailed information on a key.

## New field: `uid`
This field is optional; it can be specified when the user must generate deterministic keys.

## `/keys` route
Resources returned by the `/keys` endpoint will be paginated. This means two new parameters for the `/keys` endpoint: `limit` and `offset`. Responses will also include three new fields: `limit`, `offset`, and `total`. By default, the new `limit` parameter is `20`, meaning pagination is only likely to be relevant in instances with >20 API keys

`PATCH` endpoint only allows updates to `name` and `description` fields.

When using the `GET` endpoint to get a specific key, either the `uid` or the full key value can be used.

## Tenant tokens
`apiKeyPrefix` renamed to `apiKeyUid`.

## New actions
Supported permissions for an API key now include: `keys.get`, `keys.create`, `keys.update`, and `keys.delete`.

## References
Spec: 
  - general: https://github.com/meilisearch/specifications/pull/148
  - pagination: https://github.com/meilisearch/specifications/pull/138
Issues on core: 
  - general: https://github.com/meilisearch/meilisearch/issues/2369
  - pagination: https://github.com/meilisearch/meilisearch/issues/2442 
SME: @ManyTheFish, @gmourier

**Comment by dichotommy** [comment]
> `PATCH` endpoint only allows updates to name and description fields.

If accurate, this is a biiiig change from the current version, in which update keys method allows you to update the `actions` and `indexes` for a key. Could we have confirmation on this @gmourier @curquiza ?
