### ISSUE TITLE
v0.28: New faceting index setting

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1704]
The new `facet` search parameter (previously `facetsDistribution`) will now return a maximum of 100 facets per query by default. The main reasons for this are usability—a query returning a huge number of facets (e.g. 1000) can be difficult to handle properly—and performance—a query returning thousands of facets is likely to be much heavier than it otherwise should.

v0.28 will have a new index setting, `faceting`. `faceting` will contain a settings object with one field, `maxValuesPerFacet`, which accepts an integer and defaults to `100`.

`faceting` will be availabe in the main settings object and its own API route with `GET`, `PATCH` and `DELETE` endpoints.

### References
spec: https://github.com/meilisearch/specifications/pull/157
issue on core: https://github.com/meilisearch/meilisearch/issues/2368
SME: @Kerollmops

**Comment by dichotommy** [comment]
This will be configurable along with a new index setting: `faceting`. 

Spec: https://github.com/meilisearch/specifications/pull/157

**Comment by dichotommy** [comment]
I believe the default limit for `faceting` will be `100` as stated in the spec, not `1000` as stated previously in the core issue. Could someone from @meilisearch/core-team confirm please?
