### ISSUE TITLE
v0.28: Changes to Tasks API

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1706]
With v0.28, a few changes have been introduced to the Tasks API:

## Pagination
As the name states, users will get paginated results when using `GET /tasks`. This pagination will work differently from other routes (e.g. `/keys`, `/documents`) and depend on query parameters `from`, `next`, and `limit`. For more information on this decision, consult the spec or one of the indicated SMEs.

## Filtering
Users will also be able to filter tasks by `status`, `type`, or index. These filters can be concatenated (`?status=finished&indexUid=INDEX_UID`) and a user can use a comma-separated list of values (`?status=enqueued,processing`).

According to current spec, it seems only AND operations (but not OR/NOT) are supported. Might be good to confirm this before beginning.

## `/indexes`
Remove two endpoints, `GET /indexes/:indexUid/tasks` and `GET /indexes/:indexUid/tasks/:taskUid`

## `/tasks`
Create one new endpoints to replace  the ones removed from `/indexes` : `GET /tasks?indexUid=:indexUid`

## Task types
- Task types `documentPartial` and `documentAddition` are renamed `documentAdditionOrUpdate`
- Task type `clearAll` is renamed `documentDeletion`

### References
- Spec:
  - pagination: https://github.com/meilisearch/specifications/pull/115
  - filtering: https://github.com/meilisearch/specifications/pull/116
  - `taskUid` renaming: https://github.com/meilisearch/specifications/pull/144
-  Issue on core: https://github.com/meilisearch/meilisearch/issues/2377
- SME: @Kerollmops

**Comment by dichotommy** [comment]
Also, `uid` in the summarized task response is renamed `taskUid`.

**Comment by maryamsulemani97** [comment]
Add new errors:
- `invalid_task_status`
- `invalid_task_type`
