### ISSUE TITLE
Vale next steps

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1711]
https://github.com/meilisearch/documentation/pull/1646 adds basic rules to the docs. We will be updating these rules and adding new ones over time. The full list of current+possible rules can be found in [Notion](https://www.notion.so/meilisearch/Vale-84ca4f880e8f40a1b4946d494afb9291). 

The next step is to fix the following current rules:

- [x] [FirstPerson.yml](https://github.com/meilisearch/documentation/pull/1646/files#diff-1caa38c79d4a695e087c17f61e9a19d38d72ddc9371c34dd112628c54c0028e2)

  - Possible solution: 
       [Update the message](https://github.com/vultr/vultr-mdtk/blob/84e2213b281380f45c176b873cdf01cf24152623/styles/Vultr/FirstPerson.yml) to something like: `Avoid first-person pronouns such as '%s' unless writing FAQs"`
  - Figure out how to ignore this rule for certain pages like [FAQs](https://docs.meilisearch.com/faq.html), [Telemetry](https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html), etc.
- [x]  [HeadingPunctuation.yml](https://github.com/meilisearch/documentation/pull/1646/files#diff-a56955066196e52adbd9e9f7d9b163c16bc8890d55c9ebdf537917f6e3d78da1) and [Headings.yml](https://github.com/meilisearch/documentation/pull/1646/files#diff-c67024c30495a15ac4562a42cbd10e53ffc12a5c47204d83faab02ff9c9b424b)
   - Both rules don't work for headings like `1. Click this` and `1.2. Click here`. #1776  

Add new rules:
- [ ]  ~~No capitals after colons in sentences~~
  - Too many exceptions 
- [x]  Decide max sentence length (most rules use 25-30) 
    - Most of our “longer” (more than 25 words) sentences are between 27-30 words. The longest are ~42. We can start with a max sentence length of ~40 words and see how that goes. #1777  
 - [ ]  Sound less condescending. See discussion here: https://github.com/meilisearch/documentation/pull/1662

Start working on:
- [ ]  a list of [words to replace](https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Wordiness.yml) to avoid wordy sentences (e.g., replace `in order to` with `to`)
- [x] a [list](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/British.yml) of US vs British spelling so we follow US English #1775 
- [ ] ~~consider if we need any readability metrics~~
  - Not very helpful, they just give you a number and you have to figure out what to fix

**Comment by dichotommy** [comment]
Once these steps have been achieved, and we've done sufficient iteration on the rules to be sure they will not create false positives, we will move to the final step: add Vale to our checks CI.

**Comment by maryamsulemani97** [comment]
To be done:
1. We currently have **28 warnings and 36 suggestions** 
  - 4 warnings for using `indexation` instead of `indexing`
  - 2 suggestions for the Oxford comma
  - 19 suggestions for the First person rule. Most of the pages that have this suggestion will be moved to the Developer hub
  - 10 suggestions for using the semicolon. We will need to rewrite these sentences
  - 5 suggestions for the Heading rule (use sentence-style capitalization). There are some headings where we don't follow this format:
     - "Meilisearch Documentation" in `index.md`
     - "Recommended: "Previous" and "Next" buttons" in `learn/advanced/pagination.md`
  - 24 warnings for typos; most of these are intentional
  
![Screen Shot 2022-10-04 at 14 11 20](https://user-images.githubusercontent.com/90181761/193793875-127579dc-a8d1-4b2a-b813-56be4a76e438.png)

2. Update sentences to sound less condescending 
3. A list of [words to replace](https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Wordiness.yml) to avoid wordy sentences (e.g., replace in order to with to)
  - This isn't a high priority as we haven't identified such phrases yet
