### ISSUE TITLE
Broken link on Cookbook

### ISSUE THREAD

**Issue by alallema** [meilisearch/documentation#1729]
The link on this [paragraph](https://docs.meilisearch.com/learn/cookbooks/running_production.html#step-3-secure-and-finish-your-setup-using-a-reverse-proxy-domain-name-and-https) doesn't work. 
It could be replaced by this [one](https://certbot.eff.org/instructions?ws=nginx&os=debianbuster)

**Comment by maryamsulemani97** [comment]
@alallema, the link works for me 😕
