### ISSUE TITLE
Styling: Highlighting query terms when going to a search result page

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/documentation#1741]
_Sorry for the rather unclear title of this issue._

When searching for something on the documentation website, I find it difficult to find your query terms once you've clicked a result page.

For instance if I search for `record`:
<img width="529" alt="Capture d’écran 2022-06-16 à 14 01 54" src="https://user-images.githubusercontent.com/2602288/174080975-261c2764-6ae1-4a6e-9f4d-639c6b6965bd.png">

Then if I go to the `Quick Start` page, it's not super easy to spot where it's written `record` because it's not highlighted:

<img width="798" alt="Capture d’écran 2022-06-16 à 15 32 56" src="https://user-images.githubusercontent.com/2602288/174081568-a944d7c9-de77-4986-b231-a8744ff86266.png">

It would have been great if `records` had been highlighted.

See for instance what I would have loved: [Rust API guidelines website](https://rust-lang.github.io/api-guidelines/type-safety.html?highlight=builder#consuming-builders)

**Comment by guimachiavelli** [comment]
This issue is now the responsibility of an external team and will be monitored in their preferred platform.
