### ISSUE TITLE
GET /documents intended for admin use

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1815]
As discussed in [this Slack thread](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1660094617040919?thread_ts=1659918783.918139&cid=CP9DVS1RQ), it may be helpful to clarify in the API reference that the `GET indexes/{index_uid}/documents` endpoint is intended for admin use. For the purposes of displaying all documents on the front-end, for example when a user has arrived on the search page but has not yet entered a query, we recommend using placeholder search.

**Comment by curquiza** [comment]
@guimachiavelli I cannot access to the Slack thread anymore, do you have more contexte?

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
This issue is out-dated.
Feel free to let us know if something is missing by re-opening a new issue 😊
