### ISSUE TITLE
add markdown files as supported dataset format

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/documentation#1819]
https://docs.meilisearch.com/learn/core_concepts/documents.html#dataset-format currently lists JSON, CSV NDJSON as the supported types for Meiisearch. 
In case you have data in Markdown file and you use Gatsby you can refer to the Gatsby Meilisearch plugin (https://www.gatsbyjs.com/plugins/gatsby-plugin-meilisearch/)
By using the Gatsby Meilisearch plugin, if we have dataset in markdown format, the data can be indexed in Meilisearch. 

Note: I understand this is a very peculiar case and could potentially be added as a note.

**Comment by maryamsulemani97** [comment]
Hi @shivaylamba 
We're closing this as any plugin-specific behavior should be documented in the plugin's readme. That way, we won't have to update the docs every time there's a change.
Thanks!
