### ISSUE TITLE
Update searchable attribute warning 

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1835]
Verify if the [warning](https://docs.meilisearch.com/reference/api/settings.html#update-searchable-attributes):

>Due to an implementation bug, manually updating `searchableAttributes` will change the displayed order of document fields in the JSON response. This behavior is inconsistent and will be fixed in a future release.

still applies

**Comment by maryamsulemani97** [comment]
Still applies, verified with v.028 and v0.29rc4.

**Comment by curquiza** [comment]
FYI it wil fixed when https://github.com/meilisearch/meilisearch/issues/1495 will be solved 😄 
So far it's complicated to fix and not really problematic for the users
