### ISSUE TITLE
v0.29: Updates to auto-batching

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1838]
With v0.29, auto-batching is enabled by default.
- [x] Remove the [Experimental](https://docs.meilisearch.com/learn/experimental/overview.html) section from the docs
- [x]  Move [Auto-batching](https://docs.meilisearch.com/learn/experimental/auto-batching.html) somewhere else. Maybe Advanced topics. Does it even need its own page now?
- [x] Update the page to remove the current options:  `--debounce-duration-sec`, `--max-batch-size`, and `--max-documents-per-batch`
- [x] Remove `batchUid` from the task object as it is now an internal field
- [x] Add new instance option: `--disable-auto-batching` and environment variable: `MEILI_DISABLE_AUTO_BATCHING`
- [x] Mention auto-batching in [quick start](https://docs.meilisearch.com/learn/getting_started/quick_start.html)

## References:
- Spec: https://github.com/meilisearch/specifications/pull/162
- Issues on core:
  - https://github.com/meilisearch/meilisearch/issues/2676
  - https://github.com/meilisearch/meilisearch/issues/2582
- SME: @Kerollmops

**Comment by curquiza** [comment]
Pinging @Kerollmops who can be a better SME tham me 😇

**Comment by curquiza** [comment]
Also, we can remove the recommendation about indexing by batch here: https://docs.meilisearch.com/learn/advanced/indexing.html#improving-indexing-performance

**Comment by guimachiavelli** [comment]
Two things that might be relevant when working on this issue:

1. https://github.com/meilisearch/meilisearch/issues/2478 might be worth a quick read
2. Not sure if we should mention it (probably more of a changelog thing), but FYI launching meilisearch v0.29 with the current options will throw an error

**Comment by curquiza** [comment]
> Not sure if we should mention it (probably more of a changelog thing), but FYI launching meilisearch v0.29 with the current options will throw an error

Since this feature was in `beta` this is something not mandatory to write. My opinion is we handle this on the changelog side and on the [associated discussion](https://github.com/meilisearch/meilisearch/discussions/2070) side, but not necessarily on the docs side. However, I don't have a strong opinion, and both are correct to me. So, up to you of course 😇

**Comment by guimachiavelli** [comment]
Yeap, agreed. I'll leave the final decision to @maryamsulemani97, just wanted her to be aware of it since we did briefly discuss it during the opensource meeting.

**Comment by maryamsulemani97** [comment]
@Kerollmops 
Can you please describe a situation where disabling auto-batching might be useful? We would like to add a sentence or two on what users can gain from disabling this feature.

**Comment by Kerollmops** [comment]
@maryamsulemani97, one of the reasons I currently see where it would be helpful to disable the auto-batching system would be to:
 1. Avoid a potential bug in the auto-batching system itself.
 1. Reduce the visibility latency. If the engine indexes documents in big chunks it will take more time to be able to see the documents of the first task in a search query. If you disable the auto-batching, the whole queue will take much more time to be processed, but each individual task will be available earlier (until a certain amount of processed tasks).
