### ISSUE TITLE
Inform users to stop meilisearch service during upgrade process after dump creation.

### ISSUE THREAD

**Issue by oluademola** [meilisearch/documentation#1845]
There is a missing instruction to stop the meilisearch service in the [update to the latest Meilisearch version section](https://docs.meilisearch.com/learn/advanced/updating.html#update-to-the-latest-meilisearch-version) of the documentation. To prevent problems like [this](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1661323662206599), I believe we should inform users that they must stop the currently running service after the dump is created.

**Comment by dichotommy** [comment]
Related to #1583
