### ISSUE TITLE
Improve documentation about upgrading Meilisearch

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#1849]
Updating Meilisearch is a frustration for many users. Unfortunately, this is something the core team is not able to change in the near future; sorry for this. We will, however, improve some error messages, but we cannot do better technically for the moment.

What we (@gmourier and I) suggest is to also improve the current dump documentation, I mean how to use it
- Create a dedicated guide to update dumps with DO/AWS/GCP. Indeed, often users deploy Meilisearch using `systemctl` and do not launch Meilisearch as we do it locally on our machine. I did it multiple times, I confirm it's not easy to do at all and requires a big focus. Having a dedicated guide would reduce the needed focus and would smooth the process, even internally!
- Highlight the [migration script](https://github.com/meilisearch/meilisearch-migration) managed by the integration team, see the [slack link](https://meilisearch.slack.com/archives/C010VV3SHQF/p1661335321507009) (internal only sorry)
- Also related to this issue: https://github.com/meilisearch/documentation/issues/1845
- Soon, we could redirect them to the Cloud that will provide a button to do the Meilisearch update. If people don't like doing this and sometime are already paying (for example on DO), they could move to the Cloud!

Feel free to take what you like in this issue, or nothing at all. I only report the frustration of the users, and of course if you have better, please let me know 😄

**Comment by dichotommy** [comment]
Related to #1583

**Comment by curquiza** [comment]
You rock team! 🚀
