### ISSUE TITLE
Known limitation: maximum number of requests handled

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#1870]
I'm here to share a known limitation of Meilisearch, it's up to you to put it in the docs or not 😇 

Meilisearch can handle maximum 126 requests at the same time. "Handle" not "process". It means the users can send 126 requests maximum in the request queue.

More info here: https://github.com/meilisearch/meilisearch/issues/2648

Pinging also @Kerollmops who will be the best to review the PR

**Comment by guimachiavelli** [comment]
For clarification, this simply means that, if someone makes >126 e.g. API requests at the exact same time, Meilisearch will return an error, correct?

**Comment by Kerollmops** [comment]
> For clarification, this simply means that, if someone makes >126 e.g. API requests at the exact same time, Meilisearch will return an error, correct?

indeed, it should return an internal error even if we would prefer [to return a 503 I think](http://web.archive.org/web/20210813195210/https://httpstatuses.com/503).

> It is not a limit on, say, task queue size or anything else of the sort, right?

Indeed, it is unrelated.

**Comment by curquiza** [comment]
https://github.com/meilisearch/meilisearch/issues/2786 has been merged: from v0.30.0 the maximum number of readers will be 1024 and not 126 anymore

**Comment by davelarkan** [comment]
Hi @Kerollmops and @curquiza 👋
I as wondering if I could get some clarification on this one.
What exactly do we mean by "exact same time"? Is this "within the same millisecond" or is it more nuanced than that?
