### ISSUE TITLE
Meilisearch can open a lot of FDs for big datasets and throw errors

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#1874]
We noticed, following a bug report, Meilisearch currently opens a lot of FDs (file descriptors) when indexing big datasets. In this case Meilisearch will send an internal error

```json
{
    "message": "An internal error has occurred. `Too many open files`.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
}
```

In this case, it means the user has to increase the limit of FDs, using the `ulimit` command.

Again, this is for really big datasets: we found the issue when using a 2G CSV dataset. In JSON, the same dataset would have been more than 3,5G. This is indeed really huge!

We don't know the exact behavior, I mean, when the error will be triggered, that's why I'm not sure this should be in [known limitation page](https://docs.meilisearch.com/learn/advanced/known_limitations.html#known-limitations), maybe the [FAQ](https://docs.meilisearch.com/faq.html)? You're the one to define where is the best place, these are only suggestions

I ping @Kerollmops to ensure I correctly explain the problem and also, so that he can be a future reviewer of the PR.

**Comment by guimachiavelli** [comment]
Out of curiosity, why does indexing open a lot of FDs? We were talking about this issue today and realised no one in the docs team knew the precise relation between indexing and file descriptors.

**Comment by guimachiavelli** [comment]
Brilliant, thanks for the clear and thorough explanation!
