### ISSUE TITLE
Content + menu changes due to Developer Hub

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1875]
Meilisearch's new Developer Hub is in development and will take some content from the docs for its MVP.

Pinging @mdubus who is developing the site, and @meilisearch/docs-team who are affected.

### Affected documentation pages

Here are the pages that will be affected along with what will happen to their content:

**What is Meilisearch** section: deleted
- `comparison_to_alternatives.md` -> Dev Hub
- `contact.md` -> Dev Hub OR landing page
- `features.md` -> Dev Hub OR deleted
  - Note that this page is currently out of date. Will need to be updated if moved to the Dev Hub.
- `language.md` -> incorporated into FAQ
  - Add a sentence or two to `overview.md` about the languages Meilisearch supports, so that this information is still present on the docs and shows up on search
- `overview.md` -> Getting Started
- `philosophy.md` -> absorbed into `learn/what_is_meilisearch/overview.md`
- `sdks.md` -> Getting Started
- `search_preview.md` -> Getting Started
- `telemetry.md` -> Advanced Topics

**Cookbooks** section: deleted
- `aws.md` -> Dev Hub
- `azure.md` -> Dev Hub
- `digitalocean_droplet.md` -> Dev Hub
- `gcp.md` -> Dev Hub
- `http2_ssl.md` -> Dev Hub
- `koyeb.md` -> Dev Hub
- `postman_collection.md` -> Dev Hub
- `qovery.md` -> Dev Hub
- `railway.md` -> Dev Hub
- `running_production.md` -> Dev Hub
- `search_bar_for_docs.md` -> Dev Hub

**FAQs** page: moved to Dev Hub

### The docs after these changes

For visualization purposes:

**Main documentation menu**

- Learn
- Reference
- Integrations
- More Meilisearch

**Learn section**

- Getting Started
  - What is Meilisearch (previously What is Meilisearch -> Overview)
  - Quick start
  - Meilisearch 101
  - Official SDKs / libraries (previously inside What is Meilisearch)
  - Search preview (previously inside What is Meilisearch)
- Core concepts
- Configuration
- Security and permissions
- Advanced topics
  - Telemetry (previously inside What is Meilisearch)
- Experimental
- Contributing

**Comment by guimachiavelli** [comment]
I'm not sure about the larger plans here, but I'm against putting "Languages" inside an FAQ (no matter if in the docs our in the dev hub). 

We're taking content that is specific and easy to find ("I want to know how Meilisearch works with languages, where should I go? Oh, there's a 'Languages' page, probably there") and putting it into what is essentially the most generic and least specific page we have in the whole website ("Ok, I have looked through the menu a few times, they don't have a good place for language info, guess I'll use the search bar").

IMHO, we should never move stuff that falls under a clear category into a good ol' bag of assorted questions. I like being edgy and strict, so I'd even go as far as saying we should never move content into the FAQ, but that's a different discussion.

**Comment by guimachiavelli** [comment]
Actually, looking at the languages page right now, I think all the questions could be easily restructured into sections with proper titles and etc.

**Comment by dichotommy** [comment]
That's a good point @guimachiavelli . We should consider our reasoning for moving content to the FAQ to avoid treating it as a "junk drawer".

About the Languages page—from my perspective, there are only two pieces of critical information on this page:

1. Meilisearch should work for any language _in theory,_ but only has optimized processes for one language group (whitespace) and three specific languages (Chinese, Japanese, Hebrew)
2. The Meilisearch team will not develop support for additional languages ourselves—it needs to come from the community

I am sure that users will be curious to know all of this. On the other hand, if we present that information efficiently then it will make for a very short page. For this reason, it might be better to mention these two things in another section of an existing page, particularly if the Language page would throw off existing categories.

It's worth noting as well that **the first version of the Developer Hub will not have a search bar**. Because of this, it may make more sense to keep the FAQ in the documentation for the first iteration, since at least there it would be searchable.

**Comment by shivaylamba** [comment]
I think the Algolia guide will also be shifted to the Developer Hub if I am not mistaken cc @ferdi05

**Comment by ferdi05** [comment]
Indeed @shivaylamba , that will be the case eventually. I don't know yet if this will come with the first version of the Developer Hub, we'll figure this out later

**Comment by guimachiavelli** [comment]
@Strift, this is a bit of an old discussion and much of it might no longer be relevant, but perhaps it might help with the dev hub stuff you're working on?

**Comment by curquiza** [comment]
@guimachiavelli could we close it? I guess the devhub discussions and progressions will be be handled here, but I might be wrong

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
Indeed, this issue is about devhub and we can close it here

**Comment by shivaylamba** [comment]
Hi when is the devhub being launched? @curquiza

**Comment by curquiza** [comment]
@shivaylamba we would like to release something in the first part of next year

**Comment by shivaylamba** [comment]
Alright thank you

**Comment by shivaylamba** [comment]
Looking forward to it!
