### ISSUE TITLE
filter documentation needs correction

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#19]
[See github question](https://github.com/meilisearch/MeiliDB/issues/327)

**Comment by tpayet** [comment]
We should update the example and precise that every parameters should be url_encoded. 
https://docs.meilisearch.com/advanced_guides/search_parameters.html#filters

Maybe we should add a description of Filtering in the Advanced Guides too?

**Comment by tpayet** [comment]
Here is the new link: https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#filters

We should also precise the fact that MeiliSearch handle only one filter
