### ISSUE TITLE
Review filters guide

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1902]
This guide was written about a year ago and is starting to show its age. We should review it completely and possibly rewrite a few sections.

## Filter expressions and operators
One major pain point is the list of filter operators, which no longer comfortably accommodates the growing number of operators (started with 3, now 6, will probably be further expanded soon). Additionally, the complexity of these operators has grown significantly and fitting everything (explanation, edge cases, comprehensive examples) in a single list item has become awkward.

#### `NOT` and `EXISTS`
`EXISTS` can be negated both as `attribute NOT EXISTS` and `NOT attribute EXISTS`.

- Slack discussion on interaction between `NOT` and `EXISTS`: https://meilisearch.slack.com/archives/C02DGTH89NE/p1664207880764789 (private link)
- PR discussion on `NOT` and `EXISTS`: https://github.com/meilisearch/documentation/pull/1869/files#r974129044

#### `IN` and `OR`
At the moment, `IN` works a bit like syntactic sugar for multiple `OR` statements. The implementation is actually different, however, and devs do not offer any assurances the behaviour of both operators will always match.

- PR discussion on the relationship between `IN` and `OR`: https://github.com/meilisearch/documentation/pull/1869/files#r974130580

**Comment by maryamsulemani97** [comment]
Related: #860

**Comment by guimachiavelli** [comment]
Another related issue: #1850
