### ISSUE TITLE
Review "instance"/"instance options" terminology

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1904]
@dichotommy has pointed out "instance options" can be a rather opaque term. This is connected to the fact that "instance" itself is far from clear to new users.

I think there are two things to discuss here:

1. How and when should we use "instance"? It is a handy and useful term, so I wouldn't want to drop it completely, but it seems useful to have usage guidelines;
2. How can we refer to what we currently call "instance options"? @dichotommy previously suggested "global arguments". I'm afraid global can have some negative connotations, but would be interested in the core team's thoughts on this (pinging @curquiza)
    - Should we drop "instance options" completely? Or should we use it in conjunction with other term(s)?

**Comment by curquiza** [comment]
To be honest, I don't know what is common.
I personally use "flag" or "options" to talk about `--XXX` options, and for me it's indeed "Meilisearch flag/options", not "instance"

I also ping @Kerollmops who maybe have a different opinion than me.

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
Not something we want to do: we don't have time to make a decision about this, what we should do and why? Is it valuable for users?
Feel free to let us know if something is missing by re-opening a new issue 😊
