### ISSUE TITLE
Update docs-scraper config

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1911]
Currently, the search bar doesn't show text in backticks in search results unless it's a heading. We need to add `.theme-default-content td"` to the config file to fix that. 

See https://github.com/meilisearch/docs-searchbar.js/issues/641 for more details

**Comment by dichotommy** [comment]
The `td` element stands for table data. Adding `.theme-default-content td` to the config should allow the scraper to access the content of tables. However FWIW, if there is truly a problem with backticks, then I don't think this would affect that. Maybe the backticks weren't actually the problem? 🤔

**Comment by maryamsulemani97** [comment]
The field names I mentioned in the [issue](https://github.com/meilisearch/docs-searchbar.js/issues/641) were only used in tables or JSON responses. I can try searching for field names that aren't just used in tables, e.g., `filterableAttributes,` and see what we get.
