### ISSUE TITLE
New tutorial on how to deploy Meilisearch into Azure Container Apps

### ISSUE THREAD

**Issue by tjoudeh** [meilisearch/documentation#1931]
I've written a detailed tutorial on how to [Deploy MeiliSearch into Azure Container Apps ](https://bitoftech.net/2022/10/09/deploy-meilisearch-into-azure-container-apps/)(the Newest Serverless offering by Azure) with a companion [GitHub repository](https://github.com/tjoudeh/Container-Apps-Meilisearch) so end-user can have an on-click deployment button "Deploy to Azure" button.

With this available you should have 2 options to deploy Miliesearch, the traditional way using [Azure App Service,](https://docs.meilisearch.com/learn/cookbooks/azure.html) and now the moment Azure Container Apps.

Not sure how you would like to integrate this within your documentation if you see it useful for end users.

**Comment by maryamsulemani97** [comment]
Hi @tjoudeh, 

Thank you for the issue. Could you please open a PR with the tutorial?
