### ISSUE TITLE
v.30: update settings page for `null` values

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1961]
Some settings should throw an error when given `null`
- Update the "[Update settings](https://docs.meilisearch.com/reference/api/settings.html#update-settings)" section of the Settings API
- Update specific settings' "update" section

### References
- Issue on core: https://github.com/meilisearch/meilisearch/issues/2929
- Spec: https://github.com/meilisearch/specifications/blob/main/text/0117-typo-tolerance-setting-api.md#32222-errors
- SME:

**Comment by guimachiavelli** [comment]
FYI, just noticed there's some discussion on this which I think might significantly change what we need to update:

https://github.com/meilisearch/meilisearch/issues/2929#issuecomment-1307478594

No actual decision yet, just something to keep an eye on before merging, I guess.

**Comment by curquiza** [comment]
Confirmation, nothing to change on the code part -> https://github.com/meilisearch/meilisearch/issues/2929#issuecomment-1308497861

**Comment by maryamsulemani97** [comment]
Closing since we have nothing to update on the docs
