### ISSUE TITLE
v.30: Pass config file to Meilisearch

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1962]
Users can now send Meilisearch a configuration file instead of command line options at launch

- Update the "[Customization](https://docs.meilisearch.com/learn/getting_started/quick_start.html#customization)" section of the quick start
- Add new section to the [Configuration](https://docs.meilisearch.com/learn/configuration/instance_options.html) guide

### References
- Issue on core: https://github.com/meilisearch/meilisearch/issues/2558, https://github.com/meilisearch/meilisearch/issues/2800, https://github.com/meilisearch/meilisearch/issues/2801
- Spec: https://github.com/meilisearch/specifications/pull/185
- SME: @curquiza

**Comment by maryamsulemani97** [comment]
Hi @curquiza 👋
Do you have any examples of when a user might prefer to use the config file over instance options or the other way around?

Thanks!

**Comment by curquiza** [comment]
Hum, to be honest, I'm not sure I really know the need. As a user, I would say it's sometimes more convenient to have everything in a file, but I cannot guarantee the usage of everyone.
@gmourier will know better than me since it's something he wanted to be present in v1 to be more production ready.

**Comment by gmourier** [comment]
@maryamsulemani97 A config file can be shared and versioned; it's also more practicable to change a set of options at once instead of defining every env var/option one by one with the launch command.
