### ISSUE TITLE
Wrong anchor links to sections

### ISSUE THREAD

**Issue by adripo** [meilisearch/documentation#1978]
The anchor links of sections containing `_` are converted to `-`. The actual anchor links differ from the links that are referenced in application errors

Actual:
https://docs.meilisearch.com/errors#missing-payload
Expected ([used in errors](https://github.com/search?q=org%3Ameilisearch+%22https%3A%2F%2Fdocs.meilisearch.com%2Ferrors%23missing_payload%22&type=code)):
https://docs.meilisearch.com/errors#missing_payload

**Comment by dichotommy** [comment]
Hey @adripo , many thanks for the error report. We were unaware of this until you mentioned it! 

An issue has been opened [in the main engine repo](https://github.com/meilisearch/meilisearch/issues/3097) so I am closing this one. Thanks again! 💪🏻 🚀 🤝 🙏🏻
