### ISSUE TITLE
v0.30: Update Meilisearch version in GCP how-to

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2004]
We need to bump the recommended Meilisearch version in the GCP how-to. If I recall correctly, we need to deploy the GCP image manually.

@alallema, you're the one in charge of GCP, right? Can I assign this issue to you so you can update the docs once it's done?

**Comment by alallema** [comment]
@guimachiavelli, yes of course!

**Comment by maryamsulemani97** [comment]
closed in #2054
