### ISSUE TITLE
Mention primary key in quick start

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2005]
We need to mention the primary key in the ["Add documents"](https://docs.meilisearch.com/learn/getting_started/quick_start.html#add-documents) step. Otherwise, users may assume it's auto-generated.

**Comment by vasucp1207** [comment]
@maryamsulemani97, Can I work on this issue?

**Comment by maryamsulemani97** [comment]
Hi @vasucp1207!
Sure, go ahead! But please try to keep it short, 2-3 sentences max. We want to keep the quick start as "quick" as possible.

Thanks!

**Comment by vasucp1207** [comment]
Hey @maryamsulemani97, are you talking about adding the primary key here,

<img width="854" alt="Screenshot 2022-11-21 at 11 01 37 PM" src="https://user-images.githubusercontent.com/85363195/203122261-7e96c22e-d450-4612-ae65-99b8e51ac971.png">

**Comment by maryamsulemani97** [comment]
Hi @vasucp1207, 
We want to add a few sentences on it somewhere here:  

![Screen Shot 2022-11-22 at 11 35 44](https://user-images.githubusercontent.com/90181761/203253220-936b5dd2-494a-4f82-b9b2-016f4b478d28.png)

And then update the code sample accordingly. 

You can read more about the primary key [here](https://docs.meilisearch.com/learn/core_concepts/primary_key.html)
