### ISSUE TITLE
v0.30: rename `matchedDocuments` to `providedIds`

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2006]
For `documentDeletion`: rename `matchedDocuments` to `providedIds`

## Reference
Issue on core: https://github.com/meilisearch/meilisearch/issues/3078
Spec: https://github.com/meilisearch/specifications/pull/188
SME: @Kerollmops

**Comment by dichotommy** [comment]
`taskCancelation` has a similar field called `matchedTasks`. Are we certain that this field will not be renamed `providedIds` or similar? @Kerollmops

**Comment by Kerollmops** [comment]
Hey @dichotommy,

The difference between `taskCancelation` and the `documentDeletion` tasks is that the former is able to compute the number of tasks that match in a synchronous way when the later must wait to be processed before knowing the number of documents it can delete.

So, the answer is: no, the `taskCancelation` and `taskDeletion` must keep their `matchedTasks` fields.
