### ISSUE TITLE
v1.0: rename dump commands

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2065]
Rename: 
- `dumps-dir` to `dump-dir`
- `--dumps-dir` to `--dump-dir`
- `MEILI_DUMPS_DIR` to `MEILI_DUMP_DIR`

## To do

Some may be missing
- [ ] Update `/learn/configuration/instance_options.md`
  - [ ] Rename headings 
- [ ] Update `learn/advanced/dumps.md`

## Reference

- Spec: https://github.com/meilisearch/specifications/pull/204
- Issue on core: https://github.com/meilisearch/meilisearch/issues/3132
- SME: @dureuill

**Comment by dureuill** [comment]
Hello @maryamsulemani97 👋 

[we also convened](https://github.com/meilisearch/product/discussions/560#discussioncomment-4284904) to rename the Dumps destination section from the online documentation to [Dump Directory](https://github.com/meilisearch/product/discussions/560#discussioncomment-4323521) for consistency with the implementation

(I'm not 100% this belongs to this issue but this appears related so I post here)

I have [this PR](https://github.com/meilisearch/meilisearch/pull/3199) open to update the link on the implementation side once the documentation is ready.
