### ISSUE TITLE
v1.0: remove two-step dump import

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2067]
Currently, users with v0.20 and below need to follow a two-step process for updating Meilisearch due to different dump versions. With v1.0, all dumps created before and up to Meilisearch v1.0 can be imported into Meilisearch v1.X.Y.

## To do

- Update `updating.md` to remove content on the two-step process
- Update `learn/advanced/dumps.md`

## References
- Spec: https://github.com/meilisearch/specifications/pull/203
- Issue on core: https://github.com/meilisearch/meilisearch/issues/2985
- SME: @dureuill

**Comment by dureuill** [comment]
Here is a [comment](https://github.com/meilisearch/meilisearch/issues/2985#issuecomment-1333840498) where I detail some "quirks" relative to importing a very old (v1) dump, to consider wrt documentation.
