### ISSUE TITLE
v1.0: Reject master keys with a size lower than 16 bytes

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2069]
- Master key must be composed of at least 16 bytes otherwise, Meilisearch will throw an error
## To do
Some may be missing
- [ ] Update `/learn/security/master_api_keys.md`
- [ ] Update `learn/configuration/instance_options.md#master-key`

## References
- Spec: https://github.com/meilisearch/specifications/pull/209
- Issue on core: https://github.com/meilisearch/meilisearch/issues/3272
- Product discussion: https://github.com/meilisearch/product/discussions/538
- SME: @dureuill

**Comment by maryamsulemani97** [comment]
@dureuill 
Could you please clarify if it's 16 characters or 16 bytes?

**Comment by dureuill** [comment]
Hello @maryamsulemani97 👋 

The implementation checks using [String::len](https://doc.rust-lang.org/std/string/struct.String.html#method.len), so it is 16 **bytes**. I will try to clarify this in the command line interface messages and in the spec.

We could enforce 16 **characters** at the price of making the implementation more complex if needed.

**Comment by dureuill** [comment]
^

pinging @gmourier on this just to make sure we're aligned with product on the byte/character distinction and which one to choose for master key length

**Comment by gmourier** [comment]
Thanks @dureuill and @maryamsulemani97! Go for 16 bytes!
