### ISSUE TITLE
v1.0: tag doc releases < v0.20 and > v0.9

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2071]
Releases of the Meilisearch documentation are currently tagged from the current version down to and including v0.20.

For v1, we would like tags for as many documentation releases as possible, to make it easier for users stuck on old versions to access relevant documentation.

For an example of why this is useful, consider a user trying to migrate a database from `v0.19` to `v1.0`. This user would follow the updating guide, which tells them to use the "get update endpoint" with a returned `updateId` to track the status of a settings update. However, without access to the `v0.19` documentation, this user has no way to know how to call that endpoint, much less how to know when the update is complete.

Will try to add a comment at a later point detailing how to find the right commit for an old release, and tag it such that it appears in the correct order in the [tags tab](https://github.com/meilisearch/documentation/tags?after=v0.21).

**Comment by maryamsulemani97** [comment]
Tags created for all versions between 9 and 20
