### ISSUE TITLE
v1.0: update telemetry table

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2078]
Update the telemetry table

Specs:
Check the specifications repository to add any new changes
- https://github.com/meilisearch/specifications/pull/204/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4
- https://github.com/meilisearch/specifications/pull/207/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4
- https://github.com/meilisearch/specifications/pull/214/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4

SME: @gmourier

**Comment by gmourier** [comment]
Hi @meilisearch/docs-team! I looked through every related PRs regarding the telemetry, and we are in sync with the spec.

Thank you, and sorry if you struggled to get the updates over time.

Feel free to add me as a reviewer for that subject if we have a single PR before merging for v1.0 and if you need a last pair of eyes. 🙇‍♂️
