### ISSUE TITLE
v1.0: improved search performance

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2086]
_Needs to be updated to clarify **if** need to do anything_

## References
- Issue on core: https://github.com/meilisearch/meilisearch/issues/3111

**Comment by curquiza** [comment]
For your information, Meilisearch improves but still has some crashes, I'm not sure we want to take the risk of removing the warning and the mentions of crashes.
Engine team still needs to make a lot of improvements on it, not everything will be ready for v1.0.0

**Comment by maryamsulemani97** [comment]
Updated the description. We might not do anything about it, but created this in case we do need to do something

**Comment by guimachiavelli** [comment]
After reading through the issue on the engine repo, none of the performance updates planned for v1.0 require us to update existing our documentation of the subject.

I'm closing this, but do reopen if the engine team makes any important last minute performance improvements.
