### ISSUE TITLE
[postman] wrong path for cancelling a task

### ISSUE THREAD

**Issue by JaySunSyn** [meilisearch/documentation#2088]
I think that the path needs to be:

```
"raw": "{{url}}/tasks/cancel"
```

https://docs.meilisearch.com/postman/meilisearch-collection.json

<img width="625" alt="image" src="https://user-images.githubusercontent.com/5872432/211170970-a2f5809b-4175-4678-a469-6729c063bb32.png">

**Comment by dichotommy** [comment]
Thanks for noticing this and creating an issue for it @JaySunSyn ! 🔥 🚀
