### ISSUE TITLE
v1.0: Create update troubleshooting guide

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2097]
With #2058 , we added a new section to the updating guide: "version-specific update instructions" (AKA "[ye olde bag of version weirdness](https://meilisearch.slack.com/archives/C010VV3SHQF/p1671119964556149)").

Currently, this section has a few bullet points: a reminder to use the old authorization header, a warning that keys may be regenerated, and a warning related to a specific error affecting `_geo`.

We could expand the "version-specific update instructions" section. However, it's within our and our users' best interests to keep the updating guide as lightweight as possible. Instead of expanding this section, I propose creating a new page specifically for troubleshooting the update section.

Here's how we should deal with the information currently present in the "version-specific update instructions":
- The reminder about the old authorization header is necessary for certain users to follow the update guide. Will be kept within the update guide ✅ 
- The key regeneration warning will probably be appreciated by users following the update guide. Will be kept within the update guide ✅ 
- The `_geo` warning is not necessary to follow the update guide, and could go in a separate troubleshooting page used by those who struggle with the update process. Will be moved to the new update troubleshooting guide 🚚 

The update troubleshooting guide should be organized by affected versions and expanded with two main types of information:
- Migration-breaking problems: breaks the dump import, making update and migration to v1 impossible
  - Example: `_geo` problem
- Codebase-breaking problems: does not affect the update process directly, but will break users' codebases post-update
  - Example: changes to setting names/schemas, changes to search parameters, etc.
  - We can't possibly document all of these (plus it would most likely end up being identical to the changelog), so if we do include them, then we must focus on the most "common" problems

The big question, which we hope to understand better once we start working on this, is how much of this information is realistic + helpful to document. The first step will be reaching out to the support and engine teams to get their impressions of any critical breaking changes or other "wrenches" jamming up the update process.

**Comment by maryamsulemani97** [comment]
- Reword the `_geo` error to explain it better so people are not afraid of data corruption 3

Other possible additions:
- From v0.25: If you are upgrading from a version prior to v0.25.0, you will need to update your code to replace the previous public and private API keys with the newly generated keys to communicate with MeiliSearch.
- From v0.25: (Not sure if this will be helpful) The update resource has been renamed to task

**Comment by maryamsulemani97** [comment]
Since we don't have a lot of content, we will not create a separate page for troubleshooting. We will add it to the "Version-specific update instructions" section of the updating guide.
