### ISSUE TITLE
Wrong config.toml link in the "running_production" cookbook

### ISSUE THREAD

**Issue by gmourier** [meilisearch/documentation#2115]
The [step 3](https://docs.meilisearch.com/learn/cookbooks/running_production.html#step-3-create-a-configuration-file) download snippet is linked to the v1.0 file version (currently in RC) which brings some naming changes compared to the current release (v0.30.5)

`wget -qO /etc/meilisearch.toml https://raw.githubusercontent.com/meilisearch/meilisearch/main/config.toml
`

e.g  `dumps_dir` is renamed to `dump_dir`

It should link to the last official release file version (v0.30.5)

Kindly reported by @arcticmedia-ryan on [discord](https://discord.com/channels/1006923006964154428/1006923007559729154/1064622220674080848) 🍪😁

**Comment by ams-ryanolson** [comment]
Thanks for the shoutout. I am sorry I could not complete this PR myself.
