### ISSUE TITLE
Update `/learn/what_is_meilisearch/features.md`

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2117]
The [Features](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html) page is outdated but has a ton of views as it is linked to the landing page.

**Comment by dichotommy** [comment]
In addition to being out of date, "placeholder search" is woefully out of place there. That's more of a functionality than a feature. It's certainly not making or breaking anyone's decision to pick up Meilisearch.

**Comment by maryamsulemani97** [comment]
Update the page to add [missing features like geosearch and multitenancy](https://github.com/meilisearch/documentation/issues/2136)
