### ISSUE TITLE
movies.json has duplicate IDs 

### ISSUE THREAD

**Issue by FrancisMurillo** [meilisearch/documentation#2127]
## Description

In reference to meilisearch/meilisearch#2909, I noticed that `movies.json` had some duplicate ids which leads to some confusion about the total number of records created. Is it possible to update the repeating IDs?

**Comment by maryamsulemani97** [comment]
Hey @FrancisMurillo! 👋 
Thank you for the issue. It would be great if you could open a PR updating `movies.json`. Please let us know if you have any questions.
