### ISSUE TITLE
Update the feature list

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/documentation#2136]
As we're moving towards v1.0, and want to emphasize now being enterprise-ready, I think we could update accordingly [the feature list](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html).
I'm thinking `geosearch` and `multitenancy` at least.

**Comment by maryamsulemani97** [comment]
Hey @ferdi05! Thanks for the issue!
I'm updating #2117 and closing this one.

**Comment by ferdi05** [comment]
thanks so much @maryamsulemani97 I'm sorry for creating extra work. 
I searched for a good place to talk about this, even saw this issue, and judged it was not a good place to talk about this..
I guess I'm still upset from loosing at Mario Kart against everyone at the office at lunch
