### ISSUE TITLE
Make quick start use authorization—improve compatibility with Cloud

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2149]
# Should we use authorization for the whole quick start?

## Problem

Right now, the code samples in the quick start assume that the user is running an unprotected Meilisearch instance without a master key defined.

However, when users create projects on Meilisearch Cloud, the instance is automatically protected with a master key. This means that when Meilisearch Cloud users try to follow the quick start without changing code samples, they will get an authorization error.

## Solution

To make the Quick Start more compatible with Meilisearch Cloud, we should:

- Require users to set a master key at launch
- Add the authorization header to all code samples in the Quick Start

### Pros & Cons

Arguably, this is a better practice anyway, since protecting an instance should be the default.

On the other hand, this may make users believe that the master key is mandatory when it's not. It also slightly increases the time to first search by requiring the user to pick a master key.

@meilisearch/product-team Is there any discussion about making the master key mandatory?

Tagging @davelarkan for visibility.

**Comment by gmourier** [comment]
Hello @dichotommy 👋

We have a discussion related to that subject https://github.com/meilisearch/product/discussions/443

It should be taken with a pinch of salt, but I also got feedback from a user saying that he had no interest in starting an unsecured Meilisearch and that he would have preferred the guide to tell him directly how to do it.

If users are using an SDK, it's much easier than sending curl requests since the Authorization Bearer is automatically at the client level so it's done only time.

**Comment by maryamsulemani97** [comment]
We added a note at the beginning of the quick start that users need the `-H Authorization: Bearer API_KEY` header if they're using Meilisearch Cloud or launched their instance with a master key in #2233

**Comment by dichotommy** [comment]
Reopening this as it is not completed at all. There is still an open question of whether we will modify the Quick start code samples to use API key authorization. Showing users from the get-go how to run Meilisearch with a master key and API keys would teach users security best-practices from the beginning _and_ improve compatibility with the Cloud—two birds with one stone, so still worth considering.

The fix we merged warning users about the authorization header is just a stopgap solution.

**Comment by maryamsulemani97** [comment]
fixed in https://github.com/meilisearch/documentation/pull/2399. All quick start code samples now use a 16 byte sample master key.
