### ISSUE TITLE
Documentation of integrating MeiliSearch with Vuepress

### ISSUE THREAD

**Issue by tarvos21** [meilisearch/documentation#215]
The doc of MeiliSearch uses Vuepress, which I also use, and I find Vuepress needs a better search solution. Any guide to integrate MeiliSearch with Vuepress? Like a plugin?

Thanks!

**Comment by Kerollmops** [comment]
Hey @tarvos21,

Their already is [an answer to that question in the MeiliSearch repositiory](https://github.com/meilisearch/MeiliSearch/issues/508). We added it [to our backlog too](https://github.com/meilisearch/backlog/issues/9)! In short we will work on that in the next weeks and @curquiza will probably write a step-by-step tutorial to show how to integrate MeiliSearch to your own VuePress based documentation website 😁

Thank you again for your interrest in MeiliSearch!

**Comment by tarvos21** [comment]
Glad to hear it, thanks!
