### ISSUE TITLE
Make config file download code samples consistent

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2158]
We give instructions on how to download the default `config.toml` file in two places:

- `/learn/configuration/instance_options.md` (L#72)
- `/learn/cookbooks/running_production.md` (L#87)

One of these examples uses `curl`, the other `wget`. We should make this consistent and use `curl` on both examples, [as discussed on a separate PR](https://github.com/meilisearch/documentation/pull/2144#issuecomment-1422389926).

**Comment by zakester** [comment]
I don't see `wget` in both `/learn/configuration/instance_options.md` and `/learn/cookbooks/running_production.md`, both of them are using `curl`:

(L#72) `instance_options.md`:
```
curl https://raw.githubusercontent.com/meilisearch/meilisearch/latest/config.toml > config.toml
```
(L#87) `/learn/cookbooks/running_production.md`:
```
curl https://raw.githubusercontent.com/meilisearch/meilisearch/latest/config.toml > /etc/meilisearch.toml
```

**Comment by curquiza** [comment]
@guimachiavelli is this still up to date? I don't see any `wget` in the code either

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
Indeed, the work has been done and no `wget` is visible. We close the issue.
Feel free to let us know if something is missing by re-opening a new issue 😊
