### ISSUE TITLE
Invalid link somewhere pointing to a 404

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/documentation#2159]
https://docs.meilisearch.com/resources/faq.html#what-are-the-recommended-requirements-for-hosting-a-meilisearch-instance

Vs

https://docs.meilisearch.com/faq.html#what-are-the-recommended-requirements-for-hosting-a-meilisearch-instance

**Comment by dichotommy** [comment]
Hm, I'm not sure how to solve this as the redirect is working properly, as you can see in the URL bar. It seems like an issue with how Vuepress refreshes the page content or something. Any ideas @Kerollmops ?

**Comment by dichotommy** [comment]
Nvm, found the link via the Reddit AMA.

**Comment by guimachiavelli** [comment]
Our "fix" was to use a direct HTTP link. A terrible solution, but it will prevent users from getting 404 during the v1 release traffic spike.

We'll continue investigating this problem in #1359.
