### ISSUE TITLE
Remove `tenant_token_guide_search_no_sdk_1` from code samples file

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2169]
The `tenant_token_guide_search_no_sdk_1 ` code sample was added for illustration purposes. We would like to remove it from the code samples files(`.vuepress/public/sample-template.yaml` and `.code-samples.meilisearch.yaml`) and embed it directly into the `learn/security/tenant_tokens.md` page to avoid issues in #2162

**Comment by guimachiavelli** [comment]
This no longer seems relevant, as #2162 is not compatible with the new site and our process dealing with code samples is bound to change radically due to internal reorg.
