### ISSUE TITLE
Review `what_is_meilisearch/overview`

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2185]
Review the `/learn/what_is_meilisearch/overview.md` page to remove any sections that will require constant maintenance, e.g. the [Features](https://docs.meilisearch.com/learn/what_is_meilisearch/overview.html#features) section. We can remove it from here as we have a [dedicated page](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html#search-as-you-type) for it.

**Comment by dichotommy** [comment]
As always with page reviews, we also want to make sure the content is up to date. If some content is out of date, it may be a sign that we should change the format to make it easier to maintain.
