### ISSUE TITLE
Update code sample name format 

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2220]
- Update `.code-samples.meilisearch.yaml` (and other relevant ones)so that all code samples use the format: `[feature/api][article][description]_[number]`
- Update `.code-samples.meilisearch.yaml` to either use `code_sample_name: |-` or `code_sample_name: |`
   - 137/158 code samples use the `code_sample_name: |-`

**Comment by dichotommy** [comment]
Could you make the title of this issue more descriptive, please?

**Comment by maryamsulemani97** [comment]
fixed in #2296 
All code samples use `code_sample_name: |-`
