### ISSUE TITLE
Auto-batching docs are incomplete

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2227]
To be discussed after v1.1 with @irevoire

**Comment by curquiza** [comment]
@guimachiavelli do you have the contexte? Same question for @irevoire

**Comment by irevoire** [comment]
I don't remember tbh.
I think I wanted to show maryam why we couldn’t really document every possible way to autobatch things (with the large ugly graph I showed you a few months ago).

**Comment by curquiza** [comment]
@guimachiavelli I let you close if you don't have more context in mind either

**Comment by guimachiavelli** [comment]
It's been some time so I'm not entirely sure. I believe the documentation states autobatching only happens for document addition and update/deletion. Whilst researching something else, Maryam then discovered, through @irevoire, that wasn't the case and other operations were also autobatched.
