### ISSUE TITLE
Add images and gifs

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2236]
Add images/gifs to the following files in the Learn section:
- [ ] `search_preview.md` 
- [ ] `what_is_meilisearch/overview.md`
- [ ] `quick_start.md`
- [ ] `search_bar_for_docs.md`
- [ ] `railway.md`
- [ ] `qovery.md`
- [ ] `postman.md`
- [ ] `gcp.md`
- [ ] `digitalocean_droplet.md`
- [ ] `azure.md`
- [ ] `aws.md`
- [ ] `filtering_and_faceted_search.md`
- [ ] Verify all GIFs works

**Comment by maryamsulemani97** [comment]
fixed in #2248

**Comment by dichotommy** [comment]
Let us not forget about updating the links to images in the mdx files...
