### ISSUE TITLE
Migration: Update search instance

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2241]
Update `docs-scraper.config.json` to have the same settings as the [current docs site](https://github.com/meilisearch/documentation/blob/main/.vuepress/docs-scraper/docs-scraper.config.json).

**Comment by guimachiavelli** [comment]
Can we update this issue description with more information? 

- What steps do we need to take to update the search instance?
- What exactly needs to be updated? Paths, actions, something else?
- Clarification of what we mean by current docs settings could also be helpful and ensure we don't miss any details

**Comment by maryamsulemani97** [comment]
For now, we just want `docs-scraper.config.json` to have the same settings as the current docs. This will be fixed when  #2299 is merged
