### ISSUE TITLE
Highlight the tasks DB limitations and advocate tasks deletion to circumvent it

### ISSUE THREAD

**Issue by gmourier** [meilisearch/documentation#2252]
Internal conversation https://meilisearch.slack.com/archives/C03T1T47TUG/p1680013364650309

With v1.0, the tasks DB maximum size went from 100GB to 10GB. This week we saw two users blocking their instances after reaching the maximum size in a few days.

We cannot push a fix by v1.1, but we will work on it for v1.2; a prototype should be available soon to check if we can solve it natively.

In the meantime, a quick solution that could help would be to highlight the limitations of the task DB and advise users to delete tasks via the deletion API regularly using a cronjob or whatsoever

cc @meilisearch/cloud-team @meilisearch/engine-team

**Comment by curquiza** [comment]
Update: v1.1.1 (coming soon) will provide a temporary fix for the task DB issue

**Comment by maryamsulemani97** [comment]
fixed in #2372
