### ISSUE TITLE
Include the allow executable permission command to the meilisearch binary in the "run meilisearch in production guide"

### ISSUE THREAD

**Issue by oluademola** [meilisearch/documentation#2256]
Hello Team. To avoid errors and issues like [this](https://github.com/meilisearch/meilisearch/issues/3556), saying that meilisearch is not executable. We should include the `chmod +x meilisearch` command in this [guide](https://docs.meilisearch.com/learn/cookbooks/running_production.html#step-1-install-meilisearch). This command should be immediately after the binary installation command in step 1. Thanks.

**Comment by maryamsulemani97** [comment]
fixed in #2354
