### ISSUE TITLE
Migration: update search_bar_for_docs

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2283]
The following images/gifs were recorded with the current docs:

- `assets/images/tuto-searchbar-for-docs/vuepress-searchbar-demo.gif`
- ~~`assets/images/tuto-searchbar-for-docs/vuepress-plugin-example.png`~~

We need to record them with the new site

To be done after #2241 as both use the search bar

**Comment by guimachiavelli** [comment]
Should we, though? At least one of these images is explicitly about the vuepress plugin, but AFAIK the new nextjs website will handle scraping differently. 

Replacing only that image might make sense, but having two images referencing different versions of the same sounds confusing.

**Comment by dichotommy** [comment]
I have renamed this issue, since both of the image assets featuring the old site were in the "search bar for docs" tutorial. We should remove references to the docs site from this tutorial as they will be outdated. Should mostly be the first three lines, but there may be others.

**Comment by maryamsulemani97** [comment]
fixed in #2328
