### ISSUE TITLE
Migration: Missing or lost functionality

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2293]
- [x] Scraper for docs search bar (how does it work? do we need to do anything?)
#2315, fixed by #2299

@dichotommy: 
> The scraper is already set up (see the config file at the root of meilisearch.com repo), and I believe there's a GitHub action set up to trigger the scraping using a Vercel webhook, but I haven't put eyes on the actual file
> We do need to https://github.com/meilisearch/documentation/issues/2241, particularly searchableAttributes.

@justkahdri:
> As @dichotommy said, it's already set. Nevertheless, my idea is to migrate it to this project and trigger it when documentation itself is updated and not depend on the rest of the site.

---

- [ ] Vale (setup seems to work initially, but doesn't actually work, proselinter might work, but who knows) 
#2291 
#2239

--- 

- [ ] markdown linting (eslint + eslint-plugin-mdx?)
#2239

@justkahdri: 
> [eslint-mdx](https://github.com/mdx-js/eslint-mdx) as @guimachiavelli mentioned is a good choice. We don't have link checking in the build process itself.

---

- [ ] bors 
#2290 

---

- [ ] dead links checker (mdx-local-link-checker?) 
#2313 
#2239

---

- [x] dependabot (do we even have any deps now?)

@dichotommy:
>No, we should not have any dependencies for the moment... but this could change if we want to implement a markdown linter etc. in this repo.

---

- [ ] [deploy github workflow](https://github.com/meilisearch/documentation/pull/2299): done, awaiting merge
#2314, fixed by #2299

---

- [x] code samples (where are they? how do we edit them?)
fixed by #2296, #2297
---

- [ ] codeowners (moot point if code samples are located elsewhere)
#2316

---

- [x] .gitignore (is it still necessary?)

@dichotommy:
> We should have a .gitignore file, even if it is empty. At the beginning, I do not think there will be any files to ignore (these are usually files generated during build etc.).

---

- [ ] static assets: linking to `raw.github.com` is only a temporary solution. We need an easy way to add new images/videos/datasets to documentation pages

**Comment by dichotommy** [comment]
> Scraper for docs search bar (how does it work? do we need to do anything?)

The scraper is already set up (see the config file at the root of `meilisearch.com` repo), and I believe there's a GitHub action set up to trigger the scraping using a Vercel webhook, but I haven't put eyes on the actual file

We do need to [update the index settings in the scraper-config file](https://github.com/meilisearch/documentation/issues/2241), particularly `searchableAttributes`.

**Comment by dichotommy** [comment]
> dependabot (do we even have any deps now?)

No, we should not have any dependencies _for the moment_... but this could change if we want to implement a markdown linter etc. in this repo.

**Comment by dichotommy** [comment]
I'm not certain, but I think bors should be relatively easy to migrate. [An issue already exists](https://github.com/meilisearch/documentation/issues/2290).

We should have a `.gitignore` file, even if it is empty. At the beginning, I do not think there will be any files to ignore (these are usually files generated during build etc.).

**Comment by dichotommy** [comment]
Of these, I think that some form of link checking and markdown linting are highest priority.

@justkahdri Is there some form of link checking involved in the build process of `meilisearch.com`? Do you know a solution we could use to verify the validity (and best practices) of our `.mdx` files?

**Comment by justkahdri** [comment]
> Of these, I think that some form of link checking and markdown linting are highest priority.
> 
> @justkahdri Is there some form of link checking involved in the build process of `meilisearch.com`? Do you know a solution we could use to verify the validity (and best practices) of our `.mdx` files?

For what I know [eslint-mdx](https://github.com/mdx-js/eslint-mdx) as @guimachiavelli mentioned is a good choice.
We don't have link checking in the build process itself. I'm not quite sure I understand in which sense you mean to have a validation. Is it for example to know if a relative url present in the content would be broken?

**Comment by guimachiavelli** [comment]
about the link checking: it is more or less what you described, @justkahdri. We currently have both a local CLI command and a GitHub action triggered on push that checks for broken internal links and anchor links.

For example, if we change a page from `/cli-options.mdx` to `/configuration-options.mdx`, our checker notifies us about links pointing to the old file. The same happens for anchor links: the checker will notify us if we change a heading from `## CLI options` to `## Configuration options`.

This is very useful and an important step in our workflow, because it's hard to otherwise be aware of all links pointing to a specific resource.

**Comment by justkahdri** [comment]
I think something similar would be doable as a github action, but keeping in mind we are working with remote files it would be difficult to acomplish.

Is not a solution, but a workaround now is checking the console on the url you want to evaluate, when a link is on sight nextjs will try to prefetch the content and if the link is broken you will see the error there.
Example on the [docs homepage](https://website-git-staging-meili.vercel.app/docs):
![Screenshot 2023-04-05 at 10 29 29](https://user-images.githubusercontent.com/48418633/230096127-3753c64f-b0ba-48cf-ab9d-69ebe364f6fe.png)

**Comment by justkahdri** [comment]
@guimachiavelli code samples work the same way the worked before. You edit the `code-samples.meilisearch.yml` in the different projects and they are all fetched and parsed inside the site, then the `<CodeSamples />` components load each sample for each language that matches its respective `id`

**Comment by guimachiavelli** [comment]
@justkahdri: thanks for the quick response. There's one missing piece here, though. All API code samples in the external projects (SDKs for Ruby, Python, etc) are based off a `curl` code sample located in the documentation repository.

Our current workflow when creating new code samples:
1. create an `id` (e.g. `new_codesample_1`)
2. add a `curl` code sample to `.code-samples.meilisearch.yaml`
3. add `id` to  `/.vuepress/public/sample-template.yaml`, (the integrations team uses this on their own workflow)

Step #2 is what is unclear to us. Should we create `.code-samples.meilisearch.yaml` in the migration repo?

**Comment by guimachiavelli** [comment]
I have created issues for everything mentioned here that hasn't been fixed yet. These issues have been linked above. They are also available in https://github.com/meilisearch/documentation/projects/7.

If you have any comments on anything mentioned here or want to continue the discussion, please refer to these issues.
