### ISSUE TITLE
Migration: Redirect `docs.meilisearch.com/*` to `meilisearch.com/docs/*`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2298]
The new documentation website will be a directory inside `meilisearch.com` instead of a subdomain. At launch, old and new sites will be follow the exact same structure—with the important difference that pages in the old website end in `.html` and pages in the new website don't.

After discussing this with @dichotommy and consulting @nicolasvienot, we will solve this using CloudFlare DNS's redirect rules and dynamic transforms.

We have four options, described in the images below:

## 1
![1](https://user-images.githubusercontent.com/1923183/230150465-8233d398-9c48-42a4-8c14-5e59f6bb9fed.png)

## 2
![2](https://user-images.githubusercontent.com/1923183/230150473-45a167fc-25f8-42c5-b3ef-01f5c682b84b.png)

## 3
![3](https://user-images.githubusercontent.com/1923183/230150477-843eec28-63ae-4205-ac78-1190f2c11e4d.png)

## 4

![4](https://user-images.githubusercontent.com/1923183/230150480-a59fbd86-c544-4481-88cd-9149ad1b7d46.png)

@nicolasvienot shared a couple of articles to help us decide the best redirect approach: https://blog.cloudflare.com/introducing-transform-rules-with-url-rewriting-at-the-edge/ and https://blog.cloudflare.com/dynamic-redirect-rules/.

**Comment by dichotommy** [comment]
I don't see the difference between options 1 vs. 3 (is there a difference between "transform" and "redirect"?)

Option 4 seems the best in terms of coverage, as option 2 would not work for the homepage or datasets that end with `.json`.

**Comment by nicolasvienot** [comment]
Update:
I think 2 Page rules should do the trick:
docs.meilisearch.com/*.html -> meilisearch.com/docs/*
docs.meilisearch.com/* -> meilisearch.com/docs/*

@dichotommy @guimachiavelli do you have more information about my questions [in my previous comment ](https://github.com/meilisearch/documentation/issues/2298#issuecomment-1498918830)?

I will also need to know what to do with the current rules (delete them, update them)

**Comment by guimachiavelli** [comment]
HI @nicolasvienot!

Apologies for the delay in replying. 


> You need someone to apply a config to do the redirect + remove the trailing .html (in which case I can be assigned to this issue if you want to)
Yes.

> This will need to be done Tuesday 18th of April (do you have more information about the time?)
I unfortunately can't give you a clear answer on this. The planned date was today (April 11th 2023) , but we still have unresolved issues and it's not at all clear the devs will be able to fix them. I believe the final call is @dichotommy's, so let's see what he says.

> You're ok with having the old documentation still up for a few hours to let some time to apply the redirect rules
Yes, absolutely.

> I will also need to know what to do with the current rules (delete them, update them)
From my (limited) understanding, we could just delete and replace them with the new ones. Do you see any possible negative side effects?

**Comment by nicolasvienot** [comment]
> I unfortunately can't give you a clear answer on this. The planned date was today (April 11th 2023), with a possible extension up to thursday (April 13th) but we still have unresolved issues and it's not at all clear the devs will be able to fix them in time. I believe the final call is @dichotommy's, so let's see what he says.

Noted 👍 

> From my (limited) understanding, we could just delete and replace them with the new ones. Do you see any possible negative side effects?

For the `Redirecting doc.meilisearch.com/* to docs.meilisearch.com/*` rule, I think we can remove it if you don't think we'll have any traffic from `doc.meilisearch.com/*`

For the `Cache level` rule, I honestly don't know why it's there, and I'm assuming we won't need it but 🤔

**Comment by nicolasvienot** [comment]
@guimachiavelli Do you want me to remove the rules that does the redirection from `meilisearch.com/docs` to `docs.meilisearch.com` so you can prepare and test `meilisearch.com/docs` without being redirected?

**Comment by dichotommy** [comment]
For the current rules:

1. Should be deleted
2. Not sure. Messaging Basement devs to get a clarification on this!
3. Should be updated so that it redirects `doc.meilisearch.com` to `meilisearch.com/docs`. Would also be great to add a new one redirecting `meilisearch.com/doc` to `meilisearch.com/docs`!

**Comment by nicolasvienot** [comment]
Update:
The strategy applied did not work with URLs with `.html` in the middle of the pathname or followed by query parameters that were redirecting to the new website but with a 404.

I had to use a Cloudflare worker as:
- [Page rules](https://developers.cloudflare.com/support/page-rules/understanding-and-configuring-cloudflare-page-rules-page-rules-tutorial/) won't do the job for what we want (either replace a .html anywhere in the URL by nothing or strip after the first .html)
- [Transform rules](https://developers.cloudflare.com/rules/transform/) and [Redirect rules](https://developers.cloudflare.com/rules/url-forwarding/) needs us to be on a Enterprise/Business plan for us to use the regex_replace function for dynamic URLS rewrites

I'm unsure about Cloudflare workers pricing, but the worker can be followed in our Cloudflare workers.

Here is the code of the worker that I applied to *docs.meilisearch.com/*
```javascript
export default {
  async fetch(request) {
    const base = "https://www.meilisearch.com/docs";
    const statusCode = 301;

    const url = new URL(request.url);
    const { pathname, search } = url;

    const newPathname = pathname.replace(/\.html$/, '')
    const destinationURL = `${base}${newPathname}${search}`;

    return Response.redirect(destinationURL, statusCode);
  }
}
```
[Based on this example 
](https://developers.cloudflare.com/workers/examples/redirect/)

There might be other options that we can check later, but for now it should work for most URLs.

**Comment by guimachiavelli** [comment]
What's the status on this? Are there any remaining tasks related with the migration redirects?

**Comment by dichotommy** [comment]
Thanks @nicolasvienot ! I think we can close this issue now. We are still interested in a redirect from `meilisearch.com/doc`, provided it's not too much trouble.

(The typo-tolerant search engine should have a typo-tolerant website, right? 😂 )
