### ISSUE TITLE
Post-migration: update broken links and outdated info in external READMEs

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2300]
There will probably be a lot of broken links and outdated information in external READMEs (engine, docs-scraper, vuepress integration etc.) that we should help fix post-launch.

(To be clear, I'm speaking mainly about links to our GitHub repo main branch. Links to our production site will be handled by redirects)

**Comment by guimachiavelli** [comment]
Tasks identified:

- [x] Update `meilisearch/meilisearch` README
- [x] Update `meilisearch/vuepress-plugin-meilisearch` README
- [x] Update `meilisearch/docs-scraper` README
- [x] Notify SDK maintainers so they can update their READMEs
- [x] Notify engine team so they can update links in messages generated by the `meilisearch` binary

**Comment by guimachiavelli** [comment]
The tasks relevant to this repo have been completed.

There are a few problems with the `meilisearch/docs-scraper` PR, but it's out of scope for this issue and  will be handled directly on the scraper repo.
