### ISSUE TITLE
Migration: Basic dependabot configuration

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2317]
Though we currently have no dependencies in the new website, this will change soon as we add linters, checkers, and so on.

We need to copy the file in the old site's `.github/dependabot.yml`, move it to the same folder in the new site, and see if there are any safe and minor updates we can make.

**Comment by dichotommy** [comment]
Rather than copying the file, might be better to do a fresh setup. First, we will need to initialize as an npm project, assuming that still makes sense for us. This is also likely to be required for #2239 + #2313 .

**Comment by guimachiavelli** [comment]
This issue is now the responsibility of an external team and will be monitored in their preferred platform.
