### ISSUE TITLE
aws installation guide suggest using gp2 while gp3 is recommended 

### ISSUE THREAD

**Issue by liesislukas** [meilisearch/documentation#2366]
Guideline mentions to use gp2, which is older SSD and gp3 would work faster and would save 20% in cost. 
https://aws.amazon.com/blogs/storage/migrate-your-amazon-ebs-volumes-from-gp2-to-gp3-and-save-up-to-20-on-costs/

https://www.meilisearch.com/docs/learn/cookbooks/aws#5-storage
![image](https://user-images.githubusercontent.com/2733862/232027365-821d4a59-18ef-451b-b4af-075a4f65b8db.png)

![image](https://user-images.githubusercontent.com/2733862/232027664-608db792-c572-4440-a7e6-bfce24d2bd59.png)

**Comment by maryamsulemani97** [comment]
Hey @liesislukas,

Thank you for the detailed issue. While your suggestion is great, we prefer to avoid going into details in the deployment guides. The purpose of these is to give the user the necessary information to get a Meilisearch instance running. I did create a [PR linking the AWS docs](https://github.com/meilisearch/documentation/pull/2475).

I will be closing this issue. Please let me know if you have any questions.

**Comment by guimachiavelli** [comment]
@maryamsulemani97, though you are right we shouldn't get into specifics, this issue does indicate room for improvement in our AWS deployment guide.

As you said, "we prefer to avoid going into details in the deployment guides," but in this case we are going into detail and that detail is now out-of-date. Can you try to rephrase that bit so we're not mentioning GP2 specifically? Alternatively, we can emphasise GP2 was our choice, but not the single or best choice.

**Comment by maryamsulemani97** [comment]
I should have mentioned this before closing the issues. I discussed all these issues with @alallema. She suggested avoiding going into details in the deployment guides and sticking to the necessary information to get a Meilisearch instance running.

**Comment by guimachiavelli** [comment]
Closed in favor of #2663
