### ISSUE TITLE
aws installation guide suggests open SSH port which is security issue and not recommended on aws

### ISSUE THREAD

**Issue by liesislukas** [meilisearch/documentation#2367]
user should instead add IAM role with AmazonSSMManagedInstanceCore permission and keep SSH port closed and use aws connect to connect to ec2 instance over terminal. also SSM agent must be installed inside the AMI

![image](https://user-images.githubusercontent.com/2733862/232028391-3740e477-50d3-463f-8864-ad0a40045e8f.png)

![image](https://user-images.githubusercontent.com/2733862/232028453-3d63957c-c673-4a17-83e9-49461b107a6e.png)

![image](https://user-images.githubusercontent.com/2733862/232028756-a99978cf-c638-4a23-9122-dff557aed968.png)

**Comment by maryamsulemani97** [comment]
Hey @liesislukas,

Thank you for the detailed issue. While your suggestion is great, we prefer to avoid going into details in the deployment guides. The purpose of these is to give the user the necessary information to get a Meilisearch instance running. I did create a [PR linking the AWS docs](https://github.com/meilisearch/documentation/pull/2475).

I will be closing this issue. Please let me know if you have any questions.

**Comment by guimachiavelli** [comment]
@maryamsulemani97, please consult one of our devs. Though we don't need to give the best, most up-to-date info regarding third-party services, it might be possible to update this guide so it's still following best security practices.

**Comment by maryamsulemani97** [comment]
I should have mentioned this before closing the issues. I discussed all these issues with @alallema. She suggested avoiding going into details in the deployment guides and sticking to the necessary information to get a Meilisearch instance running.

**Comment by curquiza** [comment]
@guimachiavelli same question than for the previous issue [here](https://github.com/meilisearch/documentation/issues/2366#issuecomment-1771239983) 😇

**Comment by guimachiavelli** [comment]
Closed in favor of #2663
