### ISSUE TITLE
AWS installation guide missing part of elastic IP

### ISSUE THREAD

**Issue by liesislukas** [meilisearch/documentation#2368]
With current installation guide if user would need to update instance type which requires stopping the instance, instance would get new IP address and setup would fail. Guidelines should mention to add elastic ip on the instance, especially for production setup.

https://www.meilisearch.com/docs/learn/cookbooks/aws#5-storage

![image](https://user-images.githubusercontent.com/2733862/232029559-6a1c9863-9be2-4264-958d-d12b2c29adf3.png)

![image](https://user-images.githubusercontent.com/2733862/232029596-e9e29e6c-9d19-4381-8a64-5685f3230ea1.png)

![image](https://user-images.githubusercontent.com/2733862/232029730-2c4be2ff-eb35-4d06-b1e8-7e42c831ca52.png)

**Comment by maryamsulemani97** [comment]
Hey @liesislukas,

Thank you for the detailed issue. While your suggestion is great, we prefer to avoid going into details in the deployment guides. The purpose of these is to give the user the necessary information to get a Meilisearch instance running. I did create a [PR linking the AWS docs](https://github.com/meilisearch/documentation/pull/2475).

I will be closing this issue. Please let me know if you have any questions.

**Comment by guimachiavelli** [comment]
@maryamsulemani97, same as with the other issue: please consult one of our SMEs.

**Comment by guimachiavelli** [comment]
Closed in favor of #2663
