### ISSUE TITLE
Improve site organization + visibility

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2380]
# Visibility project

Increase the clarity of site organization and the number of visitors to underperforming pages via quick wins.

## Will do 

- [ ] ~Rename “Advanced topics” section~
  - ~Related issue: https://github.com/meilisearch/documentation/issues/2398~
  - ~Related PR:~
- [x] Delete the “Philosophy” page
  - Related issue: https://github.com/meilisearch/documentation/issues/2386
  - Related PR: https://github.com/meilisearch/documentation/pull/2392
- [x] Deal with “Features” page
  - Related issue: https://github.com/meilisearch/documentation/issues/2388
  - Related PR: https://github.com/meilisearch/documentation/pull/2393
- [x] Move indexing & performance + updating Meilisearch to the top of their respective categories
  - Related issue: https://github.com/meilisearch/documentation/issues/2387
  - Related PR: https://github.com/meilisearch/documentation/pull/2389
- [x] Retitle pages called “overview” (except API reference overview)
  - Related issue: https://github.com/meilisearch/documentation/issues/2385
  - Related PR: https://github.com/meilisearch/documentation/pull/2394
- [x] Breakdown advanced topics
  - Related issue: https://github.com/meilisearch/documentation/issues/2435
  - Related PR:
- [x] Update `/learn/what_is_meilisearch/overview`
  - Related issue: https://github.com/meilisearch/documentation/issues/2391
  - Related PR:  https://github.com/meilisearch/documentation/pull/2447

## Could do

Promote the following underperforming guides in other site sections: 

- [x] Indexing & performance
  - Related issue: https://github.com/meilisearch/documentation/issues/2387
  - Related PR: https://github.com/meilisearch/documentation/pull/2389
- [x] Geosearch
  - Related issue: https://github.com/meilisearch/documentation/issues/2433
  - Related PR: https://github.com/meilisearch/documentation/pull/2453
- [x] Sorting
  - Related issue: https://github.com/meilisearch/documentation/issues/2433
  - Related PR: https://github.com/meilisearch/documentation/pull/2453
- [x]  Asynchronous operations
  - Related issue: https://github.com/meilisearch/documentation/issues/2434
  - Related PR: https://github.com/meilisearch/documentation/pull/2455

Eliminate the following pages, which are stubs:

- [ ] Prefix search
  - Related issue: https://github.com/meilisearch/documentation/issues/2396
  - Related PR:
- [ ]  Concatenate and split queries
  - Related issue:
  - Related PR:
- [ ]  ~Dumps vs. snapshots~
  - ~Related issue: https://github.com/meilisearch/documentation/issues/2395~
  - ~Related PR: https://github.com/meilisearch/documentation/pull/2397~

**Comment by maryamsulemani97** [comment]
We could convert the "Data backup: Snapshots vs dumps" page to an FAQ.

**Comment by maryamsulemani97** [comment]
For prefix search:

Can we create a section called "Types of search" on the search API reference and add placeholder, phrase, and prefix search there? That way, we won't have to duplicate content for both GET and POST search routes.
