### ISSUE TITLE
invalid link in error to ranking rules

### ISSUE THREAD

**Issue by masukomi** [meilisearch/documentation#2384]
```
/Users/masukomi/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/meilisearch-0.22.0/lib/meilisearch/http_request.rb:131:in `validate': 
400 Bad Request - Invalid value at `.rankingRules[0]`: `title` ranking rule is invalid. 
Valid ranking rules are words, typo, sort, proximity, attribute, exactness and custom 
ranking rules.. See https://docs.meilisearch.com/errors#invalid_settings_ranking_rules. (MeiliSearch::ApiError)
```

The link provided is a 404. 

I think the correct link is <https://www.meilisearch.com/docs/reference/errors/error_codes#invalid_settings_ranking_rules>

**Comment by Kerollmops** [comment]
Hi team, I moved this issue to the documentation repository as those links should be universal, and the documentation website should maintain redirection. We will keep those links on the engine side. We cannot update the previous version of Meilisearch to accommodate new documentation pages.

**Comment by maryamsulemani97** [comment]
Fixed in https://github.com/meilisearch/meilisearch.com/issues/106
