### ISSUE TITLE
Improve site organization + visibility: Retitle pages called “overview”

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2385]
As part of https://github.com/meilisearch/documentation/issues/2380, we'd like to rename "Overview" pages.

We have overview pages for the following sections:
- What is Meilisearch (`/learn/what_is_meilisearch/overview`)
- Index settings (`/learn/configuration/settings`)
- Contributing (`/learn/contributing/overview`)

**Comment by maryamsulemani97** [comment]
## Suggestions

### Contributing (`/learn/contributing/overview`)
We can move the content from `/learn/contributing/overview` to `/learn/contributing/contributing_docs`. We will have two H2s: 
- Contributing to Meilisearch
- Contributing to the docs
### Index settings (`/learn/configuration/settings`)
Rename to "Configure index settings"
### What is Meilisearch (`/learn/what_is_meilisearch/overview`)
![Screenshot 2023-04-26 at 18 11 58](https://user-images.githubusercontent.com/90181761/234602857-f51cc871-1120-48cd-a525-b80e3174efad.png)

The page is called "What is Meilisearch". We could call it that, but having the same section and page name may be confusing

**Comment by dichotommy** [comment]
How about "All index settings" for `/learn/configuration/settings`? Not a fan of "Configure index settings", we're already overusing the word "configure". And it might actually be in our best interest to reserve that word for launch options.

**Comment by maryamsulemani97** [comment]
As discussed in https://github.com/meilisearch/documentation/issues/2391, Gui and I agree that moving this content to an FAQ is a bad idea.

Looking at it again, I think we shouldn't change  "Overview". The section is called "What is Meilisearch", so Overview makes sense. It will give an "overview" of Meilisearch: what is it, what does it offer, a demo.
