### ISSUE TITLE
Copy to clipboard buttons are not working in some pages

### ISSUE THREAD

**Issue by atoulmet** [meilisearch/documentation#2390]
The buttons that appear on hover next to the sections are not working properly.
Nothing gets copied to clipboard, and it appears there's just an empty icon.

# How to reproduce
For example, go to [the get settings section](https://www.meilisearch.com/docs/reference/api/settings#get-settings). The anchor seems to be right, on hover the button appears, but when you click on it, nothing gets copied to clipboard.

**Comment by maryamsulemani97** [comment]
Hey @atoulmet 👋 

Thanks for the issue! Could you specify the code sample or container for which the "Copy to clipboard" button isn't working? All the buttons under the "All settings" section work for me 😕

**Comment by atoulmet** [comment]
Hi @maryamsulemani97 😊
I made a small video where I first copy a random word to my clipboard (with `cmd` + `c`), then I click the button, try to paste, and I still have the previous random word.

https://www.loom.com/share/544f063769ec4aa19557c998533c2628

I use Google Chrome on Mac Monterey.

**Comment by atoulmet** [comment]
@maryamsulemani97 Oopsie, sorry for this 🙈
Thanks for your explanation!

**Comment by atoulmet** [comment]
@maryamsulemani97 Oopsie, sorry for this 🙈
Thanks for your explanation!
