### ISSUE TITLE
Improve site organization + visibility: Update `/learn/what_is_meilisearch/overview.mdx`

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2391]
As part of #2380, we want to update `/learn/what_is_meilisearch/overview.mdx` to:

- Remove "[SDKs and integrations](https://www.meilisearch.com/docs/learn/what_is_meilisearch/overview#sdks-and-integrations)" and "[Alternatives](https://www.meilisearch.com/docs/learn/what_is_meilisearch/overview#alternatives)" headings
   - We have dedicated pages for both that are visible in the sidebar
- Add a gif using Meilisearch under "[Give it a try!](https://www.meilisearch.com/docs/learn/what_is_meilisearch/overview#give-it-a-try)"

**Comment by dichotommy** [comment]
I'm going to go a step further and suggest that **we convert this entire page into an FAQ answer.**

I think if I'm clicking on FAQs on the Meilisearch documentation, I expect that the first question would be "What is Meilisearch", and the answer would be basically what is present on this page, minus the subsections, which can probably just be converted into links.

WDYT?

**Comment by guimachiavelli** [comment]
I'm in-between your opinions. I think the usefulness of the "What is Meilisearch" section is _very_ limited, but I agree with @maryam that if this section exists, it needs to answer the question in its title. Also,  ⚔️ FAQ 💀 

Anyway, my suggestion is that we keep the overview, but make it very, very simple. Personally I would cut everything except the 5 initial paragraphs, but that might be too extreme.

**Comment by maryamsulemani97** [comment]
>Anyway, my suggestion is that we keep the overview, but make it very, very simple. Personally I would cut everything except the 5 initial paragraphs, but that might be too extreme.

We will be removing the Features (https://github.com/meilisearch/documentation/pull/2393) and Philosophy (https://github.com/meilisearch/documentation/pull/2392)  pages so that content will be moved here, though in a condensed form.

So this page will contain:

- the first 5 paragraphs as they are
- the Demo section
- Features
- Philosophy
