### ISSUE TITLE
Improve site organization + visibility: convert Dumps vs. snapshots to an FAQ

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2395]
As part of #2380, we would like to remove a few pages.

Instead of completely deleting [Data backup: Snapshots vs dumps](https://www.meilisearch.com/docs/learn/advanced/snapshots_vs_dumps), we can convert some of its content to an FAQ.

**Comment by guimachiavelli** [comment]
I'm strongly against this. We're essentially making content harder to find by putting it in the FAQ.

I think there are two reasonable choices here:
- keep this page, perhaps making some light edits 
- remove the page, but edit "Dumps" and "Snapshots" so users reading these pages already know the answer to the question "when should I use dumps and when should I use snapshots"

**Comment by maryamsulemani97** [comment]
Both pages have a "Usecase" heading at the bottom explaining this. We could expand that if needed.

I thought it would be helpful to have an FAQ where users have a brief explanation and comparison of both; that way, they won't need to read both guides separately.

**Comment by guimachiavelli** [comment]
Yeah, you're right. I think we should keep "Dumps vs snapshots". Perhaps change the title slightly to something like "Deciding whether to use snapshots or dumps", or something better.

**Comment by maryamsulemani97** [comment]
> Perhaps change the title slightly to something like "Deciding whether to use snapshots or dumps", or something better.

I think the current title is good enough. It's not just about when to use snapshots or dumps but also what each is.

@dichotommy 
If moving it to the FAQs hides this information then we should keep it here. This page is useful as it gives users a brief explanation and comparison of both; that way, they don't need to read both guides separately.

**Comment by guimachiavelli** [comment]
Since we both agree on this, I'm closing the issue.
