### ISSUE TITLE
Misleading sentence on the search API

### ISSUE THREAD

**Issue by irevoire** [meilisearch/documentation#2403]
Hey,

I was looking for some info on how the filter works in meilisearch and noticed we had this table summarizing all the types of available search parameters.
[This one](https://github.com/meilisearch/documentation/blob/a0ad491bc474bedc25ffaee509812c551a5e6168/reference/api/search.mdx?plain=1#L41) seems wrong, though. A filter can be **either** a `string`, an `array of strings`, or an `array of array of strings`.

I don't know if it's a good idea to show all these types, but I would be in favor of either;
- showing the three options
- only saying `string`

**Comment by dichotommy** [comment]
Perhaps we could change it to `string`* and link to the [section of the filtering guide about filter expressions](https://www.meilisearch.com/docs/learn/advanced/filtering#filter-expressions).

**Comment by maryamsulemani97** [comment]
@irevoire

Does this apply to `facets` parameter too?
