### ISSUE TITLE
Add field allowing users to insert their own master/API key in code samples

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2406]
[We have received a suggestion](https://github.com/meilisearch/documentation/pull/2399#discussion_r1185470729) to allow for users to insert their own auth keys, then alter all code samples so they use the given key. This could make copypasting code samples easier.

This would have to be requested via basement, since it's largely independent of our written content (and outside of the @meilisearch/docs-team's expertise).

## Potential problems

- Some code samples (mostly those launching Meilisearch and configuring instances) must use the master key, while the majority should use regular API keys. Could this be an issue? Would we require two fields?
- How would this interface work? Would it be unwieldy or add significant visual complexity?

Is this something the @meilisearch/docs-team is interested in pursuing?

**Comment by maryamsulemani97** [comment]
Related issue: https://github.com/meilisearch/documentation/issues/480

**Comment by guimachiavelli** [comment]
I thought we already had an issue for this but couldn't find it. Thanks!

Closing as duplicate.
