### ISSUE TITLE
v1.2: Delete and get documents by filter

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2411]
With v1.2, users will be able to get and delete documents by filter.

## To do
- [ ] Update [documents API page](https://www.meilisearch.com/docs/reference/api/documents) to add the new routes:
   - [ ] POST `indexes/:index_uid/documents/fetch`
   - [ ] POST `indexes/:index_uid/documents/delete` 
   - [ ] Update links to use the new endpoints

## References
- Issue on engine repo: https://github.com/meilisearch/meilisearch/issues/3477
- Specs:
   - Spec on get documents by filter: https://github.com/meilisearch/specifications/pull/234
   - Spec on delete documents by filter: https://github.com/meilisearch/specifications/pull/236
 - SME: @dureuill, @irevoire  @macraig

**Comment by irevoire** [comment]
Hey @maryamsulemani97, thanks a lot for catching that :scream: 
Yes, it's totally the case, and I'm going to specify it + add a test for it (yeah because it was forgotten to that extent)
