### ISSUE TITLE
 v1.2: Telemetry table updates

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2414]
We need to update the telemetry table for Meilisearch's new release.

## Changes

- [x] New datapoint: `per_filter` (https://github.com/meilisearch/specifications/pull/234)
- [x] New datapoint: `clear_all` (https://github.com/meilisearch/specifications/pull/236)
- [x] New datapoint: `infos.experimental_reduce_indexing_memory_usage` https://github.com/meilisearch/specifications/pull/239/files#diff-dbac052211a8ea4b2c5d068a6264380740b022efead552b4dfc9e4e8d961f0f4R102

@maryamsulemani97, please add to this list as you begin working on your own v1.2 issues. Just specify the field and, if available, its spec.

## References
- SME: @gmourier

**Comment by maryamsulemani97** [comment]
fixed in #2416
