### ISSUE TITLE
v1.2: Add new `IS NULL` and `IS EMPTY` filter operators

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2415]
v1.2 introduces two new filter operators, `IS NULL` and `IS EMPTY`.

`IS NULL` matches fields that exist but have an explicit `null` value:

```json
{
  "name": null
}
```

`IS EMPTY` matches fields that exist but have an empty value, including strings, objects, and arrays:

```json
{
  "name": "",
  "reviews": [],
  "locations": {}
}
```

Both operators can be used together with `NOT`: `IS NOT EMPTY`, `NOT [attribute] IS EMPTY`, `IS NOT NULL`, `NOT [attribute] IS NULL`.

## Tasks

- [ ] Update `/learn/advanced/filtering.mdx`

## References
- spec: https://github.com/meilisearch/specifications/pull/232
- issues: https://github.com/meilisearch/meilisearch/issues/3615, https://github.com/meilisearch/meilisearch/issues/3614
- SME: @Kerollmops

**Comment by maryamsulemani97** [comment]
fixed in #2416
