### ISSUE TITLE
v1.2: Automatic culling of old tasks when maximum database size reached

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2420]
v1.2 sets a limit of 1M to the maximum number of tasks stored in the task database. Once Meilisearch reaches this size and a user tries to enqueue another task, Meilisearch will automatically try to delete the oldest 100k tasks. Unfinished tasks are not deleted. If all 100k tasks are currently unfinished, Meilisearch will notify the user and enqueue the task.

## Tasks

- [ ] Update `/learn/advanced/asynchronous_operations.mdx`
- [ ] Update `/learn/advanced/known_limitations.mdx`

## References
- spec: https://github.com/meilisearch/specifications/pull/238
- issue on core: https://github.com/meilisearch/meilisearch/issues/3622
- SME: @irevoire

**Comment by irevoire** [comment]
Hey @guimachiavelli,

> If all 100k tasks are currently unfinished, Meilisearch will not enqueue the new task and notify the user.

Actually, if all the 1M tasks are unfinished and meilisearch can't delete any tasks, it'll still enqueue the new task!

**Comment by guimachiavelli** [comment]
Ah, ok, thanks for letting me know. Can you confirm we need to [change this line ](https://github.com/meilisearch/engine-team/pull/49/files#diff-10663f28e62ea120d48eee02e20cf5957a963556280dd0167e2f906f2f41e786R137) on the changelog?

**Comment by maryamsulemani97** [comment]
fixed in #2416
