### ISSUE TITLE
Download & Launch link is not working

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/documentation#2439]
I saw this link
https://www.meilisearch.com/docs/reference/features/installation#download-and-launch

In the js repository README.

This is the direct replacement, right? https://www.meilisearch.com/docs/learn/getting_started/installation#installation

I'm not sure if this can be fixable or we should change it in the js repo?

**Comment by dichotommy** [comment]
Hey @brunoocasali , wow that's a very old link! It would be best to change it in the js repo, and the replacement link you sent is perfect. Thank you very much 🙇🏻 🙏🏻

**Comment by brunoocasali** [comment]
Cool, perfect! I'll close this issue then! ciao!
