### ISSUE TITLE
Fix TO filter operator example in Learn > Advanced > filtering

### ISSUE THREAD

**Issue by adesombergh** [meilisearch/documentation#2463]
The example for the TO operator in "[Learn > Advances > Filtering](https://www.meilisearch.com/docs/learn/advanced/filtering#to)" is wrong:

Wrong (current):
```
rating.users 80 TO rating.users 89
```

Right (should be):
```
rating.users 80 TO  89
```

**Comment by maryamsulemani97** [comment]
Thanks for the issue @adesombergh! We've created a PR fixing it: https://github.com/meilisearch/documentation/pull/2470.
