### ISSUE TITLE
Crawler to fill in index from static site

### ISSUE THREAD

**Issue by edi9999** [meilisearch/documentation#248]
Hello, 

I wish to add search to a static website. The site is just plain HTML, and I would basically like to have a crawler that crawls my whole site and generates index itself.

In this commit, it is written : Change site organization for the crawler : 

https://github.com/meilisearch/documentation/commit/c8141e8bb15bb31f0749cd26ea8fbb945b98fdfa

So I'm guessing that you are yourself using such a crawler ? If yes, do you mind to point me the code that you use for that, and/or what is the general operating mode of this crawler ? @curquiza

**Comment by edi9999** [comment]
Oh I just found this : 

https://github.com/meilisearch/docs-scraper :)

**Comment by curquiza** [comment]
Hello!
Yes, you found out our crawler 🙂
However, it works only for documentation. I mean, the way of indexing your data in MeiliSearch fits for documentation purposes. Is it your use case?

FYI, I'm currently working on improving [docs-scraper](https://github.com/meilisearch/docs-scraper). It's not well-documented for the moment, I mean if someone else wants to use it.  And I'm updating it to work with the new MeiliSearch version (the v0.9.0).

If you are interested, I will keep you informed when I'm done 🙂

**Comment by edi9999** [comment]
I'm not sure, my website is about some paid extensions for an open-source library, the website is at https://docxtemplater.com/modules/image/ (this is  the doc about the image module as an example).

I will see what I can do from my end. Using selenium or similar is at least a good starting point.

**Comment by edi9999** [comment]
Ok, and yes, I would definitely like to be informed, thanks !

**Comment by curquiza** [comment]
Ok, It might be possible by well-filling the config file.
When I will finish, we can try to configure that with you and see together if it's possible.

Are you already on our slack? https://slack.meilisearch.com

**Comment by edi9999** [comment]
Hello @curquiza , no I'm not on slack and it seems that I need an invite to be able to join, can you add me (my email address is on my github profile).

It would be very cool to see together if that is possible !

**Comment by curquiza** [comment]
I've just sent you an invitation at contact@javascript-ninja.fr :)

**Comment by edi9999** [comment]
Thanks ! Can you please remove my email from your comment, I would like to avoid having it at more places than it already is to avoid spam.

**Comment by curquiza** [comment]
For other people reading this issue, a tutorial [How to integrate a search bar to you docs with MeiliSearch](https://docs.meilisearch.com/resources/howtos/search_bar_for_docs.html) is now available 🎉 
It should work for static websites!

@bidoubiwa you can finally close this issue 🙂

**Comment by Jieiku** [comment]
@curquiza Is there a way to perform a similar search to this but without javascript: https://docs.meilisearch.com/resources/howtos/search_bar_for_docs.html

I imagine it would function more like submitting a form and returning a newly generated page, instead of a results as you type approach.
