### ISSUE TITLE
v1.3: Experimental API route

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2482]
The engine team is working on creating a new API route to manage experimental features without the need for CLI flags and environment variables. The aim is to make it easier for users to turn experimental features on and off, something which will also benefit Meiliearch's cloud offering.

Not all experimental features will be editable via the new endpoint. We won't havetime  to implement an interface for some (e.g. `/metrics` endpoint), and it is impossible to use the API to manage others (e.g. `--experimental-reduce-indexing-memory-usage`).

## Tasks
- [ ] create new overview page under "Learn > Experimental" presenting experimental features, the experimental API, and which features can be configured via the API
- [ ] create new page under "Reference > API" describing the API route

## References
- PRD (private): https://www.notion.so/meilisearch/Runtime-API-to-toggle-Experimental-Feature-a9e4053bbc6f42539983b782cd9b2a3b
- Slack discussion (private): https://meilisearch.slack.com/archives/C056WNAV3L2/p1687444578105049
- SME: @dureuill

**Comment by guimachiavelli** [comment]
@dureuill, question:

Changes made to an experimental feature using the API persist between launches. For example, if I activate vector search via the API, that feature will still be active after I interrupt and relaunch an instance.

What happens when changes made via the API conflict with e.g. a cli flag? For example, if I launch Meilisearch with `--experimental-vector-search`, disable vector search via the API, and relaunch the instance with `--experimental-vector-search`? I assume the cli flag takes precedence?

**Comment by guimachiavelli** [comment]
@dureill, another question on the interaction between experimental options and experimental API.

Do cli flags/env vars mark an experimental feature as active in the API?

For example, if I launch Meilisearch with `--experimental-vector-search`, then `GET` query the API, will the response show `{"vector_search": true}`?

**Comment by dureuill** [comment]
Hello @guimachiavelli,

We sidestepped this issue by making it so that features that can be toggled at runtime cannot be enabled by a command line flag, a configuration setting or an environment variable.

**Comment by guimachiavelli** [comment]
duh, sorry, I missed that. Thanks for pointing it out 🙏

**Comment by dureuill** [comment]
You're welcome! It was a good question, hence why we decided to not answer it right away in this first iteration

**Comment by guimachiavelli** [comment]
Ok, another question, which I hopefully have not missed from the PR nor the PRD.

From what I'm seeing, we have implemented a `POST` endpoint for this route. What is its use case for `POST` in this route?

**Comment by dureuill** [comment]
hmmm, I think we don't have a good reason to provide a `POST` endpoint here. I'll check with people that know more about REST than I do
