### ISSUE TITLE
Fix wrong assertion about the number of fields by document

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/documentation#2488]
Hey, docs-team 👋

[There is a wrong assertion about the limit of the number of fields in a document](https://www.meilisearch.com/docs/learn/advanced/known_limitations#maximum-number-of-document-fields). The new limit is 65536 fields which should probably be even undocumented.

Could you, please, remove this paragraph? As even if the limit is reached there is no more undefined behavior regarding the ranking rules.

Have a nice day 🌻

**Comment by maryamsulemani97** [comment]
Hey @Kerollmops,

Thanks for the issue. To clarify: We have a limit of 65536 document fields. Even if the user exceeds this limit, the ranking rules will work as expected.

Will exceeding this limit impact anything else? If so, we can remove this from "Known limitations".

Thanks!

**Comment by Kerollmops** [comment]
> Will exceeding this limit impact anything else? If so, we can remove this from "Known limitations".

It shouldn't impact anything else 😃

**Comment by guimachiavelli** [comment]
Out of curiosity, does anything at all happen when a user tries to add a document with >65536 fields? Will they get an error, will the engine ignore these extra fields, or will everything just function regularly?

**Comment by Kerollmops** [comment]
> Out of curiosity, does anything at all happen when a user tries to add a document with >65536 fields? Will they get an error, will the engine ignore these extra fields, or will everything just function regularly?

[There will be an error](https://github.com/meilisearch/meilisearch/issues/3833) reporting that the maximum number of 65536 fields has been reached.
