### ISSUE TITLE
Fix broken links reported by new checker

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2521]
The broken links checker created in #2507 has found quite a few issues. We need to resolve these before we can merge that PR.

Table copied from #2507 
| Broken link | Type | File | 
| ----------- | ----------- | ----------- | 
| /learn/cookbooks/dockerr.mdx | link | [/./home.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/./home.mdx) | 
| /learn/front_end/search_preview | link | [/learn/what_is_meilisearch/overview.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/what_is_meilisearch/overview.mdx) | 
| /learn/configuration/instance_options#http-address-port-binding | hash | [/learn/getting_started/search_preview.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/getting_started/search_preview.mdx) | 
| /learn/core_concepts/primary_key#primary-key-2 | hash | [/learn/core_concepts/documents.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/core_concepts/documents.mdx) | 
| /learn/advanced/sorting | link | [/learn/core_concepts/indexes.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/core_concepts/indexes.mdx) | 
| /learn/advanced/sorting | link | [/learn/core_concepts/relevancy.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/core_concepts/relevancy.mdx) | 
| /learn/core_concepts/relevancy#_2-typo | hash | [/learn/core_concepts/relevancy.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/core_concepts/relevancy.mdx) | 
| /reference/errors/error_codes#task-not-found | hash | [/learn/async/asynchronous_operations.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/async/asynchronous_operations.mdx) | 
| /learn/core_concepts/relevancy#_2-typo | hash | [/learn/index_settings/typo_tolerance.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/index_settings/typo_tolerance.mdx) | 
| /learn/fine_tuning_results/geosearch#filtering-results-with-georadius-and-geoboundingbox | hash | [/learn/fine_tuning_results/filtering.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/fine_tuning_results/filtering.mdx) | 
| /learn/advanced/sorting#configuring-meilisearch-for-sorting-at-search-time | link | [/learn/fine_tuning_results/geosearch.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/fine_tuning_results/geosearch.mdx) | 
| /learn/advanced/sorting#sorting-results-at-search-time | link | [/learn/fine_tuning_results/geosearch.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/fine_tuning_results/geosearch.mdx) | 
| /learn/advanced/sorting#sorting-and-custom-ranking-rules | link | [/learn/fine_tuning_results/geosearch.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/fine_tuning_results/geosearch.mdx) | 
| /reference/errors/error_codes#invalid-search-sort | hash | [/learn/fine_tuning_results/geosearch.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/fine_tuning_results/geosearch.mdx) | 
| /learn/fine_tuning_results/geosearch#sorting-results-with-geopoint | hash | [/learn/fine_tuning_results/sorting.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/fine_tuning_results/sorting.mdx) | 
| /reference/api/keys#actions-2 | hash | [/learn/security/tenant_tokens.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/security/tenant_tokens.mdx) | 
| /reference/api/keys#actions-2 | hash | [/learn/security/tenant_tokens.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/learn/security/tenant_tokens.mdx) | 
| /learn/core_concepts/primary_key#primary-key-2 | hash | [/reference/api/documents.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/documents.mdx) | 
| /learn/core_concepts/primary_key#primary-key-2 | hash | [/reference/api/documents.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/documents.mdx) | 
| /learn/advanced/sorting | link | [/reference/api/search.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/search.mdx) | 
| /learn/core_concepts/relevancy#_5-sort | hash | [/reference/api/search.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/search.mdx) | 
| /reference/errors/error_codes#invalid-search-filter | hash | [/reference/api/search.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/search.mdx) | 
| /learn/fine_tuning_results/geosearch#sorting-results-with-geopoint | hash | [/reference/api/search.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/search.mdx) | 
| /reference/api/search#search-in-an-index-with-post-route | hash | [/reference/api/keys.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/keys.mdx) | 
| /reference/api/search#search-in-an-index-with-get-route | hash | [/reference/api/keys.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/keys.mdx) | 
| /reference/errors/error_codes#api-key-not-found | hash | [/reference/api/keys.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/keys.mdx) | 
| /learn/advanced/sorting | link | [/reference/api/settings.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/settings.mdx) | 
| /learn/advanced/sorting | link | [/reference/api/settings.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/settings.mdx) | 
| /learn/advanced/sorting | link | [/reference/api/settings.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/api/settings.mdx) | 
| /reference/api/indexes#body-3 | hash | [/reference/errors/error_codes.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/errors/error_codes.mdx) | 
| /reference/api/indexes#body-3 | hash | [/reference/errors/error_codes.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/errors/error_codes.mdx) | 
| /reference/api/indexes#body-3 | hash | [/reference/errors/error_codes.mdx](https://github.com/meilisearch/documentation/blob/a7e99b9ce1c9ad2e8f88c9d44d4925d4a5f99233/reference/errors/error_codes.mdx) |

**Comment by curquiza** [comment]
Fixed by #2507 that is integrated into #2507 (which is merged)
