### ISSUE TITLE
Meilisearch documentation says it has "nested field support", but it doesn't

### ISSUE THREAD

**Issue by njaard** [meilisearch/documentation#2525]
In the page [Document Schema section](https://www.meilisearch.com/docs/learn/what_is_meilisearch/comparison_to_alternatives#document-schema) of the comparison page, you list "Nested field support" as a feature of both Elasticsearch and Meilisearch.

However, "Nested Field Support" in elasticsearch terminology is not what Meilisearch supports. Meilisearch seems to support some sort of "JSON object destructuring", which appears to just be a way to name fields. Elasticsearch's [Nested Field](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) is something more akin to a "Join" in SQL terminology.

**Comment by guimachiavelli** [comment]
hello @njaard! Thanks for taking the time to create this issue.

I see what you mean—it might be confusing for users to see two somewhat related features summarised under the same term. If I may ask you for a bit more of your time: is the lack of something exactly like Elasticsearch's `nested` data type affecting you? If so, can you describe your use case?

What do you think about this, @gmourier and @macraig?

**Comment by njaard** [comment]
Yes, an equivalent to Elasticsearch's "nested" feature is required for me. Imagine my excitement when I saw the reference to support for it in Meilisearch's documentation, and then my disappointment when read I further.

Here's an example of what I do, with a fictional example. I have an index of Companies, each Company has a number of Employees:

* Company
  * name
  * website
  * number_of_employees

* Employee
  * name
  * city
  * university
  * role

So, now, let's say I want to find all the companies with fewer than 10 employees, and a CEO that studied at "Berkeley":

```
number_of_employees<10 employees.role="CEO" employees.university="Berkeley"
```

Without Elasticsearch's definition of "nested fields", this will give me all the companies with fewer than 10 employees, where the company has _a_ CEO, and _any_ employee studied at Berkeley.

Here's how I might do this in SQL, with two tables:

```
select * from companies C where number_of_employees<10
  and exists (select 1 from employees where employer=C.company_id and city='CEO' and university='Berkeley')
```

**Comment by guimachiavelli** [comment]
Thanks for this, @njaard, it's really helpful. I'm discussing this issue with our engineering team and will update it as soon as we identify the best way to update the docs to avoid any confusion.

**Comment by guimachiavelli** [comment]
After having discussed this with the engineers, we have decided we will update the docs to clarify what we mean with "nested fields" and how it is different from elasticsearch's nested document querying.

---

## Summary notes

Both Meilisearch and Elasticsearch allow users to search for data in nested fields (e.g. an array of objects, an object containing an arbitrary number of other nested objects).

Elasticsearch additionally supports nested document querying. In @Kerollmops's words, nested document querying is "a way of considering a sub-object as a whole when filtering and therefore being able to specify two distinct sub-objects fields to match a condition in one of the sub-object not any sub-object in a single document to match any of the filters."

## Tasks
- [ ] Update `learn/what_is_meilisearch/comparison_to_alternatives.mdx#document-schema`: properly distinguish nested fields from nested document querying
- [ ] Update `https://www.meilisearch.com/docs/learn/advanced/datatypes#objects`: describe what can/cannot be done with Meilisearch's nested fields

## References
- https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html
- https://github.com/meilisearch/product/discussions/544#discussioncomment-6240444
- SME: @Kerollmops
