### ISSUE TITLE
Sorting document is not found

### ISSUE THREAD

**Issue by aooohan** [meilisearch/documentation#2526]
When I was reading the sorting section of the search document, the reference link of sorting page is show 404.
Also, the version shows v1.2, hasn't this page been updated yet?

https://www.meilisearch.com/docs/learn/filtering_and_sorting/sorting

**Comment by curquiza** [comment]
Hello @aooohan 
Thanks for the report
Can you show me exactly where you saw this broken link? I don't succeed in finding it

**Comment by aooohan** [comment]
Hi, @curquiza.  Look following picture.
https://www.meilisearch.com/docs/reference/api/search#sort
<img width="862" alt="image" src="https://github.com/meilisearch/documentation/assets/40265686/bac27966-ded8-478b-a255-5079b8c33e18">

**Comment by curquiza** [comment]
@guimachiavelli weird we did not fix this link with your PR (https://github.com/meilisearch/documentation/pull/2524)
Is it expected?

**Comment by curquiza** [comment]
Hey @justkahdri

Contrary to what we supposed [here](https://github.com/meilisearch/documentation/pull/2507#issuecomment-1671655061), the broken link is still present, so was not detected by the checker, right?

**Comment by justkahdri** [comment]
I'm currently seeing the link fixed. It probably was still deploying the new version when you checked, or maybe it was showing an old cached version of the page.

Nevertheless I'll monitor it closer on the next broken links update. 🙏🏼

**Comment by aooohan** [comment]
It's fine now. 👍

Thank you for such an amazing project. : )

**Comment by curquiza** [comment]
It works on my side now as well! Thank you very much everyone!
