### ISSUE TITLE
New known limitation about facet search

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#2529]
Add a [known limitation](https://www.meilisearch.com/docs/learn/advanced/known_limitations) about facet search: the maximum number of retrievable facets is `100`. It's currently not able to customize it but it's considered for future implementation, cf [PRD](https://www.notion.so/meilisearch/Search-for-facet-values-PRD-c9499f0654dd4f06ad786730222f4ad2#e3ccfec4fb3e491589b72f1af69cb62b) (internal only)

Following https://github.com/meilisearch/meilisearch/issues/3980 and https://github.com/meilisearch/documentation/pull/2528

**Comment by curquiza** [comment]
Hello @RyanGoudie01 
thank you very much for this PR
I'll let @guimachiavelli review the PR since he's the maintainer of the repository, but he's on Holiday for one week more. This addition is not an emergency so far.
Thank you again ❤️

**Comment by RyanGoudie01** [comment]
No problem. This is my first PR so fingers crossed it can be accepted. 🤞🏻

**Comment by curquiza** [comment]
It will be reviewed, we will probably ask for changes, but if you are reactive, it will be accepted at the end 😊 
Thanks for your patience during this Holiday period!
