### ISSUE TITLE
Improve custom ranking rules example text

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2537]
The last line of the example text under "Ranking rules > Custom rules" in `/learn/core_concepts/relevancy.mdx` reads:

> To add a rule to the existing ranking rule, you have to add the rule to the existing ordered rules array using the settings route,

This is very difficult to parse due to the repetition of the same words referring to different things in very quick succession. Though this might be unavoidable to some extent, we should be able to rephrase it so it's easier to read.

**Comment by RecreationalMath** [comment]
Hi @guimachiavelli,

I couldn't find the `/learn/core_concepts/relevancy.mdx` file in documentation repository.
Looking around the documentation folder structure it seems it has been renamed/moved to `learn/relevancy/relevancy.mdx` but this file doesn't contain the specified line.
I checked `learn/relevancy/custom_ranking_rules.mdx` file as well to locate the specified line but couldn't find.

Perhaps this issue has already been solved as part of some other documentation improvement, if not then could you please guide me, what am I missing?

**Comment by guimachiavelli** [comment]
Hi there, @RecreationalMath!

I think you're correct. We did rewrite significant parts of the relevancy documentation earlier this year and it seems this issue was inadvertently fixed then.
