### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Sunlight-Rim** [meilisearch/documentation#2569]
https://www.meilisearch.com/docs/learn/security/master_api_keys#updating-an-api-key
Unclosed single quote in the curl example of the Master api keys article.
>` -X PATCH 'http://localhost:7700/keys/74c9c733-3368-4738-bbe5-1d18a5fecb37 \`

**Comment by guimachiavelli** [comment]
Thanks for reporting this, @Sunlight-Rim! 

Issue has now been fixed on the live site.
