### ISSUE TITLE
Review "Running in Production"

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2579]
The initial sections of `/learn/cookbooks/running_production.mdx` are in dire need of editing. The language is marketing-oriented ("running a meilisearch instance is incredibly easy"), and the text is opinion-heavy ("using meilisearch for your weekend project is fun"), possibly condescending, and almost empty of any actual information.

- [ ] Rewrite first subsection into a short paragraph briefly introducing the guide, or remove it altogether.
- [ ] Rewrite article title (currently "Run Meilisearch in production: taking it to the next level")

**Comment by curquiza** [comment]
Isn't this a duplication of https://github.com/meilisearch/documentation/issues/2187?

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
not a duplication. This issue is more English oriented, and the other one (#2187) about fixing technical information.
