### ISSUE TITLE
bug: `movies.json` link is broken in quick_start page

### ISSUE THREAD

**Issue by kskarthik** [meilisearch/documentation#2607]
Section: https://www.meilisearch.com/docs/learn/getting_started/quick_start#add-documents

Problematic element:

```html
<a id="downloadMovie" download="movies.json" target="_self" class="underline text-pink underline-offset-2 transition-colors hover:text-current" href="a">movies.json</a>
```

Looks like it's originating from this file https://github.com/meilisearch/documentation/blob/d2b6ae754da81692916d9f2a997d1fe0fa627eaa/learn/getting_started/quick_start.mdx#L69

**Comment by guimachiavelli** [comment]
Hello @kskarthik! Just to inform you we pushed a fix for this a few minutes ago. The download link should be working once again.

Thanks for spotting this!
