### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by LeonAlvarez** [meilisearch/documentation#2624]
Link https://discord.com/invite/meilisearch is broken, was trying to find community link without success

**Comment by guimachiavelli** [comment]
Hello @LeonAlvarez! Thanks for reporting this issue. We had some temporary issues with our Discord invite, but all links in the Documentation should be working as expected now.

In case you still need it, here's the official link to Meilisearch's Discord server: https://discord.meilisearch.com

Thanks again!

**Comment by PaezRice** [comment]
On your landing page the link seems to be broken again. Link directs to the URL specified by OP

**Comment by curquiza** [comment]
Thanks @PaezRice for the report, reporting this to the team
