### ISSUE TITLE
v1.7: Huggingface embedder updates

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2736]
v1.7 allows users to generate embeddings with NVidia GPUs.

## Questions
- Is this being exposed on Meilisearch Cloud? If so, will it require any user input or will it be sorted out on our end?

## Tasks
- [ ] Update `learn/experimental/vector_search`

## References
- SME: @dureuill 
- Initial documentation: https://github.com/meilisearch/meilisearch/issues/4306#issuecomment-1893849620
- Engine issue: https://github.com/meilisearch/meilisearch/issues/4306

**Comment by dureuill** [comment]
Hello :wave:

> is this being exposed on Meilisearch Cloud? 

It isn't
