### ISSUE TITLE
No example displayed in a tip box

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#2764]
No example displayed here: https://www.meilisearch.com/docs/reference/api/overview#authorization

<img width="784" alt="Capture d’écran 2024-03-18 à 18 20 24" src="https://github.com/meilisearch/documentation/assets/20380692/4289f7e5-dad4-483c-8d7e-cbec6bd90909">

**Comment by guimachiavelli** [comment]
I believe this was related to an error in the code samples `yaml` file. As far as I can see, this was fixed by #2765. 

Please reopen this issue if you're still seeing this missing code sample.

**Comment by curquiza** [comment]
No issue anymore 🎉
