### ISSUE TITLE
Hugging Face overview page

### ISSUE THREAD

**Issue by gbutterfield** [meilisearch/documentation#2770]
https://www.meilisearch.com/docs/learn/cookbooks/computing_hugging_face_embeddings_gpu

This command:
cargo build --release --features cuda

fails because a repo package cant be found.
error: failed to download `candle-kernels v0.3.1 (https://github.com/huggingface/candle.git#f4fcf609)`

**Comment by guimachiavelli** [comment]
Thanks for reporting this, @gbutterfield.

@dureuill, do you have any idea what might be going on here? Do we need to explicitly install candle?

**Comment by dureuill** [comment]
Hu, that's unexpected, it seems the [commit does exist upstream](https://github.com/huggingface/candle/commit/f4fcf609)

Unfortunately I cannot try right now as I don't have immediate access to a CUDA enabled machine

**Comment by gbutterfield** [comment]
The 1.8 update has resolved this issue and the cargo build step works.

**Comment by guimachiavelli** [comment]
Thanks for updating the issue, @gbutterfield!

Pinging @dureuill, only FYI, no action needed.
