### ISSUE TITLE
Users are struggling when creating tenant token

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#2786]
A user struggled to understand why the search requests were failing with their tenant token

https://github.com/meilisearch/meilisearch/discussions/4567#discussioncomment-9118613

They wanted to access the full index but without specifying any filter, so they needed to add `indexName: {}` which was not intuitive. Maybe we could detail this?

@guimachiavelli, to be honest, I did not check in the documentation if this explanation is already available, so feel free to close this issue if not useful

However I think it's still useful to work on tenant token experience. To let you know, and maybe we could do something on the product side as well: users often struggle with tenant token usage because they DON'T know why the request is forbidden (i.e. the tenant token is invalid). The message is really vague and does not indicate if the action or the index is forbidden. So maybe we could add some warning of basic errors to check have having issues with tenant token?

**Comment by guimachiavelli** [comment]
Reworking the tenant tokens article is in this quarter's roadmap. I'll make sure to address the `indexName: {}` bit when I get to that.

**Comment by guimachiavelli** [comment]
As noted by the support team, whether the API key uuid is necessary is not communicated very clearly in the tenant token guide. Fixing that should also be part of this rework.

Reference link (private slack chat): https://meilisearch.slack.com/archives/CD7AJLL01/p1715863916526779

**Comment by irevoire** [comment]
> The message is really vague and does not indicate if the action or the index is forbidden. So maybe we could add some warning of basic errors to check have having issues with tenant token?

I also believe it’s something we should fix from the engine directly

**Comment by curquiza** [comment]
I agree, pinging @gmourier and @macraig for the product part, since we have product usage frustration here
