### ISSUE TITLE
Search analytics now support multi-search

### ISSUE THREAD

**Issue by Strift** [meilisearch/documentation#2817]
The docs states that search analytics [isn't compatible with multi-search](https://www.meilisearch.com/docs/learn/cloud/analytics#update-urls-in-your-application), but it now is.

There's an issue in meilisearch-cloud that confirms this, and @brunoocasali confirmed it [on Slack too](https://meilisearch.slack.com/archives/C01K0CZKASZ/p1713356936160609).

**Comment by guimachiavelli** [comment]
Fixed in #2826
