### ISSUE TITLE
Add links to competitors comparison

### ISSUE THREAD

**Issue by Strift** [meilisearch/documentation#2823]
Hi, it would be great if the [comparison to alternatives](https://www.meilisearch.com/docs/learn/what_is_meilisearch/comparison_to_alternatives) pages would link to the more detailed comparisons we wrote about some competitors:
- [elastic comparison](https://blog.meilisearch.com/why-should-you-use-meilisearch-over-elasticsearch/)
- [typesense comparison](https://blog.meilisearch.com/meilisearch-vs-typesense/)

**Comment by guimachiavelli** [comment]
Pinging the comparison page maintainers, @meilisearch/product-team.
