### ISSUE TITLE
Add examples of every SDK where for the moment there is only curl in the guides

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#283]
In the getting started guide there is an example in every official MeiliSearch SDK. Those examples should also be in the the other guides.

Should we thing of a clever way to handle this or should we simple put them by hand and update them on every release if needed?

Suggestions are welcome.

Example in getting started: 
<img width="760" alt="Screenshot 2020-04-07 at 15 31 45" src="https://user-images.githubusercontent.com/33010418/78675123-ea7a9480-78e4-11ea-9569-fa5d86ee568e.png">

**Comment by curquiza** [comment]
In my opinion, we should find a way for the docs to automatically update the examples when there is a new version.
The exactness of the code snippets is not the responsibility of the docs, but more of the SDK maintainers.

Why not a kind of template in each SDK repository that the maintainers update when needed. With this solution, the maintainer would change the code AND the documentation in a single PR 🙂
Then, this repository (the docs) could fetch this template and update the code snippets accordingly.

**Comment by bidoubiwa** [comment]
Great idea!
