### ISSUE TITLE
Ranking score details missing in search overview

### ISSUE THREAD

**Issue by the-sinner** [meilisearch/documentation#2838]
Info about `showRankingScoreDetails` missing in search overview
[Link](https://www.meilisearch.com/docs/reference/api/search#overview)
![Screenshot 2024-06-03 at 10 51 20 PM](https://github.com/meilisearch/documentation/assets/34604329/909398c5-7e35-4d1c-b48a-c1622678db27)

**Comment by guimachiavelli** [comment]
Thanks for opening this issue, @the-sinner.

Should have been fixed by #2895
