### ISSUE TITLE
Guide on promoting products with kle.io

### ISSUE THREAD

**Issue by sebastian** [meilisearch/documentation#2851]
Hi 👋

In two locations in your docs (under [core concepts](https://github.com/meilisearch/documentation/blob/d86e13c6c4a9f876d703e11bec15c22f3fd1dcdd/learn/core_concepts/relevancy.mdx?plain=1#L184-L186) and under [fine tuning results](https://github.com/meilisearch/documentation/blob/d86e13c6c4a9f876d703e11bec15c22f3fd1dcdd/learn/fine_tuning_results/sorting.mdx?plain=1#L135-L137
)) you mention that Meilisearch does not offer support for sponsored products out of the box. 

I, and this is where this becomes a shameless plug, am the creator of an ad-server which, among other things, has built in support for Meilisearch. It's plug and play. You change your Meilisearch endpoint to the become that of the ad server, and the ad server proxies the request to Meilisearch and then runs an auction on the hits returned by Meilisearch before returning the final results to the client.

It's all documented here: https://kle.io/docs/meilisearch

Is there any chance we could mention this amongst the other resources referenced in these sections?

I'd, of course, be more than happy to create a pull-request if appropriate.

Lots of greetings and love from Berlin in Germany

**Comment by guimachiavelli** [comment]
Hello @sebastian, and thanks for getting in touch! Apologies for the delay in responding to your message. 

Pinging @meilisearch/devrel-team: what do you think? Would an article about kle.io fit in the "Guides" section?

**Comment by sebastian** [comment]
Hi @guimachiavelli!

From my point of view an article in the guides section would of course be wonderful. If there is anything I can do to help with the content, or to help clarify concepts, please let me know!

**Comment by Strift** [comment]
Hi @sebastian 👋 

Thank you for your proposal.

Sorry, but we currently don't accept community guides about third-party tooling. However, I added a link to your docs in the [awesome meilisearch](https://github.com/meilisearch/awesome-meilisearch) list.

Have a good day,
