### ISSUE TITLE
Missing `showRankingScoreDetails` on `/search` reference tables

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2870]
All search parameters should be present in both the `GET` and the `POST` endpoints of the `/search` route. `showRankingScoreDetails` is currently missing

## Tasks

- [ ] Add row to `POST` body parameter table with parameter name (`showRankingScoreDetails`), accepted value type (boolean), and brief description of setting
- [ ] Add row to `GET` query parameter table with parameter name (`showRankingScoreDetails`), accepted value type (boolean), and brief description of setting

**Comment by postmeback** [comment]
I would like to give it a try.

**Comment by guimachiavelli** [comment]
Hello @postmeback! Thank you for your interest, much appreciated ☺️ 

Feel free to send in a PR whenever you're ready and add me as a reviewer.

Looking forward!

**Comment by postmeback** [comment]
Well, I went to the website and searched with "/search", ended up on https://www.meilisearch.com/docs/reference/api/search page. There I searched with 'showRankingScore', there were 7 occurrences of it. 

Maybe I am searching at the wrong place, can you help me ? 

![image](https://github.com/meilisearch/documentation/assets/14862687/5baeeb85-4200-4355-800b-b5bd97745a27)

@guimachiavelli

**Comment by guimachiavelli** [comment]
Apologies, @postmeback, there was a typo in the original issue text.

Instead of
 
> "`showRankingScore` details"

the text should have read

> "`showRankingScoreDetails`"

as stated in the title of the issue.

**Comment by postmeback** [comment]
The PR is done, please review it.
