### ISSUE TITLE
v1.10: Language settings

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2934]
## References
- SME: @ManyTheFish 
- PRD: https://www.notion.so/meilisearch/v1-10-Language-settings-usage-26c5d98b553349d9abacbe7aff698e4e
- Engine issue: https://github.com/meilisearch/meilisearch/issues/4749

**Comment by curquiza** [comment]
I applied this fix: https://github.com/meilisearch/documentation/pull/2956
