### ISSUE TITLE
v1.10: Code sample changes tracker

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2941]

**Comment by guimachiavelli** [comment]
## #2945 

- New code sample: `multi_search_federated_1`

**Comment by guimachiavelli** [comment]
## #2950 

- New: `search_parameter_reference_locales_1`
- New: `get_localized_attribute_settings_1`
- New: `update_distinct_attribute_1`
- New: `reset_distinct_attribute_1`

**Comment by guimachiavelli** [comment]
This should be the final list, @meilisearch/integration-team 🙇

**Comment by curquiza** [comment]
@guimachiavelli I think it's
- not `update_distinct_attribute_1` but `update_localized_attribute_settings_1`
- not `reset_distinct_attribute_1` but `reset_localized_attribute_settings_1`

I updated here: sorry if I was wrong

**Comment by curquiza** [comment]
Done for JS and PHP, you can close 🎉
