### ISSUE TITLE
Remove `meilisync` as an option to sync PostgreSQL

### ISSUE THREAD

**Issue by omar-zahid** [meilisearch/documentation#2960]
`meilisync` is suggested as a way to sync data between Postgresql and meilisearch. This wrongly implies `meilisync` as an official adapter from `meilisearch`. To make things worse, this app is buggy (at least for PG) and causes errors in production.  

Here is the documentation in question: https://www.meilisearch.com/docs/guides/database/meilisync_postgresql

Here are the open issues in `meilisync` related to postgres.

https://github.com/long2ice/meilisync/issues/68
https://github.com/long2ice/meilisync/issues/111
https://github.com/long2ice/meilisync/issues/37
https://github.com/long2ice/meilisync/issues/28

For us, we've encountered production outage due to WAL errors and our storage spiked to 100% due to the replication slot errors.

![image](https://github.com/user-attachments/assets/733572bf-da4a-44de-ac9c-f5de0f8514c0)

Please consider removing meilisync from the documentation at least until the issues above are addressed and the app is stable. Thank you.

**Comment by guimachiavelli** [comment]
Thanks for the feedback, @omar-zahid. We have been getting more and more reports of users experiencing similar issues to yours. We were already seriously considering removing meilisync content from the docs and your report sort of seals the deal for me.

@Strift, I think we should go ahead and remove both the Postgre and the MySQL meilisync guides. Are you ok with that?

**Comment by Strift** [comment]
@guimachiavelli, I agree.

But these guides are also featured in Meilisearch Cloud, so we need to validate this with @meilisearch/product-team.

**Comment by macraig** [comment]
I think this makes sense, @gmourier do you agree? If so we can ask the Cloud team to remove any mentions on the Cloud

**Comment by Strift** [comment]
Note: we have external articles linking to our meilisync guides, e.g. [this piece](https://www.dragonflydb.io/blog/top-10-modern-data-infrastructure-2024-part-02?hss_channel=tw-1535352010421063680). We'll need to think of a redirection for this links. 

I think redirecting to meilisync repo would be good enough, and better than a 404. Not feeling strongly this either, so happy to go in another direction.

**Comment by gmourier** [comment]
> I think redirecting to meilisync repo would be good enough, and better than a 404

Agree

**Comment by ohld** [comment]
Great idea, guys!

But how then I should sync MeiliSearch db with a table in Postgres?

**Comment by guimachiavelli** [comment]
Hello @ohld!

This issue is about the removal of `meilisync` content from the official documentation due to users reporting too many issues with that tool. We do plan to provide more content on database migration in the future, but we're still in the early stages of discussing what should be our official guidance on the matter.

For a more immediate solution, I'd recommend reaching out to our support staff and the community on Meilisearch's official Discord server. You're much more likely to get timely and useful help there.
