### ISSUE TITLE
v1.11: Code sample changes

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2997]

**Comment by guimachiavelli** [comment]
## #3011

- updated: `search_parameter_guide_hybrid_1`
- updated: `search_parameter_reference_retrieve_vectors_1`

**Comment by guimachiavelli** [comment]
This should be the final list of code sample updates for v1.11, @meilisearch/integration-team

**Comment by curquiza** [comment]
It's now done and ready for the release day
