### ISSUE TITLE
v1.12: Code sample updates

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#3065]

**Comment by guimachiavelli** [comment]
## #3070 

- NEW: `get_facet_search_settings_1`
- NEW: `update_facet_search_settings_1`
- NEW: `reset_facet_search_settings_1`
- NEW: `get_prefix_search_settings_1`
- NEW: `update_prefix_search_settings_1`
- NEW: `reset_prefix_search_settings_1`

**Comment by curquiza** [comment]
pinging @Strift here and @meilisearch/integration-team

**Comment by guimachiavelli** [comment]
## #3072 

- NEW: `get_all_batches_1`
- NEW: `get_batch_1`

**Comment by guimachiavelli** [comment]
This is the final list of code sample updates for v1.12.

pinging @curquiza, @meilisearch/integration-team, @Strift

**Comment by Strift** [comment]
Thanks for the ping. I'll add the code samples to the JavaScript and PHP SDKs this week.

**Comment by curquiza** [comment]
@guimachiavelli 
For your information I just added @Strift to @meilisearch/integration-team group on GitHub 👌 
(Unfortunately on Slack I cannot, despite I would like)

**Comment by Strift** [comment]
I submitted PRs to add the relevant code samples, they should be merged shortly 🙏 

Links FYI
- JavaScript: https://github.com/meilisearch/meilisearch-js/pull/1801
- PHP: https://github.com/meilisearch/meilisearch-php/pull/711
