### ISSUE TITLE
Upgrade mermaid version to latest and fix breaking changes

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#314]
In an upgrade, [mermaid](https://mermaid-js.github.io/mermaid/#/) went from version `8.4` to `8.5`. The changes in this new release break the implementation of our mermaid schema.

This should be addressed at some point.

Step to reproduce 
```
yarn upgrade mermaid

yarn build
```

If you now go to the asynchronous updates guides, in advanced guides, you should observe the schema not rendered.

**Comment by tpayet** [comment]
#368 solved it. It's working now
