### ISSUE TITLE
Create a page: MeiliSearch limits

### ISSUE THREAD

**Issue by qdequele** [meilisearch/documentation#327]
Limites are:

- 10Mb of body JSON on AddDocuments and UpdateDocuments.
- 1000 words per attribute max indexed.
- 65536 words per documents
- 65536 max fields given to MeiliSearch during all life of the Index.
- ?? indexes
- 100Gb Database size (Could be increased)

-> Redirect to "Best practices of indexing"

@Kerollmops could you confirm this information and tell us if there are more restrictions?

**Comment by erlend-sh** [comment]
I assume each limit also comes with some common-practice workarounds? I’ve seen a few of those explained on crisp/slack already. 

So what I’m saying is each limitation should probably be followed by a “how to work around it” section.

**Comment by qdequele** [comment]
Yes, of course, I created an issue https://github.com/meilisearch/documentation/issues/328

**Comment by Kerollmops** [comment]
IIRC the number of indexes is something around 300 but it will change with https://github.com/meilisearch/MeiliSearch/issues/625 as there will be new internal databases, therefore the max number will decrease (to something like 200).

The maximum number of indexed words is indead around 1000 but some users reported that this was lower than that, I investigated and my test lead to 963 words, so yeah we can put "around 1000" in the documentation. This will probably change when the new tokenizer is is place anyway.

I confirm the other limits.
