### ISSUE TITLE
Adding DigitalOcean deployment to quickstart & installation guide

### ISSUE THREAD

**Issue by tpayet** [meilisearch/documentation#361]
Should we add the DigitalOcean one click deploy to the installation guide?

I am not sure regarding the quickstart though

**Comment by curquiza** [comment]
Maybe not in the quick start, but maybe in the [What's next?](https://docs.meilisearch.com/guides/introduction/whats_next.html) section 🙂

**Comment by erlend-sh** [comment]
I think this is the same discussion from a different angle:
https://github.com/meilisearch/documentation/issues/358
