### ISSUE TITLE
Titles on images are conflicting with check-md rules

### ISSUE THREAD

**Issue by eskombro** [meilisearch/documentation#364]
EXAMPLE: 

`![img](../../public/image/digitalocean/03.select-plan.png "Select plan")`

ERROR MESSAGE: 

```
File is not found: ![img](../../public/image/digitalocean/03.select-plan.png "Select plan") (/Users/esk/Meili/documentation/resources/howtos/digitalocean_droplet.md:21:1)
```

WORKING EXAMPLE: 

`![Select plan](../../public/image/digitalocean/03.select-plan.png)`

WHAT SHOULD BE WORKING: 

`![Select plan](../../public/image/digitalocean/03.select-plan.png "Select plan")`

**Comment by curquiza** [comment]
(Just a tip: you don't need to provide all the path for the image, Vuepress looks for your image in `public`. Cf [this examples in the Postman tutorial](https://raw.githubusercontent.com/meilisearch/documentation/master/resources/postman_collection.md).)

**Comment by curquiza** [comment]
Does the working example make the job to provide a title as you expected?

**Comment by eskombro** [comment]
No it doesn't. What I mean is that this was my fix to pass the check, but the image title is not shown!
I created this issue with @bidoubiwa as a reminder to fix the problem, but she apparently knows how to solve the issue.
But thanks to you, I added the `WHAT SHOULD BE WORKING` example

**Comment by bidoubiwa** [comment]
Yes the problem lies at the string added at the end of the URL

> ![img](../../public/image/digitalocean/03.select-plan.png "Select plan")

The `"Select plan"` makes the link checker throw an error. 

The reason why @eskombro added that string is because it generates a `title` attribute in the `img` tag: https://www.w3schools.com/tags/att_title.asp. When hovering on the image you should then see "select plan". It is considered good practice.

**Comment by bidoubiwa** [comment]
You were right about the paths @curquiza.

The reason why some links on the documentation uses `../../public` instead of the shortened path you propose is because the images were in the wrong `public/` folder.

I have moved them all: #336 

Thanks curquiza :D
