### ISSUE TITLE
Docs examples: get keys example not displayed

### ISSUE THREAD

**Issue by eskombro** [meilisearch/documentation#406]
In the API reference, the [get keys example](https://docs.meilisearch.com/references/keys.html#example) is not displayed for JavaScript, but the example is present in the [js examples file](https://github.com/meilisearch/meilisearch-js/blob/master/.code-samples.meilisearch.yaml#L40). I don't know if this error is coming from the js file or the docs

**Comment by curquiza** [comment]
Pretty sure it should be `get_keys_1: |-` and not `get_keys: |-` in the js file example.

**Comment by eskombro** [comment]
Moved issue [here](https://github.com/meilisearch/meilisearch-js/issues/444)

Please close this one :)
