### ISSUE TITLE
Splitting big documents to improve relevancy

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/documentation#432]
It would be great if we provide a guide page where we explain that splitting is the best way to deal with big documents.

This is [not the first time](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1593102886140600?thread_ts=1593101716.135700&cid=CP9DVS1RQ) [people try to index big documents](https://github.com/meilisearch/MeiliSearch/issues/556#issuecomment-605333369) in MeiliSearch and encounter issues.

Splitting documents by paragraph or even by sub-title/content like for the MeiliSearch documentation is the best way to deal with that as it allows the engine to answer with more precise part of the original text.

To do so the original documents must be split into shorter parts where the original document id should be kept and a `distinctRule` can be used on the original document id to make sure only the best part of the original documents is shown to the user.

**Comment by tpayet** [comment]
Close in favor of #328

**Comment by bidoubiwa** [comment]
It could be added in two places : 

1. In the `FAQ` as it appears to be a common question: 
    - `Why are my documents are not fully indexed?`
    - `Why is my dataset is not fully added?`
2. In the [documents guide](https://docs.meilisearch.com/guides/main_concepts/documents.html#upload)

```
The best way to upload a big dataset is to split it into smaller chunks. This will prevent data loss or potential memory crashes.
If your documents contain fields with a lot of data, consider splitting them by paraghraph or sub-title/contents. This allows the engine to answer with more precision.
```

**Comment by tpayet** [comment]
@bidoubiwa could you comment in #328 or reopen this one if you feel it should be
