### ISSUE TITLE
Suggestion: Stop words for languages

### ISSUE THREAD

**Issue by devrck** [meilisearch/documentation#444]
Hi guys,

I know that Meilisearch starts from scratch :smile: but maybe it's useful to have on the docs page some standard stop words for each language that it supports.

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stop-tokenfilter.html#analysis-stop-tokenfilter-stop-words-by-lang

What do you guys think?

Sorry if i opened the issue in this project, please move it to the correct one if needed.

**Comment by guimachiavelli** [comment]
Although I can definitely see why it is useful to have a list of common stopwords for supported languages, are we the best people to host such a list? Do we want that responsibility?

According to our docs we support pretty much any white-space separated language (which includes but is not limited to pretty much every language written in the latin alphabet) and Chinese. That's a pretty daunting list, and one I'm not sure the @meilisearch/docs-team has the proper skillset to create.
