### ISSUE TITLE
Document facet type restrictions

### ISSUE THREAD

**Issue by rsalmond** [meilisearch/documentation#447]
Turns out knowing nothing about Rust makes it fairly hard to read, but based on some testing it appears that after configuring facet attributes, documents will not be indexed if the values of those attributes are integers. Converting them to strings got things working for me.

If this is a known limitation it'd be good to document.

**Comment by bidoubiwa** [comment]
Hey,
Thanks for creating this issue. I will update the documentation after recieving some additionnal information from the core team.
