### ISSUE TITLE
Missing field in the sample template

### ISSUE THREAD

**Issue by Mubelotix** [meilisearch/documentation#473]
The field `settings_guide_synonyms_1` is missing from https://docs.meilisearch.com/sample-template.yaml.

**Comment by bidoubiwa** [comment]
Yes, this is fixed in this PR #439! I also made a script that will inform what sampleId is missing from each SDK sample file on documentation build. 
Thanks for your input!

**Comment by bidoubiwa** [comment]
fixed by: #439
