### ISSUE TITLE
Example hardcoded

### ISSUE THREAD

**Issue by Mubelotix** [meilisearch/documentation#474]
The example for `attributes for faceting` [here](https://docs.meilisearch.com/guides/advanced_guides/settings.html#example-3) is hardcoded in the doc.

**Comment by Mubelotix** [comment]
And the example for `Ranking rules` is hard-coded too.

**Comment by bidoubiwa** [comment]
I will look into that

**Comment by bidoubiwa** [comment]
Ranking rules does not seem hardcoded to me. Could you confirm where it is hardcoded?

**Comment by Mubelotix** [comment]
That's right. I made a mistake.
