### ISSUE TITLE
Wrong field name

### ISSUE THREAD

**Issue by Mubelotix** [meilisearch/documentation#475]
In [this guide](https://docs.meilisearch.com/guides/advanced_guides/faceted_search.html#using-facets), the field `genre` is often written `genres` which leads to an error.

**Comment by Mubelotix** [comment]
In fact, the example database does not correspond at all with this guide and this is very confusing. For example, the guide is using inexistant `producer`, `director`, and `production_companies` fields and `genres` instead of `genre`.

**Comment by Mubelotix** [comment]
It is even showing an integer type instead of a String for the `id` field.

**Comment by bidoubiwa** [comment]
Hey @Mubelotix, 
This is absolutely something that needs to be fixed. We have mixed two datasets together as the base dataset didn't had any "facetable" fields. 
I have recently added the `genre` field in the example dataset. But as you have noticed we wrote `genres` in the examples. 
Also you are right, `director, producer, production_companies` does not exist in the example dataset. 
We used them to showcase what was possible if you had a dataset with multiple faceted fields. I did not expect someone to follow that guide with the given movie dataset. Those will have to be updated as well. 
Thanks a lot for you input.

**Comment by guimachiavelli** [comment]
Closing this issue because the guide it points to doesn't exist as of #924.

We have an ongoing discussion on the `movies.json` dataset and how we can best communicate to our users that it is only valid for the getting started tutorial on #1026.
