### ISSUE TITLE
Code samples should be tested

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#478]
A script should be made to try out all the code samples that are added to the documentation through the `.code-samples.meilisearch.yaml` files.

This script should run on build and test that all added samples in the documentation are up to date with the latest of MeiliSearch.

This will require to think about a strategy on how it will be possible.
- Should an order of execution be determined ?
- Should we run an environment for every different languages that will be tested (python, javascript, ...) and install the corresponding latest package ?
- Should we only start with the `curl` examples as MVP ?

**Comment by guimachiavelli** [comment]
Though this sounds like a great thing, between reorg, the uncertain future of non-`curl` code samples, and the fact the technical side of the docs is now managed by an external team make it very unlikely we'll be able to implement this anytime soon.
