### ISSUE TITLE
More technically detailed comparison of solutions

### ISSUE THREAD

**Issue by tpayet** [meilisearch/documentation#492]
From Crisp: ```I'm just a hobbyist, so probably not worth your time, but just fyi: a more structured and technical comparison between engines would be helpful, perhaps a table, also showing relative suitability for large data, dynamic data, segmented data (per-project / customer), etc```

That sound reasonable, let's wait and see if anyone else ask for this :)

**Comment by maryamsulemani97** [comment]
@ferdi05, does the current[ Comparison to alternatives](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html) page resolve this? Not sure about the "relative suitability for large data, dynamic data, segmented data (per-project / customer), etc" part

Thanks!

**Comment by ferdi05** [comment]
@maryamsulemani97 I believe so. Hard to know if a request from 2020 is still relevant.
Let's say so, until we receive more feedback.
