### ISSUE TITLE
Add instant-meilisearch in SDK list

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#504]
Instant meilisearch https://github.com/meilisearch/instant-meilisearch should be added in the [sdk list](https://docs.meilisearch.com/resources/sdks.html)

**Comment by fharper** [comment]
Which PR closed this issue?

**Comment by react-learner** [comment]
Unsure; I think it predates my arrival at Meili. I just know that instant-meilisearch is currently listed on the SDK list under Front-End Tools.

**Comment by fharper** [comment]
Oh OK, I thought you did a PR :D
