### ISSUE TITLE
Show languages supported by MeiliSearch

### ISSUE THREAD

**Issue by tpayet** [meilisearch/documentation#519]
What do you think of having a page in Resources about supported languages by MeiliSearch?

I was thinking of this format:

| Language | Optimized | Basic support | No support | Comment |
|---|:---:|:---:|:---:|---|
|🇬🇧 English|✅||||
|🇫🇷 French|✅||||
|🇩🇪 German||✅|| No tokenization of long german words made of multiple words |
|🇸🇦 Arabic|||⛔️||
|🇨🇳 Chinese|✅||||

We might also ask for help from community to fill this array based on the level of relevancy they get in their own language.

**Comment by curquiza** [comment]
It's a detail, but for unsupported languages, we could redirect them to the issue associated with the [product roadmap](https://roadmap.meilisearch.com/tabs/1-under-consideration) in the `Comment` column, so that we could know if it's an eagerly awaited feature 🙂

**Comment by tpayet** [comment]
Yes! Was also wondering if we could have a sub-product board just dedicated to language support so that anyone could vote for language we need to prioritize for the tokenizer refacto? @qdequele would that be possible?

**Comment by react-learner** [comment]
I think the new tokenizer page would be a perfect place for this. See: https://github.com/meilisearch/documentation/pull/685

**Comment by react-learner** [comment]
Leaving this out of #685 because not enough time. Planned for this week.

**Comment by react-learner** [comment]
Fixed by #699 . No fancy table for now, for a few reasons:
- Stating explicitly that some languages are not supported could discourage users from testing them and giving us feedback
- In terms of tokenization, we are technically only optimized for Chinese 😬 
- Large tables are difficult to format and maintain in Markdown 😩 😂
