### ISSUE TITLE
Error code missing

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#560]
The following error code: 
- `index_not_found` 

is missing in the `errors.yaml` file resulting in an absence of this error code in the documentation: https://docs.meilisearch.com.

It should be added with a clear and concise description.

Mentionned here: meilisearch/meilisearch-js#638

**Comment by CreaTorAleXander** [comment]
I would like to do this

**Comment by tpayet** [comment]
Hey @CreaTorAleXander, thank you for your interest. How comfortable do you feel about this? 

You should update the [errors.yaml file](https://github.com/meilisearch/documentation/blob/master/errors.yaml) and add index_not_found error with a short description using the same style we have for other errors.

You can then submit a pull request @bidoubiwa, @react-learner or I should be able to review and merge :) 

Let me know if you need any other informations!
