### ISSUE TITLE
Clarify/Rewrite faceted search guide

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#562]
The faceted search guide lacks in clarity, it should be rewritten.

Sentences like these are too confusing.
> Faceted attributes are the attributes used as facets. They must be added to the settings to be usable as facet filters.

**Comment by react-learner** [comment]
I wasn't able to find the example sentence mentioned above. Is this still an issue or has it been fixed?

**Comment by bidoubiwa** [comment]
Apparently, it is not there anymore. But the guide is still confusing I think. Could you confirm?

**Comment by guimachiavelli** [comment]
Fixed by #924
