### ISSUE TITLE
Make users aware of data.ms

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#584]
There is too little mention of data.ms in the documentation. Meaning users are confused when updating MeiliSearch to a new version.
We should find ways to integrate that knowledge into our documentation.

## What is data.ms?

data.ms is the default folder name for the database in MeiliSearch. It is in this folder that the database is stored with all its indexes, documents, settings, and updates. 

Data.ms name can change using `--db-path` CLI option.

Data.ms is bound to the version it was created on. Meaning that if you update MeiliSearch you need to delete and recreate the database.  Using [dumps](https://docs.meilisearch.com/guides/advanced_guides/snapshots_and_dumps.html#dumps) you can keep your data between versions.

**Comment by maryamsulemani97** [comment]
@meilisearch/docs-team what would be the best place for this? I could only think of the [Update to the latest Meilisearch version](https://docs.meilisearch.com/learn/advanced/updating.html) page or under "Data backup".
