### ISSUE TITLE
Confusing examples for Placeholder Search

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#585]
According to the documentation : 'A placeholder allows you to find documents without providing search terms.'  The placeholder search takes therefore place when no query string is provided. The confusing thing is, the provided examples show the query string in the search parameters.

**Comment by bidoubiwa** [comment]
Could you give the url to that part of the documentation?

**Comment by CaroFG** [comment]
https://docs.meilisearch.com/guides/main_concepts/search.html#features

**Comment by CaroFG** [comment]
It is indeed written : "To perform a placeholder search, simply omit the query parameter." But if you add the 'ranking rules' issue and the example that doesn't accurately illustrate the concept, I find it a bit confusing.

**Comment by CaroFG** [comment]
Realized it's a problem with the heading size that makes you think that the examples illustrate exclusively placeholder search. In fact the example section contains samples of search parameters in general. I'm closing this issue and making a PR to correct heading size.
