### ISSUE TITLE
Unclear ranking rules behaviour in Placeholder Search

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#586]
Advanced Guides > Sarch Parameters > Query (q) 
"A placeholder allows you to find documents without providing search terms. It will return documents sorted according to the ranking rules order."

The ranking rules listed in the documentation depend on the query string. How do they behave with the placeholder ?

**Comment by bidoubiwa** [comment]
The following should be explained: 

- How does MeiliSearch order documents in placeholder search without any query 
- How do Ranking Rules impact placeholder search?
