### ISSUE TITLE
Add gif demonstrating faceted search

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#600]
I propose that we create a gif demonstrating how placeholder search can be used with facets and filtering to create an intuitive visual interface for searching + browsing. Currently, the description of placeholder search is a bit too theoretical and lacks a solid visual example to show the power of this feature. 

I recommend a gif displaying an online storefront. Placeholder search allows the customer to view and browse all products in the storefront, while facets allow them to browse by category and filters to narrow on criteria like price.

**Comment by dichotommy** [comment]
As noted in #776 which this issue replaces, it is particularly important to replace the Amazon storefront image currently found [here](https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#faceted-search) in the faceting guide.

We may be able to use an existing Meilisearch demo for this.

**Comment by dichotommy** [comment]
Could be done as part of #1902

**Comment by maryamsulemani97** [comment]
We could also add this to the [Front-end integration](https://docs.meilisearch.com/learn/getting_started/quick_start.html#front-end-integration) step of the Quick start

**Comment by guimachiavelli** [comment]
That's a good question. Do you think we still need that gif, @maryamsulemani97? What would we lose by removing it?

**Comment by guimachiavelli** [comment]
I think @maryamsulemani97's assessment of the situation is correct and this issue is no longer relevant.
