### ISSUE TITLE
Components reusability

### ISSUE THREAD

**Issue by tpayet** [meilisearch/documentation#62]
Sometime we need to have the same information written twice or more in the documentation. 
-> We do not want to maintain two versions of the same thing as it is not DRY

We have to find a way to reuse some components. For example, on the get [Quick start](https://docs.meilisearch.com/getting_started/quickstart.html) we have the same documentation as on the [download page](https://docs.meilisearch.com/getting_started/download.html).

Vuepress team [seems to promote](https://github.com/vuejs/vuepress/issues/222#issuecomment-458693558) the use of `<Content/>` but it seems [not fully handled](https://github.com/vuejs/vuepress/issues/222#issuecomment-513102036).

**Comment by maryamsulemani97** [comment]
Closing as the new site will have reusable components
