### ISSUE TITLE
Adapt JavaScript Tutorial

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#621]
Michiel Mulders wrote a tutorial for us on using Meilisearch's JavaScript SDK to search a database of Nobel Prize winners: https://blog.meilisearch.com/how-to-search-nobel-prize-winners-faster-with-meilisearch-api-for-javascript/

We should adapt this and add it to the documentation. Content should be smoothed over and style adjusted. Edit for clarity. And maybe further down the road, we can find a more exciting dataset 😅

**Comment by maryamsulemani97** [comment]
Closing as we won't be doing this
