### ISSUE TITLE
Add "How to Search Nobel Prize Winners Faster With MeiliSearch and JavaScript" to the documentation

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#630]
Add a copy of [How to Search Nobel Prize Winners Faster With MeiliSearch and JavaScript](https://blog.meilisearch.com/how-to-search-nobel-prize-winners-faster-with-meilisearch-api-for-javascript/) into the tutorials section of the documentation and set the canonical link to the doc on the blog post.

**Comment by bidoubiwa** [comment]
The tutorial has been added to reddit and hacker news as a canonical link to the blog, what happens if the blog is a canonical link for the doc in this case?

**Comment by fharper** [comment]
It may not be something we want to do anymore with the new doc structure coming. I'll let @react-learner add his opinion and close the issue if we don't want to move further with that.
