### ISSUE TITLE
Duration + Difficulty Tags for Tutorials

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#633]
Ideally, every tutorial on our doc site would be tagged w/ a difficulty (i.e. beginner-intermediate-advanced) and an approximate duration (e.g. 5m, 25m, 1h). Currently, our VuePress site doesn't support things like this; it would require us to write these metrics explicitly in the tutorial body. This is a feature we should consider for the future when we switch to a platform that allows us more dynamic content and tighter control over display.

**Comment by maryamsulemani97** [comment]
@dichotommy, is this something we still plan on doing?
