### ISSUE TITLE
Documentation Restructure Proposal

### ISSUE THREAD

**Issue by react-learner** [meilisearch/documentation#634]
I would like to propose some changes to how we organize our MeiliSearch documentation.

First, some disclaimers: please note that I am not a UI/UX designer (actually I can’t even draw a straight line) so this proposal merely deals with the organization of content, not presentation. I’m not set on any of the names given in the last section, and I appreciate suggestions. Finally, I want to mention that—just by the nature of this topic—this post will mostly dwell on the negatives of our current documentation, not the many positives of the wonderful content created by @bidoubiwa and others on the team 🙏  I hope it's clear that it is all meant constructively and with an aim to make this resource the best it can be 💪  

### The Problem - Why do we need a new organization for our documentation? 😥 

Right now, our documentation is very effective on a content level. However, the lack of clear architecture (in terms of what type of content goes where) makes it difficult to maintain over time. It also has the side-effect of forcing users to rely on search, since browsing the site is often ineffective.

As a search engine company, this is not a bad problem to have 😉   There’s a reason that our developers seem to be mostly satisfied with our documentation: when you mainly use documentation to solve problems and find API references, navigating by search is ideal. 

However, while the documentation serves us well at this moment, I believe it will become increasingly problematic as it grows in size, and we begin to attract more beginners, hobbyists, and others from outside the open-source community, who expect a more guided approach and a clearer division of information.

**We can break our current problems down into a few parts. Right now:**

1. Most of our feature-oriented reference documentation is lumped together under a single category, “Advanced Guides”, making it difficult to find relevant content by browsing. This includes some information that does not seem particularly advanced (e.g. Installation, Web Interface), as well as all settings.

2. Technical info for some features is spread across multiple pages and sections, which may not be titled clearly, rather than being consolidated in one place (e.g. Searchable Attributes, Dumps).

3. Sections such as Main Concepts, which should focus on broad conceptual understanding, sometimes contain technical information that may or may not be repeated elsewhere (e.g. Ranking Rules).

4. Some API reference pages go beyond a brief description of the task they perform (e.g. Displayed attributes) to the extent that they stop being about the API. This is a problem because when API references give technical info about a feature, it's unclear how that info relates to other locations in the documentation where that feature is described (i.e. is this information unique, or is it repeated elsewhere?)

5. Outside of Getting Started, there is no clear path for beginners. Because there is no clear separation between content for beginners and content for experienced users, pages in the documentation must be written for every audience, instead of targeting a best approach for one specific audience.

I believe we have already received some complaints from experienced users about having to wade through basic search engine concepts and analogies while looking for technical reference info. I suspect that we will experience more of the opposite problem, beginners who are turned off by overly complex concepts mixed in with introductory material, as our software becomes more popular outside of the “open source scene”.

### The Question - What does good documentation organization look like? 🤔 

Django core developer/doc writer [Daniele Procida](https://www.youtube.com/watch?v=t4vKPhjcMZg), among others, breaks software documentation into four categories:

**Tutorials**
* learning-oriented
* rewarding/“fun”
* not necessarily useful in a production context
* _Meili example: Getting Started_

**How-to Guides**
* problem-oriented
* a repeatable “recipe” for achieving a desired result
* useful in a production context
* _Meili example: Setting Up Facets_

**Explanations/Discussions**

* understanding-oriented
* basically, anything that provides a broader context
* more conceptual or theoretical material
* _Meili example:_
    * _Filters or Facets?_
    * _Snapshots vs. Dumps_
    * _almost everything under Main Concepts_

**Technical References**
- information-oriented
- straight-forward, encyclopedia-like entries
- written in consistent technical language
- Consolidate all useful information on a feature
- _Most Meili doc pages currently fall into this category (esp. those under Advanced Guides)_

Currently, MeiliSearch’s documentation **excels at references and how-to guides**, which is why our open-source users appear to be quite satisfied: these categories are the most important for advanced users looking to put our software into production. On the other hand, **we have a lot of room to grow in the areas of tutorials and discussions**, two types of documentation that primarily aid software adoption and learning, not production.

**Let's use these terms to describe two guidelines for our documentation architecture.**
1. Content for beginners (mainly tutorials and simple explanations) should be separate from content for intermediate to experienced users (mainly guides, advanced discussions, and references).
2. Technical references should have their own section—not just API references, but feature references as well. If someone just wants to use our documentation like a manual, they should be able to.

In the future, there are other "best practices" we can codify for our documentation. But for now, these two are the most important for creating a new organizational structure that creates a learning flow and helps users find the content they need.

### My Solution 🚀 

While Daniele’s classification of documentation into four categories is extremely helpful, it’s not a good structure for a documentation site. Four is a bad number: it’s too many categories for a site-wide navbar, and too few categories to really be helpful finding things. Not to mention that the categories have overlap: the difference between guides and tutorials, for example, can be a point of particular confusion for users.

I believe that our eventual goal should be to replace our current three categories (Guides, API References, and Resources) with three new ones based on use-case: **Learn**, **Create**, and **Reference**.

The **Learn** page will contain all information related to learning the software, including tutorials, descriptions of key search concepts, and simple overviews of our key features / selling points.

The **Create** page will contain all the information an intermediate developer needs to put a MeiliSearch site or web app into production: solution-oriented step-by-step guides, plus cool articles, ideas, and comparisons to inspire higher-level projects.

The **Reference** page is pretty self-explanatory! They key thing is that it will contain references for all features, not just the API.

Here's a more hierarchical view:

**Learn**
- Tutorials
    - Getting Started
    - Next Steps
    - etc.
- Key Search Concepts
    - Documents
    - Relevancy
    - etc.
- Feature overview
    - Instant Search (e.g. “MeiliSearch supports Instant Search! Click here to view a guide that will show you how to use it, or click here to view the reference doc.”)
    - Faceting
    - etc.

**Create**
- How To:
    - Implement Instant Search in 5 Minutes
    - Quickly Set Up Attribute Ranking
    - Contribute to MeiliSearch
    - etc.
- Discover
    - Can MeiliSearch be used to help E.R. Doctors quickly diagnose symptoms?
    - Top 5 Sites Using MeiliSearch in Production
    - etc.

**Reference**
- Feature References
    - Indexes
    - Search Parameters
    - etc.
- API References
    - etc.

As far as the labor cost of implementation, these changes would mostly mean moving around files and renaming directories. However, some ambiguous pages (such as those currently under Main Concepts) would require more extensive reworks, or even to be split in two.

Whew, that's it! My hope is that this reorganization will help us have clarity on where every type of content belongs, and allow users to browse the documentation in the way they prefer. Thanks for reading, and please leave your questions, comments, and concerns below ⬇️

**Comment by fharper** [comment]
Amazing work @react-learner!

**Comment by fharper** [comment]
Everyone agreed on our internal company meeting on December 14

**Comment by curquiza** [comment]
As I mentioned during the meeting (and if I remember well Tommy talked about changing this point), I don't really agree/understand the `Discover` sub-section in the `Create` section if it contains pages like "How does MeiliSearch compare with ElasticSearch and Algolia?" or "What does being Open-Source mean to us?" 🙂
Pretty sure @react-learner is aware of it, but I wanted to write it down 😇

**Comment by fharper** [comment]
Actually, we all agree to move forward ([disagree and commit](https://en.wikipedia.org/wiki/Disagree_and_commit)): it's important because we need to find the right balance between discussing and making things happen. I'm sure @react-learner will explain a bit more the structure he decided if it was not clear. Also, we will probably write a blog post about the thinking of the restructuration to help other startups have better documentation, so that will be helpful to understand better.

**Comment by react-learner** [comment]
> As I mentioned during the meeting (and if I remember well Tommy talked about changing this point), I don't really agree/understand the `Discover` sub-section in the `Create` section if it contains pages like "How does MeiliSearch compare with ElasticSearch and Algolia?" or "What does being Open-Source mean to us?" 🙂
> Pretty sure @react-learner is aware of it, but I wanted to write it down 😇

Thanks for the reminder @curquiza ! I'll replace those examples in the proposal. 

In terms of the actual implementation (now in progress!), I may only include the `How To` subcategory, which will contain repeatable cookbooks/recipes that solve specific problems. We don't have a lot of content for a `Discover` subcategory right now (I believe the name `Inspire` was also suggested). In general, it's obvious that `Create` is the broadest category—`Learn` and `Reference` at least come with clear expectations of the kind of content within. It's nice to have one category that can include lots of different types of content, but can also become confusing, so we'll have to see which side it falls on.
