### ISSUE TITLE
Missing server requirements

### ISSUE THREAD

**Issue by emulienfou** [meilisearch/documentation#639]
@curquiza seems I'm the only one having some difficulties to find the **server requirements** for Meilisearch and wanted to relaunch this discussion.

I think the current documentation has something missing.
* First of all, there is no server requirements section on the documentation. We currently don't know which Linux is supported (Debian,Red Hat,CentOs,...), what are the exact requirements (minimum disk space, architecture, ...)
* Secondly, seems there is on GitHub releases page packages for Linux (amd64, armv8), MacOs and Windows available, but documentation did not make references to Mac and Windows.

> Event if I found this page: https://docs.meilisearch.com/running-production/#get-your-meilisearch-ready-for-production this information should be put directly in the Installation section I think

**Comment by curquiza** [comment]
Thanks for this issue @emulienfou! Looks like a great addition to our docs indeed!
