### ISSUE TITLE
API FAQ weird 404

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#642]
On the [API home documentation](https://docs.meilisearch.com/references/), the FAQ link at the top is 404 if you CMD + click to open in a new tab. That is weird because the link is correct, it points to https://docs.meilisearch.com/faq/faq.html but if you CMD + Click (or right click, open in new tab) it open https://docs.meilisearch.com/faq/ . This is 404 at first, but have data when refreshing... I tried on Chrome & Brave, and after clearing my cache. Not sure what is happening here!

![image](https://user-images.githubusercontent.com/1170989/102258893-65686600-3edc-11eb-9e9a-21471843d7ba.png)

**Comment by curquiza** [comment]
So weird!
Maybe because it's a permalink: there is the same issue with `How to use HTTP2 and SSL` link on [this page](https://docs.meilisearch.com/resources/howtos/).
But it should not have this behavior!
