### ISSUE TITLE
Errors page inaccessible through browsing

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#658]
The "MeiliSearch Errors" page, which lists and explains error statements, is only accessible through search, not browsing.

In the new docs structure, this page would fit well in the "Reference" section.

**Comment by bidoubiwa** [comment]
I had trouble adding it as a tab. We should look into vuepress dynamic webpages integration in the navigation. Since I created that page dynamically in a plugin.

**Comment by dichotommy** [comment]
Fixed by docs restructure #735
