### ISSUE TITLE
Note on backwards compatibility

### ISSUE THREAD

**Issue by react-learner** [meilisearch/documentation#665]
Add note on backwards compatibility in guides/advanced_guides/installation.md#updating-meilisearch. Other relevant locations in the docs? 
Something like this:
"MeiliSearch is in beta! Backwards compatibility is a planned feature for our official release. For now, you can use the [dumps feature](/guides/advanced_guides/snapshots_and_dumps.md#snapshots) to maintain your database between updates."

Related to [#1152](https://github.com/meilisearch/MeiliSearch/issues/1152)

**Comment by bidoubiwa** [comment]
I dont think there is another fitting place. Maybe in the introduction? 
https://docs.meilisearch.com/guides/introduction/

**Comment by react-learner** [comment]
Fixed by #702
