### ISSUE TITLE
Need tokenizer documentation

### ISSUE THREAD

**Issue by react-learner** [meilisearch/documentation#675]
Now that we are on the cusp of releasing our redone tokenizer (https://github.com/meilisearch/MeiliSearch/pull/1091), it seems like the perfect time to add more robust documentation of how this works "under the hood". I am envisioning a separate docs page dedicated to the tokenizer, which ideally would be ready before the new release.

I would greatly appreciate it if someone on the core team could write a technical description of the tokenizer and either send it to me, or open a PR into the prepare-meilisearch-2021-w1 branch. Once completed, @CaroFG would be able to link it in her v0.18 blog post.

Is this doable?

**Comment by MarinPostma** [comment]
Many has some material, and there is the spec, what else do you need?

**Comment by bidoubiwa** [comment]
This is the spec: https://github.com/meilisearch/specifications/blob/master/text/0001-script-based-tokenizer.md
It technically has everything you want to know, but it is maybe a bit hard to understand for non-rusters.
 
Before you arrive I read it and I called Many to ask some questions about what I did not understand (which was a lot). And he explained it to me very well. I would suggest maybe doing the same.

**Comment by react-learner** [comment]
Okay, I will do my best to write a summary based on the spec (you're right, I don't understand all of it 😂) and the tracking issue (https://github.com/meilisearch/MeiliSearch/issues/624). I assume I'll get some stuff wrong, but I don't really need to understand everything—just the details that could affect users.

**Comment by MarinPostma** [comment]
@react-learner call me if you need to get up to speed

**Comment by bidoubiwa** [comment]
fixed by: #685
