### ISSUE TITLE
Guide: Example of a local and production environment with Docker

### ISSUE THREAD

**Issue by schwamic** [meilisearch/documentation#676]
meili's documentation shows many quick-start possibilities, but only one way of setting up ready for production/"real-life". the current example is well explained, but there are two things to criticise: 
1. the most steps are implemented manually on the server side, so you have to repeat this for every instance 
2. my local environment is not the same where I will run it later

these two problems could be solved very easily with docker. so it would be great if the existing prod tutorial could be reimplemented with docker and some guidance on how to use it for local development as well.

in addition, the topic of cors settings would be interesting. since you can't or don't always want to use the same domain. for me, for example, this is an issue because meili and the frontend run locally under different ports and meili in production is accessible under a subdomain.

**Comment by guimachiavelli** [comment]
I'm inclined to say #1816 has addressed this request. Thoughts, @dichotommy, @maryamsulemani97?

**Comment by maryamsulemani97** [comment]
Agreed. There is a separate issue for [cors settings](https://github.com/meilisearch/documentation/issues/678)

**Comment by curquiza** [comment]
@guimachiavelli should we close this?

**Comment by curquiza** [comment]
Discussed with @guimachiavelli 
Indeed, the work has been done.
Feel free to let us know if something is missing by re-opening a new issue 😊
