### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#680]
Let's be allies and make this change that means a lot.

Here is a [blog post](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main) that explain a little more why it's important, and how to easily do it. It will be a bit more complicated with automation, but we still should do it!

**Comment by react-learner** [comment]
I think this is a good idea, worried about breaking our automation or deploy system though 😬

**Comment by react-learner** [comment]
Is there any risk that it makes contribution more confusing for people who are expecting to push to a master branch?

**Comment by fharper** [comment]
> I think this is a good idea, worried about breaking our automation or deploy system though 😬

I'll check those to be sure it's working well.

**Comment by fharper** [comment]
> Is there any risk that it makes contribution more confusing for people who are expecting to push to a master branch?

No, the principal branch of a repo is the one displayed by default, you can't missed it. Also, since maybe two months, the default branch for new repo created on GitHub is main, not master.
