### ISSUE TITLE
Add section: unofficial MeiliSearch extensions

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#691]
Add a section in the documentation to highlight cool tools/frameworks/extensions/integrations that use MeiliSearch but aren't supported by us?

The question for me is, would this be better on the documentation site or as a highlight series on the blog?

**Comment by fharper** [comment]
Or both! I would love a blog post when we have a new integration or find a new one from our community, but it would be nice to have it somewhere. I focussed on the documentation site, but maybe simply adding a section in the https://github.com/meilisearch/integration-guides repo could do it (with a huge warning that we do not support those). WDYT @curquiza ?

I still think it would be better in the documentation as before checking the mentioned repo, you need to know that this repo exist. My first reflex would be to go in the doc and search for JAVA to know if we have one, so I assume it would be the same for external one we want to promote.

I would also like us to test them to be sure they are not crap before we promote them 😬

**Comment by curquiza** [comment]
I think this is great to put it into https://github.com/meilisearch/integration-guides but also in the docs (if it's ok for you).
Blog posts would be also awesome 😁

**Comment by fharper** [comment]
Would that make sense to extend this to good content like this blog post https://keliris.dev/meiliesearch/ ?

**Comment by curquiza** [comment]
Maybe could it be a separated "Awesome MeiliSearch" WDYT?

**Comment by fharper** [comment]
> I think this is great to put it into https://github.com/meilisearch/integration-guides but also in the docs (if it's ok for you).
> Blog posts would be also awesome 😁

I'm not a fan of duplicating the content, but for this it make sense, since it's mostly links!
