### ISSUE TITLE
Add upgrade guide

### ISSUE THREAD

**Issue by Nick-Mazuk** [meilisearch/documentation#698]
This comes from a [recent Slack thread on upgrading MeiliSearch](https://app.slack.com/client/TPQ39J9F1/CP9DVS1RQ/thread/CP9DVS1RQ-1604847114.240600). I think this would be great to add to the docs, plus Fred said that someone should add the issue. I didn't find one, so thought I'd create one. Feel free to delete if it's a duplicate.

> **BB**
> To prevent unplanned downtime, I wouldn’t use the docker tag latest but a specific version, so you decide when you upgrade.
> 
> If you’re using docker-compose, one way would be to add a new service, in parallel with the same settings and once it is up and indexed (and you verified it’s working), you switch your nginx reverse-proxy rule to go to the new one later delete the old one from your docker-compose config.
> 
> This would temporarily duplicate disk space usage and RAM usage, of course.
If you want a more generalized perspective on that, check out blue-green deployment

**Comment by bidoubiwa** [comment]
@eskombro Could you elaborate?

linked to #1187

**Comment by eskombro** [comment]
This is an answer to that question, which works as a workaround for updating MeiliSearch version until we define an official way to do it or provide an official tool:

https://github.com/meilisearch/MeiliSearch/discussions/1187
