### ISSUE TITLE
Http server version

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#7]
It could be great to refer the documentation to a specific https server version.

**Comment by tpayet** [comment]
There is no official way of handling versioning using vuepress as of today, it seems to be an issue they are working on: [vuejs/vuepress#1018](https://github.com/vuejs/vuepress/issues/1018)

We could handle versioning like [strapi](https://github.com/strapi/strapi/tree/master/docs) but it implies to have multiple directory with a lot of redundant information, in which we will have to update multiple file for the same information.

I think we will handle proper versioning when we will be stable (> 1.0.0) and today we should keep the documentation up to date with the last version published

**Comment by bidoubiwa** [comment]
related to #197

**Comment by guimachiavelli** [comment]
@curquiza is this still relevant and/or different from #197?

**Comment by curquiza** [comment]
@guimachiavelli to be honest I don't remember the context of this issue. I think it's related to #197
I was in meili for 2 months when I opened it! 😂

**Comment by guimachiavelli** [comment]
hmmm…ok. We're trying to trim down duplicate and stale issues, so I'm closing this in favour of #197.

If you ever remember the context and think it's still relevant, please let us know.
