### ISSUE TITLE
Improve Update part of Getting started.

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#701]
A lot of users ask questions about the update system in MeilISearch.
After checking the getting started guide It may be confusing for a new user. 

I think I rewrite should be done. Maybe also adding concrete examples.

For example: 

(image this in all languages)
```javascript
const docProcess = client.index('movies').addDocuments(dataset)
const status = client.index('movies').getUpdateStatus(docProcess.updateId)
```

And then under the above tab, a return example. Explaining that the status will go from `enqueued` to `processing` to `processed` or `failed` in which case an error message will be provided as well.  

```json
{
  "status": "processed",
  "updateId": 1,
  "type": {
    "name": "DocumentsAddition",
    "number": 4
  },
  "duration": 0.076980613,
  "enqueuedAt": "2019-12-07T21:16:09.623944Z",
  "processedAt": "2019-12-07T21:16:09.703509Z"
}
```

This could considerably reduce the big chunk of texts with self-explanatory examples. 

I think this may really improve comprehension of the `update` system (until we change the name for a more intuitive one).

**Comment by maryamsulemani97** [comment]
closing as we didn't go into detail on task status in the new getting started. The workflow is explained in the [Asynchronous operations page ](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html)
