### ISSUE TITLE
Test versioning plugin for Vuepress

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#705]

**Comment by bidoubiwa** [comment]
What do you mean by that? Do you want to keep a documentation version for every MeiliSearch release?
Like quentin described in this issue : https://github.com/meilisearch/documentation/issues/197 ?

**Comment by react-learner** [comment]
@bidoubiwa Yes, exactly! Versioning is not super helpful right now, but it is a must-have for the documentation after we hit v1.0.

Before we seriously consider switching to Docusaurus or a similar tool, I'd like to test out the Vuepress versioning plugin I found. Here's the repo: https://github.com/appcelerator/docs-devkit/tree/develop/packages/vuepress/vuepress-plugin-versioning

**Comment by bidoubiwa** [comment]
I looked at it in the past. It has not a lot of star, doesn't look to be maintained a lot and is hard to install and configurate. Except from this option I did not find any other plugin. 
The other solution would be to create an in-house option but this should require some thought. It is not clear how we can manage that the most efficiently possible. 
- Should we have multiple directories with copies of the documentation each supporting a specific version. Considering the fact that 99% of the content between dir's would be the same?
- Should we look for a smart system where only the changed files would be in a sub-folder and they would be auto-completed with the main folder?
- Or any more complex system?

Does Docusaurus provide an easy solution for that?

**Comment by bidoubiwa** [comment]
@tpayet @qdequele Could you give your opinion on the matter?

**Comment by react-learner** [comment]
> Does Docusaurus provide an easy solution for that?

@bidoubiwa Yep, it is one of their main features. https://docusaurus.io/docs/en/versioning

**Comment by qdequele** [comment]
My proposition is: we will certainly change the documentation render engine with the new version on which the designer and the front end developer will work. We will certainly use Docusaurus. So, during the beta of the v1, we will also have the ability to test the beta of the new documentation. We could use a different subdomain like beta-docs.meilisearch.com. Like Docusaurus already have a versioning feature, after this change, we will be able to use it.

**Comment by react-learner** [comment]
We concluded that Appcelerator's versioning plugin for VuePress does not have enough active maintainers or support for us to use it comfortably with our docs. Instead, we will go forward with Docusaurus.
