### ISSUE TITLE
Add a limitation on the number of words in the query

### ISSUE THREAD

**Issue by qdequele** [meilisearch/documentation#724]
Until now, the query parser in the search query had no limits in terms of the maximum number of words it could contain. When the [PR](https://github.com/meilisearch/MeiliSearch/pull/1174) will be merged into the new release (v0.19.0), then this limit will be 10 words. 

The explanation of why we limit the number of words in the query is that the more words we put in the query, the longer the search time is. You can easily exceed one second with very long queries. 

An example of this change could be: 

```json
{
    "q": "Among actors, the role of Hamlet, Prince of Denmark, is considered the jewel in the crown of a triumphant theatrical career."
}
```

Even if this query doesn't really make sense, because MeiliSearch is not made for this kind of usage, the research's used words will be only the 10 first. So "Among actors, the role of Hamlet, Prince of Denmark, is". 

What needs to change. 
- In the [query guide](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#query-q) we should put a small warning to specify that now the maximum limit of words taken into account is 10. If the query has more than 10 words, only the first 10 words will be considered. 
- We can also add few words in the [know limitations](https://docs.meilisearch.com/guides/advanced_guides/known_limitations.html) part.

**Comment by qdequele** [comment]
@react-learner This one is in preparation, could normally be merged today. I will keep you up to date on the progress of the RP. Happy to write directly the documentation if you approve the part we need to add changes. Otherwise delighted to reread the doc.

**Comment by react-learner** [comment]
I know it was proposed that users be able to alter/set this limit themselves—did this feature make it into the release, or no?

**Comment by qdequele** [comment]
> feature

Nop
