### ISSUE TITLE
Add an explanation about synonyms normalization

### ISSUE THREAD

**Issue by qdequele** [meilisearch/documentation#725]
In a new [PR](https://github.com/meilisearch/MeiliSearch/pull/1184), we changed the way we handle synonyms by normalizing them before indexing them, so they are not case sensitive anymore. Then normalization also involves deunicoding in some cases, such as accents, so `été` and `ete` are considered equivalent in a search for synonyms.

We could add a word on that change in the [synonyms guide](https://docs.meilisearch.com/guides/advanced_guides/synonyms.html#the-one-way-association). 

Two things changes: 
- All synonyms are now lowercased. 
- All synonyms are now deunidecoded.

**Comment by qdequele** [comment]
@react-learner This one is in preparation, could normally be merged today. I will keep you up to date on the progress of the RP. Happy to write directly the documentation if you approve the part we need to add changes. Otherwise delighted to reread the doc.

**Comment by react-learner** [comment]
Thanks Quentin. This is part of the next release, right?

**Comment by qdequele** [comment]
Yes, If you need help, or if you need me to write something don't hesitate.
