### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#73]
The Readme is quite weird, especially the Open-source section 😂
- the links "Star" and "Fork" are not visible because like the same sentence
- there is an HTML tag
- ...

And a visible link to MeiliSearch repo could be great, no? 😀

**Comment by bidoubiwa** [comment]
The github link is on the top right corner of the screen but i added it on the PR #79

I don't see the problem with start and fork neither do i see the HTML tag.
