### ISSUE TITLE
Create redirects from old pages to new ones

### ISSUE THREAD

**Issue by react-learner** [meilisearch/documentation#739]
Links on most MeiliSearch resources have been fixed to point to the new documentation paths, however links from outside our ecosystem will remain broken until we create a redirect.

Will try to solve this problem w/ Netlify.

**Comment by bidoubiwa** [comment]
Vuepress has an option for that: 

https://github.com/vuejs/vuepress/issues/239

**Comment by bidoubiwa** [comment]
Which would be simply here for us: 

<img width="425" alt="Screenshot 2021-02-04 at 10 16 32" src="https://user-images.githubusercontent.com/33010418/106871029-12d44a80-66d2-11eb-930e-1bde725af1d4.png">

And then you add it like this: 

<img width="399" alt="Screenshot 2021-02-04 at 10 16 05" src="https://user-images.githubusercontent.com/33010418/106871061-1962c200-66d2-11eb-97ed-34b683820691.png">

**Comment by react-learner** [comment]
Thanks @bidoubiwa ! 💓

**Comment by react-learner** [comment]
@bidoubiwa After doing some further research, not sure that this will solve the problem.

As an example, try going to https://docs.meilisearch.com/error/. You will get a 404, but if you refresh, the correct page will load. When you first visit the page, the redirect triggers and changes the URL to https://docs.meilisearch.com/errors/ (the correct link). However, the correct page does not render so users still see the 404. See: https://github.com/vuejs/vuepress/issues/160
