### ISSUE TITLE
Discussion: Graphic design tasks

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#753]
Let's brainstorm areas in the docs that might be improved by some graphic design.

**Comment by react-learner** [comment]
- Core concepts: would be nice to have an image that graphically represents the relationship between documents, indexes, and the database.

**Comment by fharper** [comment]
- update the Movie animated gif at https://docs.meilisearch.com/learn/tutorials/getting_started.html#web-interface once the movie demo is updated.

**Comment by guimachiavelli** [comment]
I am closing this because it isn't really an actionable issue and is not functioning as a discussion hub at the moment.
