### ISSUE TITLE
Add a graphic in the Core Concepts page

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#767]
This page is a bit empty, maybe we could make a graphic of the [core concept](https://docs.meilisearch.com/learn/core_concepts/)?

![image](https://user-images.githubusercontent.com/1170989/107992770-62a2f380-6fa7-11eb-9b2a-5a9e6c620cb9.png)

**Comment by maryamsulemani97** [comment]
closing as we no longer have this README
