### ISSUE TITLE
Change Faceted Search examples to use MeiliSearch mini dashboard

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#776]
The [Faceted Search documentation](https://docs.meilisearch.com/reference/features/faceted_search.html#filters-or-facets) was created before we have a release with that feature, so we used Amazon examples. It's more than time that we change that for examples with MeiliSearch.

![image](https://user-images.githubusercontent.com/1170989/108112774-9001a700-7064-11eb-93c5-229bcc894cdf.png)

**Comment by fharper** [comment]
block by https://github.com/meilisearch/devrel/issues/134

**Comment by maryamsulemani97** [comment]
closing this for #600
