### ISSUE TITLE
Ensure examples use attributes in the movies.json

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#779]
In some examples we are using attributes that does not exist in the mobies.json file we provide for tests. Either updates the JSON files with all needed fiels, or update the examples. I assume it will be the former. The idea is to be sure that a new user will be able to do all our code examples with the dataset provided (except facets).

![image](https://user-images.githubusercontent.com/1170989/108115179-c4c32d80-7067-11eb-80d7-f6cb4eb8c498.png)

**Comment by bidoubiwa** [comment]
See related conversation: https://github.com/meilisearch/documentation/issues/493

**Comment by fharper** [comment]
Duplicate of #493
