### ISSUE TITLE
Add the JSON returned for the distinct attribute example

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#782]
Add the JSON returned for the [distinct attribute example](https://docs.meilisearch.com/reference/features/distinct.html#example)

![image](https://user-images.githubusercontent.com/1170989/108117408-e4a82080-706a-11eb-964b-ed9d7f771d51.png)

**Comment by CaroFG** [comment]
So I tested it. The result is the following:

**Comment by CaroFG** [comment]
It would be very cool if it could also send info about how many products with the same porduct_id there are and info about their differences. So one could know, this jacket also exists in black and blue. But I don't know if it is feasible.

**Comment by fharper** [comment]
> So I tested it. The result is the following:

Feel free to do a PR :)

**Comment by fharper** [comment]
> But I don't know if it is feasible.

I don't know either. Check with the core team.
