### ISSUE TITLE
Document Meilisearch API with OpenAPI

### ISSUE THREAD

**Issue by JacobLey** [meilisearch/documentation#798]
[OpenAPI](https://swagger.io/specification/) would provide a language-agnostic, machine-friendly way of documenting the Meilisearch API.

Existing documentation/design is RESTful but requires specific client libraries (or cURL) to actually access the code. With tools like [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) and [Swagger UI](https://www.npmjs.com/package/swagger-ui) users can test code in-browser or with the language/framework of their choice.

This would be entirely additive, no existing documentation would need to change, except with perhaps an extra link pointing to the OpenAPI document.

I'm happy to take a first swing at writing the OpenAPI doc.

Opening this issue mainly as a means of discussion prior to opening that PR.

**Comment by fharper** [comment]
Awesome, I didn't remember the changes needed, but Swagger was one of the thing I mention when I started, so I'm all about OpenAPI!

@react-learner WDYT? As Jacob mentioned, we would just need to add an additional tab for API examples in the doc, and if I'm not wrong, something in the header so tools can easily understand our docs have Open API available.

I could review the PR if you prefer.

Thanks a lot @JacobLey !

**Comment by JacobLey** [comment]
<img width="787" alt="Screen Shot 2021-02-22 at 1 20 10 PM" src="https://user-images.githubusercontent.com/37151850/108771566-b914b280-7510-11eb-8860-16db017b663b.png">
You are referring to this `CodeSamples` component? OpenAPI isn't itself an sdk/language so I'm not really sure what would go there...
Perhaps just a link to that endpoint on a SwaggerUI page?

I'm not aware of any
> header so tools can easily understand our docs have Open API available
but if that is a thing it is probably easy to implement. If someone could point me where to look for info about that I can include in this PR as well

**Comment by sanders41** [comment]
@JacobLey the idea in the end would be to have a page like [this](https://editor.swagger.io/?_ga=2.142152753.2019979058.1614031623-493194483.1613873351) (right side) documenting the API correct? If yes would it make sense to have another link [here](https://docs.meilisearch.com/reference/) on the left nav bar linking to the OpenAPI page?

**Comment by JacobLey** [comment]
Ah yes that kind of header, yes that sounds about right
