### ISSUE TITLE
Add to FAQ: browser URL sync

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#807]
There is a way to achieve browser URL sync with InstantSearch. This should be documented and added to the FAQ.

**What is browser URL sync?** Essentially, your browser URL updates in real-time to reflect your search query and other parameters. This allows users to save or share a specific set of search results with ease. It can also be helpful for SEO.

**Comment by guimachiavelli** [comment]
I don't think this belongs on the Meilisearch docs as it relates to a plugin, not the engine itself.

If we really want to give `instant-meilisearch` some love, I think the only reasonable place would be in a new cookbook.

**Comment by guimachiavelli** [comment]
@bidoubiwa: what do you think about this? Is this documented in the `instant-meilisearch` repo? Are there other places better suited for this info?

**Comment by bidoubiwa** [comment]
I'm not sure I understand correctly. If it is what I think it is, it [is supported by `instantsearch`](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/).

> I don't think this belongs on the Meilisearch docs as it relates to a plugin, not the engine itself.

I agree, it is also not related to instant-meilisearcu but to instantsearch.

**Comment by guimachiavelli** [comment]
@dichotommy, can you confirm @bidoubiwa has understood your issue correctly? If so, it seems neither the docs nor `instant-meilisearch` are good fits for this content. Do you have any further thoughts regarding this issue's original goals?

**Comment by guimachiavelli** [comment]
Ok, this sounds plenty of info to begin writing a blog post. @meilisearch/devrel-team, I have added this to the ideas section of the post forecast.
