### ISSUE TITLE
Make default search limit (20 results) more prominent in the docs

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#809]
Questions like this one: 

<img width="689" alt="Capture d’écran 2021-02-25 à 18 36 35" src="https://user-images.githubusercontent.com/48251481/109193269-7cf38300-7798-11eb-8c2c-0d2c401f17dd.png">

**Comment by react-learner** [comment]
Can't you use the [limit parameter](https://docs.meilisearch.com/reference/features/search_parameters.html#limit) for this?

**Comment by CaroFG** [comment]
Yes, you can use the limit parameter and raise it. But it's there by default. And we may want to make it **obvious** that you won't get all the results for your query if you do not raise it.

**Comment by react-learner** [comment]
Great point @CaroFG , sounds like something that should be mentioned in [Getting Started](https://docs.meilisearch.com/learn/tutorials/getting_started.html).

**Comment by dichotommy** [comment]
Closed by #1228
