### ISSUE TITLE
Small change to FAQ Recommended Requirements

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#818]
#772 adds an FAQ entry that covers memory + storage use. We have a list of factors that are known to have a high impact on memory use + database size; ideally, this list should be in order of impact. That way users can have a better idea of how to efficiently reduce hardware usage.

**Comment by react-learner** [comment]
This is not possible right now, but should still make some changes to this FAQ answer.

There are only two things that take lots of RAM / cause RAM spikes (since both cause indexing):
- Adding documents
- Updating settings
Everything else on the list is mainly affecting database size.

**Comment by dichotommy** [comment]
Fixed by #843
