### ISSUE TITLE
Clarify that POST search route is default

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#821]
POST is the preferred method for search (because it has preflight caching for CORS). ~~Page should only display POST reference info~~We should strongly push users to use the POST route unless they have specific needs that are only accomplished w/ the GET route.

**Comment by maryamsulemani97** [comment]
Closing as this is mentioned in the [docs](https://docs.meilisearch.com/reference/api/search.html#search-in-an-index-with-post-route)
