### ISSUE TITLE
Add details to Dumps API and Feature References

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#822]
API reference for [getting a dump status](https://docs.meilisearch.com/reference/api/dump.html#get-dump-status) could use some more detailed information:
- What errors can cause a dump process to be `failed`?
- Should be noted that the dump queue is separate from the update queue.
- If using a single CPU, is the dump queue prioritized over the regular update queue? ~For example, if a document addition request is in progress, will it wait for that process to finish before starting the dump creation process?~
  - Yes, when you trigger a dump creation process (`POST /dumps`) the update queue is immediately paused and the dump begins processing.
  - While a dump or snapshot is processing, no write operations can occur on the database.
~- Is dump creation multithreaded? (It is [reentrant](https://github.com/meilisearch/MeiliSearch/pull/1128).)~
- It should also be made explicit that a dump `uid` *is* the timestamp at which the dump was triggered.

For the Dumps feature ref (and possibly also API ref):
- ~~Creating a dump calls the GET documents endpoint. That means if fields are not displayed, they will not be included in the dump. Set all fields as displayedAttributes before creating a dump if you want to avoid data loss.~~ **Fixed by v0.21**

~~Also, the fact that there's no `enqueued` status (equivalent is `in_progress`) implies that there is no queue and only a single dump can be performed at a time. Should this be changed?~~ There is no queue; if you attempt to call the dump creation endpoint while a dump is in progress, it will trigger [an error](https://docs.meilisearch.com/errors/#dump_already_in_progress).

**Comment by maryamsulemani97** [comment]
closing as it was resolved in PR #1240
