### ISSUE TITLE
Consolidate placeholder search info

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#823]
Placeholder search information is generally scarce in the docs. It is mentioned in the [features list](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html#placeholder-search) and twice, very briefly, in the [search parameters feature reference](https://docs.meilisearch.com/reference/features/search_parameters.html#placeholder-search) and [search API Reference](https://docs.meilisearch.com/reference/api/search.html#search-in-an-index-with-get-route) (very easy to miss 😬).
- In API reference, the description of placeholder search should be more prominent.
- In features list, the description of placeholder search should be more concise, with links to the reference.
- In search parameters feature reference, the explanation should be more thorough, including:
  - **Default ranking rules do not apply to placeholder search.** Only custom rules (asc or desc sort) and filters.

**Comment by guimachiavelli** [comment]
The search parameters feature reference has been improved since this issue was created, but could possibly still benefit from a more explicit statement regarding default ranking rules.

**Comment by maryamsulemani97** [comment]
resolved in PR #1151
