### ISSUE TITLE
Update security information

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#828]
The keys + authentication sections can use an update. Specify that master key can be a string of any length.

Tools for generating master keys:
- 1password
- `shasum`
- [`uuidgen`](https://www.digitalocean.com/community/tutorials/workflow-command-line-basics-generating-uuids)
- https://randomkeygen.com/
- [`openssl rand`](https://www.openssl.org/docs/man1.0.2/man1/rand.html)

Some cybersecurity basics:
- Recommended number of bits of entropy (256 minimum?)

Related to #662

**Comment by bidoubiwa** [comment]
Maybe avoid 1password as it is a closed-source and not a free tool. 
Everything else tip top
