### ISSUE TITLE
Fix moment bug

### ISSUE THREAD

**Issue by react-learner** [meilisearch/documentation#830]
The module `moment` is causing some errors when running the docs' yarn scripts. Try `yarn check-links` on a fresh clone to reproduce.

**Comment by bidoubiwa** [comment]
I cannot reproduce :(

**Comment by react-learner** [comment]
@bidoubiwa  v15.4.0 That's good if you can't reproduce it! Maybe it was just an issue with my local copy.

**Comment by react-learner** [comment]
Closing this unless/until the error re-surfaces.
