### ISSUE TITLE
Standardize searchable attributes formatting

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#831]
The searchable attributes list is sometimes referred to as `searchableAttributes` in the documentation, because that's the name of the field in the settings object. Other times it's referred to as "the searchable attributes list". On the other hand, the route itself is searchable-attributes. We should be more consistent and intentional with these spellings.

Need to take a closer look at the pages in question and ensure that the correct format is used in the appropriate place.

**Comment by maryamsulemani97** [comment]
Just to clarify; we can't say something like "updating the `searchableAttributes` list?" It's either:
- updating the searchable attributes list
- updating `searchableAttributes`
