### ISSUE TITLE
Specify that it's not possible to filter documents by null fields

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#837]
I have modified the movie 'Shazam' in the movies dataset, I've set the genres to null.
It's currently impossible to make this kind of filtered search:

```
curl 'http://localhost:7700/indexes/movies/search' \
--data '{ "q": "Shaz", "filters": "NOT genres = \"null\"" }'
```

The first result returned it's still 'Shazam'.

**Comment by dichotommy** [comment]
Confirmed in https://github.com/meilisearch/MeiliSearch/issues/972
