### ISSUE TITLE
Documentation around How to Handle Dates / Best Practices

### ISSUE THREAD

**Issue by cryptoroo** [meilisearch/documentation#840]
**Is your feature request related to a problem? Please describe.**
Having used other search engines I am used to have a datetime type. 
Usually ISO-8601 is the preferred format. 
I haven't seen any recommendations on how to deal with dates in MeiliSearch. 
It would be useful to understand what your thoughts as the developers of the product are around this. 

**Describe the solution you'd like**
Some clear examples on how you can use dates for search filters but also for facets. 
Any roadmaps for including native date parsing? 

**Describe alternatives you've considered**
The cleanest solution to date has been to use Linux Timestamps as they are Integers which are very easily represented in MeiliSearch

**Comment by react-learner** [comment]
This is indeed something that should be documented, ideally in a tutorial or guide. Thanks for bringing it to our attention, @cryptoroo !

**Comment by lukasa1993** [comment]
so timestamps are only eay forward ? no datetime support timezones and stuff ?

**Comment by curquiza** [comment]
For the moment only timestamps are handle.

I don't think the datetime support is in our current roadmap. However we have a public roadmap where our users can share their ideas and their needs. It would be awesome if you can add your idea so that other users will upvote it if they need it as well.
https://roadmap.meilisearch.com/tabs/5-ideas

**Comment by alfonsrv** [comment]
Not sure how much overhead this would add to the search speed, but being able to declare a data-type for each `filterableAttributes` could be one idea.

**Comment by maryamsulemani97** [comment]
fixed in #1917

**Comment by cryptoroo** [comment]
thanks all. Unix timestamps are absolutely fine :D
