### ISSUE TITLE
Add relevancy in-depth explanation of the algorithm and the default ranking rules into the documentation

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#850]
In core concepts [relevancy section](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#relevancy), the sentence `For a more in-depth explanation of the algorithm and the default ranking rules, see this issue` is pointing to the [issue](https://github.com/meilisearch/MeiliSearch/issues/358). Let's add an item in the "under the hood" section, or anywhere else, that have the same explanation so we don't point on the issue.

**Comment by dichotommy** [comment]
This is the issue that was previously referenced in `relevancy.md`: https://github.com/meilisearch/MeiliSearch/issues/358
It has since been removed, but it would still be nice to create an "Under the Hood" page that goes more in-depth about the implementation of ranking rules.
