### ISSUE TITLE
Change relevancy examples images to text

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#851]
Change [relevancy examples](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#examples) images to text so it's accessible for people with vision impairment and right now, the contrast for bold words isn't good for colorblind folks.

**Comment by guimachiavelli** [comment]
Changing these images to text would negatively impact users—they're gifs illustrating a process already described in the accompanying text. Describing these gifs would result in content duplication.

We could improve the contrast of the images to address some of the accessibility concerns, but it's unclear where the original interface is located, and recreating it would use resources better spent elsewhere.
