### ISSUE TITLE
Clarify attribute ranking order example

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#858]
In the [attribute ranking order example](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#example-2) it isn't clear that the impact of the rule is determined by ITS position in the ranking-rules list, e.g. if attribute is last in the ranking rules list, then attribute ranking order will have effectively no impact.

In other words, we need to draw a clearer connection between the "attribute" ranking-rule and the concept of the attribute ranking order.

**Comment by maryamsulemani97** [comment]
closed in PR #1239
