### ISSUE TITLE
Improve coherence between dataset and examples

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#860]
Currently, the documentation provides examples that mention fields not present in the dataset available for download, like `director` or `rating`.

You can see it one the faceted search section: https://docs.meilisearch.com/reference/features/faceted_search.html#setting-up-facets or in the filtering one: https://docs.meilisearch.com/reference/features/filtering.html#examples

We could either add those fields to the dataset or replace the examples.

**Comment by dichotommy** [comment]
Related to https://github.com/meilisearch/devrel/issues/134

**Comment by guimachiavelli** [comment]
Adding to the list of examples that must be fixed: /reference/features/search_parameters.md

Some of the examples will be fixed by #1016, but I am sure that at least one of them still refers to the `director` field.

**Comment by bidoubiwa** [comment]
Some problems with this proposition: 
- Some examples do not fit well with the dataset. And thus do not serve well the explanation
- Adding more fields to the dataset will make the dataset bigger, in term of size. We want to avoid asking the user to download a to big dataset

**Comment by guimachiavelli** [comment]
> Adding more fields to the dataset will make the dataset bigger, in term of size. We want to avoid asking the user to download a to big dataset

I missed the suggestion regarding expanding the dataset. I agree we should not add fields — if anything, I'd prefer `movies.json` to be smaller.

Perhaps we should only reference specific datasets in guides and tutorials (e.g. quick start, how-to articles, etc) and dissociate our examples from the `movies.json` dataset in things like the API reference?
