### ISSUE TITLE
master key setup

### ISSUE THREAD

**Issue by ustenko** [meilisearch/documentation#870]
hi,
i read https://docs.meilisearch.com/reference/features/authentication.html#master-key
i can't find in docs how to setup master key and where it located
can u provide some tutorial to generate master key?
i'm using laravel+docker

**Comment by ustenko** [comment]
ok, thanks
one more question
i'm using laravel sail to run docker
this is my docker-compose.yml file
what i need to add to this file to send master key

`# For more information: https://laravel.com/docs/sail
version: '3'
services:
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
        build:
          context: .
          args:
            - master-key=masterKey
              
networks:
    sail:
        driver: bridge
volumes:
    sailmeilisearch:
        driver: local
`

**Comment by CaroFG** [comment]
You just need to add `environment` and lits the environment variables you'd like to use, like so:

`version: '3'
services:
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
        environment:
             - MEILI_MASTER_KEY: "masterKey"
networks:
    sail:
        driver: bridge
volumes:
    sailmeilisearch:
        driver: local`

**Comment by ustenko** [comment]
> You just need to add `environment` under your meilisearch service and list the environment variables you'd like to use, like so:
> 
> ```
> version: '3'
> services:
>     meilisearch:
>         image: 'getmeili/meilisearch:latest'
>         ports:
>             - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
>         volumes:
>             - 'sailmeilisearch:/data.ms'
>         networks:
>             - sail
>         environment:
>              - MEILI_MASTER_KEY: "masterKey"
> networks:
>     sail:
>         driver: bridge
> volumes:
>     sailmeilisearch:
>         driver: local
> ```
> 
> [Here](https://docs.docker.com/compose/environment-variables/) is the Docker compose documentation on env variables, in case you need more info 🙂

**Comment by ustenko** [comment]
@CaroFG thanks for your help
