### ISSUE TITLE
Add comparison of implicit vs. explicit index creation

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#873]
In the main concept guide, we should definitely add an implicit vs. explicit comparison section similar to [MongoDB's](https://docs.mongodb.com/manual/core/databases-and-collections/#create-a-collection).

- Implicit: default option, simple, less code.
- Explicit: much more error-proof. This is because implicit index creation is actually two actions (1. Create index, 2. Add documents to said index) tied to one command (add documents). Unlike all other actions in MeiliSearch which are atomic, it is possible for only one of these two actions to complete successfully (index is created, but documents are not added). This can cause errors or missing documents.

Inspired by #583

**Comment by guimachiavelli** [comment]
"Merging" this issue with #1043. Relevant bits of the discussion there:

> In the documents core concept it would be interesting to explain that when you add documents in an index that does not exist, the index will be created automatically.

> In [`indexes` core concept](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-creation) it could be an idea to talk about the implicit index creation. Apparently not only `POST /documents` creates the index in the background. 

> the [index creation](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-creation) part seems like a good place.
