### ISSUE TITLE
Add batching documents as a best practice

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#875]
On large dataset, it is way better to batch documents in smaller chunks. This reduces indexing time and avoid RAM spikes (as all documents are saved on RAM during indexation - I think).

It is [briefly mentioned in the docs](https://docs.meilisearch.com/learn/core_concepts/documents.html#upload)

> MeiliSearch uses a lot of RAM when indexing documents. Be aware of your RAM availability as you increase the size of your batch as this could cause MeiliSearch to crash.

But it should be a more visible information!

**Comment by curquiza** [comment]
Ask the users to batch their documents is a tip the Meili team repeat multiple time a week. This is indeed not obvious to everyone 🙂 
Make the document batching more obvious in the learning process of the users would be definitely helpful.
Cf https://github.com/meilisearch/MeiliSearch/issues/1256#issuecomment-829371579

**Comment by Boscop** [comment]
What's the optimal chunk size when batching?

**Comment by curquiza** [comment]
It depends on:
- the size of your documents. If you have a lot of attributes or if your attribute values are big, you should push fewer documents by batch. 
- your machine: the bigger the batches are, the more performant MeiliSearch is. But if your batches are too big and the RAM capacity of your machine too small, you can use too many memory and the OS will kill MeiliSearch.

The default payload size of MeiliSearch is 100Mb, which is more than ok to push in one batch the [movie.json dataset](https://raw.githubusercontent.com/meilisearch/MeiliSearch/master/datasets/movies/movies.json) for example. But if you want to want to increase this default payloard size, you can by passing [this argument](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size) when launching MeiliSearch.

**Comment by Boscop** [comment]
I'm worried that it'll use too much RAM and crash, and then maybe leave the db in a corrupt state.
The payload size is the size of the json file, right? (Not the indexing RAM usage.)
Is there any guaranteed upper bound that for a payload size of 100 MB, how much RAM would it maximally use?
(I want to index millions of small docs on my laptop which is already always swapping RAM to disk.)

**Comment by curquiza** [comment]
> The payload size is the size of the json file

Yes 

> Is there any guaranteed upper bound that for a payload size of 100 MB, how much RAM would it maximally use?

We cannot guess it depends on too many metrics: see https://docs.meilisearch.com/faq/#what-are-the-recommended-requirements-for-hosting-a-meilisearch-instance

>  (I want to index millions of small docs on my laptop which is already always swapping RAM to disk.)

The current version of MeiliSearch is not able to index millions of documents. The core team is working on a new search engine that will handle this amount of data. We hope we can release a RC version by the end of June

**Comment by react-learner** [comment]
Related to #824 , #328

**Comment by gmourier** [comment]
We are currently thinking about a way to do it automatically and transparently for the users at the MeiliSearch level. Maybe we will have less need to document the batching on the client-side if this behavior is implemented.  https://github.com/meilisearch/product/issues/69

**Comment by dichotommy** [comment]
Downgraded in priority due to possibility of auto-batching.

**Comment by maryamsulemani97** [comment]
closing as we now have [Auto-batching ](https://docs.meilisearch.com/learn/experimental/auto-batching.html#enable-auto-batching)
