### ISSUE TITLE
Update status (and dumps status)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#877]
There are currently 2 actions that have status:
- dumps
- updates

But, they don't have similar behaviors.

Dumps status are:
- `in_progress`
- `done`
- `failed`

(cf in codebase: https://github.com/meilisearch/MeiliSearch/blob/c984fa1071fa6dc42344253490180b448314f729/meilisearch-http/src/dump.rs#L196-L200)

Update status are:
- `enqueued`
- `processed`
- `failed`

(cf in codebase: https://github.com/meilisearch/MeiliSearch/blob/c984fa1071fa6dc42344253490180b448314f729/meilisearch-core/src/update/mod.rs#L163-L176)

Cleared list the different status in the docs might be helpful 😄

**Comment by bidoubiwa** [comment]
This part of the documentation is also impacted by this information: 
https://docs.meilisearch.com/learn/advanced/asynchronous_updates.html#terminate-meilisearch-while-a-task-is-processing

**Comment by react-learner** [comment]
Since this will be affected by v0.21 ([adds an update status](https://github.com/meilisearch/transplant/issues/107), and may change dump status names), this change to the docs will probably be made as part of the [preparation for v0.21](#931 ) in order to avoid doing the same work twice.
