### ISSUE TITLE
Improve search experience on the documentation

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/documentation#879]
I was using our doc, and I thought it would be cool if we made the search more centric to the experience of browsing the reference, the two things that came to my mind were:
- 1) focus on the search bar as soon as you enter the reference, so you can start typing right away,
- 2) Have the search bar more present in the main page, maybe even with a CTA to invite the user to try the search feature.
- 
My idea is really to push forward "search focused browsing", and display our product at the same time :)

**Comment by guimachiavelli** [comment]
@maryamsulemani97, a suggestion: you may also want to look into `tabIndex`. I believe we could use it to make it so the search bar is the first thing a browsers focusses on when users are tabbing through content without forcing focus on load.

**Comment by guimachiavelli** [comment]
This issue is now the responsibility of an external team and will be monitored in their preferred platform.
