### ISSUE TITLE
Update style for quick start css

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#882]
Quick start guide has a section called Integrate with Your Project which uses HTML and a css stylesheet to create a simple instant-search interface.

Once the browser search interface (aka `web interface` in the docs) has been redone, we should update this section of the docs using that CSS file (will make it prettier, plus allow users to view facets).

Will arrive with new engine (est. Summer 2021)

**Comment by maryamsulemani97** [comment]
@dichotommy, do we plan on doing this?

**Comment by bidoubiwa** [comment]
Current `css` is hosted here https://github.com/meilisearch/instant-meilisearch/tree/main/templates

**Comment by guimachiavelli** [comment]
As far as I can see, this was solved during the quick start review earlier this year. CSS file linked on the tutorial is exactly the same as the one on the `instant-meilisearch's latest release.
