### ISSUE TITLE
Add information about fieldDistribution

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#886]
There is currently no documentation on what fieldDistribution means when calling the stats routes. We don't know if it's dependent or not on the searchableAttributes : https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1616765363060700

**Comment by react-learner** [comment]
A more detailed explanation of fieldDistribution should be added in the [Stats API reference](https://docs.meilisearch.com/reference/api/stats.html).

We still need further clarification from the Core team (@MarinPostma @LegendreM ): is fieldDistribution affected in any way by searchableAttributes or displayedAttributes?

**Comment by maryamsulemani97** [comment]
Fixed in PR #1250
