### ISSUE TITLE
Inconsistency in snapshots documentation

### ISSUE THREAD

**Issue by regzon** [meilisearch/documentation#895]
[Documentation about snapshots](https://docs.meilisearch.com/reference/features/snapshots.html#starting-from-a-snapshot) states that there is an env variable (called `MEILI_IMPORT_SNAPSHOT`) that allows starting the server from the snapshot, but I didn't find this option on the [configuration page](https://docs.meilisearch.com/reference/features/configuration.html#options) or in the source code. This functionality can be only controlled via the CLI option, but the "Snapshots" page states that this can be done via the env variable (which is not true).

**Comment by curquiza** [comment]
Related to https://github.com/meilisearch/MeiliSearch/issues/1323

**Comment by react-learner** [comment]
Nice catch! The env variable was removed recently and we must have missed this spot in the docs. Many thanks @regzon 🚀
