### ISSUE TITLE
Create telemetry page

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#908]
Info on telemetry/analytics is currently located here: https://docs.meilisearch.com/reference/features/configuration.html#analytics

It should be moved to its own page with more detail on what the information is used for, the fact that it is GDPR compliant, the opt-in procedure, etc.

Will probably be added to the new docs website (Docusaurus), not the current one (VuePress).

**Comment by gmourier** [comment]
Issue mentioned in https://github.com/meilisearch/specifications/pull/34  🙏
