### ISSUE TITLE
Criteria names changed with the engine rewritte

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/documentation#91]
When I rewrote the core engine algorithm (i.e. `v0.8.5-alpha.1` & `v0.8.5-beta.1`) to improve performances, I take the time to rename the criteria with shorter and clear names.

  - `sum of typos` becomes `typo`
  - `number of words` becomes `words`
  - `words proximity` becomes `proximity`
  - `sum of words attribute` becomes `attribute`
  - `sum of words position` becomes `words position`
  - `exact` remains `exact`

This is just a remainder to update the documentation examples that refers to old names.

**Comment by bidoubiwa** [comment]
Is this change in version v0.8 or will be added in v0.9 ?

**Comment by bidoubiwa** [comment]
fixes: #103

**Comment by Kerollmops** [comment]
Just to be sure, the `exact` criterion is also renamed in `exactness`.
