### ISSUE TITLE
Create download button for movie dataset

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#919]
During the getting started we suggest to the user to use our movie dataset. Nonetheless we do not provide an easy way to download it. 

We should add a button `download movie dataset` that trigger automatic download of movies.json. 

Some useful references: 

https://www.w3schools.com/tags/att_a_download.asp

**Comment by maryamsulemani97** [comment]
@bidoubiwa currently the user can download the dataset by [clicking the link](https://docs.meilisearch.com/learn/getting_started/quick_start.html#step-2-add-documents), does that resolve this?

**Comment by bidoubiwa** [comment]
The idea was to make a button that pops to the eyes. But the link is already a good thing :)

**Comment by guimachiavelli** [comment]
My 0.02€: I would be in favour of closing this. Homepage excluded, we have no other buttons in the middle of an article, so I'm afraid a download button might feel out of place and inconsistent with behaviour elsewhere on the docs website.

**Comment by bidoubiwa** [comment]
Good for me :)
