### ISSUE TITLE
Prepare documentation for v0.21

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#931]
v0.21 of MeiliSearch contains a code refactor. The code refactor splits MeiliSearch into two parts: **milli**, a prefix search library (the "engine", so to speak), and **transplant**, a REST API.

This shouldn't have an impact on users; however the large number of [breaking changes](https://github.com/meilisearch/transplant/projects/1) (see column: "Done & definitely breaking") and major performance improvements certainly will.

PR here: #924

**Comment by guimachiavelli** [comment]
Closed by #924
