### ISSUE TITLE
Couldn't get Getting Started JavaScript example to run

### ISSUE THREAD

**Issue by alanwsmith** [meilisearch/documentation#933]
On this page:

https://docs.meilisearch.com/learn/getting_started/quick_start.html#search

The JavaScript example for Search is:

```javascript
index.search('botman').then((res) => console.log(res))
```

I couldn't get that to run given the previous code on the page. I.e.

```javascript
npm install meilisearch

const { MeiliSearch } = require('meilisearch')
const movies = require('./data/movies.json')

const client = new MeiliSearch({ host: 'http://127.0.0.1:7700' })

client.index('movie').addDocuments(movies)
  .then((res) => console.log(res))
```

When I changed the code to this, it worked:

```javascript
client.index('movie').search('botman').then((res) => console.log(res))
```

**Comment by react-learner** [comment]
Thanks for spotting this @alanwsmith ! Should be fixed shortly by [this PR](https://github.com/meilisearch/meilisearch-js/pull/903).
