### ISSUE TITLE
Clarify primary key

### ISSUE THREAD

**Issue by alallema** [meilisearch/documentation#934]
At [this](https://docs.meilisearch.com/reference/api/documents.html#add-or-replace-documents) point in the documentation, it is written:
`The primary key of the documents`
then
`the primary key of your index`
This was not clear to me. Whose primary key was it? Also, it's on me because I don't know why I bypass the Structure of the document [here](https://docs.meilisearch.com/learn/core_concepts/documents.html#structure). Which turned out to be very enlightening.
The link of the document about PrimaryKey send me directly [here](https://docs.meilisearch.com/learn/core_concepts/documents.html#primary-field).

**Comment by react-learner** [comment]
Thank you for pointing this out!

**Comment by guimachiavelli** [comment]
If I understand this correctly, using `primary key of the index` is clearer and more correct, right?
