### ISSUE TITLE
Add intro paragraph to Quick Start

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#956]
I think the main point here would be to state more clearly who is the intended audience of this tutorial and what we expect them to know.

Familiarity with the CLI for sure, given how we start right off the bat with `curl`.

The last section, `Integrate with Your Project`, requires some understanding of basic programming concepts if the user is to be able to apply what they learned here somewhere else, I think.

I guess we do use JSON, but understanding what it is doesn't seem particularly important at this stage.

Anything else?

**Comment by misterbastean** [comment]
Added intro paragraph, PR #959
