### ISSUE TITLE
Create a reminder that the documentation follows the master branch and not the tag

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#96]

**Comment by tpayet** [comment]
Until MeiliSearch is stable (<1.0.0), the documentation should be up to date with the latest tag (v0.8.4 today).

- For each new target release, we will create a milestone on this repository
- Each PR on MeiliSearch's repository will be linked to an Issue or a PR on this repository (documentation)
- MeiliSearch won't be released under a new tag until all the documentation have been written and is ready to merge on this repo
