### ISSUE TITLE
Add .nvmrc to repo

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#963]
Ran into the [node versioning issue](https://github.com/meilisearch/documentation/pull/951) reported by @bidoubiwa earlier this week. 

Adding the node version requirement to the readme is great, but perhaps we should look into adding support for [NVM](https://github.com/nvm-sh/nvm)?

For those unfamiliar, NVM stands for Node Version Manager and works more or less like [RVM](https://rvm.io/): it looks for .nvmrc files specifying a node version and installs/switches to the required node version. When it works, at least.

Not sure how many contributors will have NVM installed on their machines, but it might make life easier for those who do.

**Comment by bidoubiwa** [comment]
Good idea! We can also add this in the package.json

```js
"engines": {
    "node": ">=12 <15"
  }
```

based on this [doc](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines)

and to force the error message if the node version is not good the [following StackOverflow](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json) recommend this: 

> As ben pointed out below, creating a .npmrc file at the root of your project (the same level as your package.json file) with the text engine-strict=true will force an error during installation if the Node version is not compatible.

Thanks so much for having looked into it more
