### ISSUE TITLE
Anchor links not working reliably on Deploy and Integrate guides

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#971]
In the [Deploy on AWS guide](https://docs.meilisearch.com/create/how_to/aws.html), the ToC links do not work reliably: sometimes they lead me to a section header, sometimes they don't. I see the same behaviour in the [GCP guide](https://docs.meilisearch.com/create/how_to/gcp.html), but, weirdly enough, not in the [Run in Production guide](https://docs.meilisearch.com/create/how_to/running_production.html).

This issue seems to be restricted to Firefox. Safari works ok-ish (smooth scrolling doesn't always work); Google Chrome works without a hitch.

**Comment by dichotommy** [comment]
Just a hunch, but I think this is a problem with how VuePress handles image load-in. I notice that in guides with lots of images, clicking a link will bring me to the "original" location of the header (i.e. before images), which is not useful now that images have loaded and pushed the text further down the page. Is this the same problem you're noticing?

**Comment by guimachiavelli** [comment]
Yeah, you're right. Will mark it as P4 (won't fix).
