### ISSUE TITLE
Make it obvious that logs are not displayed on production mode

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#978]
ATM, the documentation states that `if the server is running in development mode more logs will be displayed`, after that it is said that `In production mode, the web interface is disabled.`. I think we should add that logs are also disabled.

**Comment by guimachiavelli** [comment]
Will be resolved by #976

**Comment by guimachiavelli** [comment]
Just to confirm, there is no logging at all when `environment` is set to `production`, right?

**Comment by CaroFG** [comment]
Well, I haven't done a lot of tests myself, just a coupe of search requests and I had no logs at all. But I have [this](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1623328077276000?thread_ts=1623316414.256400&cid=CP9DVS1RQ) comment and conversation with a user which didn't have any logs at all on production mode.

**Comment by guimachiavelli** [comment]
ok, thanks. It does sound odd that production has no logging at all, should definitely be in the docs.

**Comment by CaroFG** [comment]
I think this may change with the new release as stated in this [spec](https://github.com/meilisearch/specifications/pull/33/files)

**Comment by guimachiavelli** [comment]
Perhaps worth checking with core whether this will be included in v0.21, @dichotommy?

**Comment by guimachiavelli** [comment]
Confirmed logging will change on v0.21 and follow the [spec](https://github.com/meilisearch/specifications/pull/33/files).

PR #976 will bring docs up-to-date with current behaviour. 

Things related to v0.21 will be handled by #924.
