### ISSUE TITLE
How to disable telemetry on meilisearch digitalocean snapshot?

### ISSUE THREAD

**Issue by diazsasak** [meilisearch/documentation#995]
i install meilisearch using this method. how can i disable the anonymous telemetry? thanks

https://docs.meilisearch.com/create/how_to/digitalocean_droplet.html#_8-your-meilisearch-is-running-in-development-environment

**Comment by diazsasak** [comment]
no information about the telemetry. but we can see the command with --no-analytics argument

![image](https://user-images.githubusercontent.com/7880137/122303159-a990fd80-cf35-11eb-8aa3-03e6405073da.png)

**Comment by curquiza** [comment]
Weird, I've just done all the steps to test, and I got the `Anonymous Telemetry: Disabled`

<img width="1238" alt="Capture d’écran 2021-06-22 à 10 41 38" src="https://user-images.githubusercontent.com/20380692/122893458-a4252000-d346-11eb-8440-24853de5009a.png">

**Comment by dichotommy** [comment]
We are going to add this information to the docs, but would like to confirm that the same procedure works for GCP and AWS deploys.

@alallema Hi Amélie, could you please check that setting config options works the same for AWS and GCP images as it is for a DO droplet? e.g. it should work with the following commands

> modify the /etc/systemd/system/meilisearch.service by adding the flag --no-analytics=true at the end of the command in ExecStart.
> relaunch the meilisearch service: systemctl restart meilisearch

**Comment by CaroFG** [comment]
We should also document how to configure MeiliSearch, change the payload size, and other options the user might want to change...

**Comment by alallema** [comment]
@dichotommy,
Sorry for the delay. It's the same procedure on aws too.
