### ISSUE TITLE
Question about snapshot feature

### ISSUE THREAD

**Issue by JokerQyou** [meilisearch/documentation#999]
From [the doc about snapshot](https://docs.meilisearch.com/reference/features/snapshots.html#creating-snapshots):

> The first snapshot is created on launching MeiliSearch. After that, snapshots are created routinely on a set interval until you deactivate snapshots or end the MeiliSearch instance. By default, one snapshot is taken every 24 hours.

But it does not describe how exactly one could **deactivate snapshot**.

Initially I thought snapshotting was like [dumping](https://docs.meilisearch.com/reference/api/dump.html#create-a-dump), which is accessible via an HTTP API. But it's not. Turns out that snapshotting is actually enabled via a command-line option, and the MeiliSearch instance itself controls it.

So how can we deactivate snapshots without ending the MeiliSearch instance? Is it a planned feature yet to be implemented, or is it just a typo in the doc?

**Comment by dichotommy** [comment]
Hi @JokerQyou , to my knowledge it is not yet possible to deactivate snapshots (or any other configuration option, for that matter) without terminating and restarting the MeiliSearch instance. As to whether it's a planned feature or not, I'll have to check with our devs.

Thanks a bunch for spotting this misleading phrase! 😁 🎉
